import type {
  AcademicFeaturedWork, AcademicProfile, AcademicProfileType, AcademicReviewType,
  AcademicVerificationEvidence, CompactAcademicProfile, PublicAcademicProfile,
  ResearchSupportType, VerificationEvidenceType,
} from "@trend/shared-types";
import { AppError } from "../../common/exceptions/app-error.js";
import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import { auditService } from "../audit/audit.service.js";
import { notificationService } from "../notifications/notification.service.js";
import { evaluateLecturerVerificationEvidence } from "./academic-verification.policy.js";
import { institutionalEmailVerificationService } from "./institutional-email-verification.service.js";
import type { LecturerListQueryInput, UpdateAcademicProfileDetailsInput, VerificationDecisionInput } from "./dto/academic-profile.schema.js";
import { isValidPublicHandle, normalizePublicHandle } from "./public-handle.js";

type LooseRecord = Record<string, unknown>;
function legacyType(role: string): AcademicProfileType | undefined { return ["student", "researcher", "lecturer"].includes(role) ? role as AcademicProfileType : undefined; }
function record(value: unknown): LooseRecord { return value && typeof value === "object" ? value as LooseRecord : {}; }
function stringValue(value: unknown): string | undefined { return typeof value === "string" && value.length > 0 ? value : undefined; }
function stringArray(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function iso(value: unknown): string | undefined { if (!value) return undefined; const date = value instanceof Date ? value : new Date(String(value)); return Number.isNaN(date.valueOf()) ? undefined : date.toISOString(); }
function normalizeSupportTypes(value: unknown): ResearchSupportType[] { const aliases: Record<string, ResearchSupportType | undefined> = { RESEARCH_DIRECTION: "RESEARCH_DIRECTION", LITERATURE_REVIEW: "LITERATURE_REVIEW", RESEARCH_GAP_VALIDATION: "RESEARCH_GAP_VALIDATION", METHODOLOGY: "RESEARCH_METHODOLOGY", RESEARCH_METHODOLOGY: "RESEARCH_METHODOLOGY", EXPERIMENT_DESIGN: "EXPERIMENT_DESIGN", DATA_ANALYSIS: "DATA_ANALYSIS", ACADEMIC_WRITING: "ACADEMIC_WRITING", SOFTWARE_TECHNICAL_REVIEW: "SOFTWARE_TECHNICAL_GUIDANCE", SOFTWARE_TECHNICAL_GUIDANCE: "SOFTWARE_TECHNICAL_GUIDANCE" }; return [...new Set(stringArray(value).map((item) => aliases[item]).filter((item): item is ResearchSupportType => Boolean(item)))]; }
function normalizeReviewTypes(value: unknown): AcademicReviewType[] { const aliases: Record<string, AcademicReviewType | undefined> = { RESEARCH_PROPOSAL: "RESEARCH_PROPOSAL", LITERATURE_REVIEW: "LITERATURE_REVIEW", RESEARCH_GAP: "RESEARCH_GAP", METHODOLOGY: "METHODOLOGY", EXPERIMENT_REPORT: "EXPERIMENTAL_RESULTS", EXPERIMENTAL_RESULTS: "EXPERIMENTAL_RESULTS", MANUSCRIPT: "RESEARCH_PAPER", RESEARCH_PAPER: "RESEARCH_PAPER", SOFTWARE_RESEARCH_PROJECT: "SOFTWARE_RESEARCH_PROJECT" }; return [...new Set(stringArray(value).map((item) => aliases[item]).filter((item): item is AcademicReviewType => Boolean(item)))]; }
function idWhere(value: string): { id: string } | { legacyMongoId: string } { const parsed = parseDatabaseId(value); if (!parsed) throw AppError.notFound("Academic profile not found"); return parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; }
async function resolveUser(value: string) { const user = await getPrisma().user.findUnique({ where: idWhere(value) }); if (!user?.isActive) throw AppError.notFound("Academic profile not found"); return user; }
async function resolveProfile(value: string) { const profile = await getPrisma().academicProfile.findUnique({ where: idWhere(value) }); if (!profile) throw AppError.notFound("Academic profile not found"); return profile; }

async function buildPrivateProfile(userId: string): Promise<AcademicProfile> {
  const prisma = getPrisma(); const user = await resolveUser(userId); const academicType = user.academicProfileType ?? legacyType(user.role); if (!academicType) throw AppError.notFound("Academic profile not found");
  const profile = await prisma.academicProfile.upsert({ where: { userId: user.id }, create: { userId: user.id, verificationStatus: "SELF_DECLARED" }, update: {} });
  const [identities, works, evidence] = await Promise.all([prisma.academicExternalIdentity.findMany({ where: { profileId: profile.id }, orderBy: { position: "asc" } }), prisma.academicFeaturedWork.findMany({ where: { profileId: profile.id }, orderBy: { position: "asc" } }), prisma.academicVerificationEvidence.findMany({ where: { profileId: profile.id }, orderBy: { createdAt: "asc" } })]);
  const support = record(profile.supportAvailability), review = record(profile.reviewAvailability); const status = ["PENDING", "VERIFIED", "REJECTED"].includes(profile.verificationStatus) ? profile.verificationStatus as "PENDING" | "VERIFIED" | "REJECTED" : "SELF_DECLARED"; const publicUserId = publicDatabaseId(user);
  return {
    id: publicDatabaseId(profile), userId: publicUserId, points: Math.max(0, user.points), publicHandle: profile.publicHandle ?? undefined,
    academicType: academicType as AcademicProfileType, displayName: user.fullName, avatarUrl: user.avatarUrl ?? undefined,
    coverUrl: profile.coverStorageKey ? `/academic-profiles/${publicUserId}/cover?v=${profile.coverUpdatedAt?.getTime() ?? 1}` : undefined,
    profileVisibility: profile.profileVisibility as AcademicProfile["profileVisibility"], headline: profile.headline ?? undefined,
    biography: profile.biography ?? undefined, bio: profile.biography ?? undefined, academicTitle: profile.academicTitle as AcademicProfile["academicTitle"],
    affiliation: { institutionName: user.institution ?? undefined, rorId: profile.affiliationRorId ?? undefined, department: profile.affiliationDepartment ?? undefined, position: profile.affiliationPosition ?? undefined, startYear: profile.affiliationStartYear ?? undefined, institutionalEmail: profile.institutionalEmail ?? undefined, institutionalEmailVerifiedAt: profile.institutionalEmailVerifiedAt?.toISOString() },
    institution: user.institution ?? undefined, department: profile.affiliationDepartment ?? undefined, institutionalEmail: profile.institutionalEmail ?? undefined,
    researchInterests: user.researchInterests, expertiseAreas: profile.expertiseAreas, skills: profile.skills, researchKeywords: profile.researchKeywords,
    externalIdentities: identities.map((identity) => ({ provider: identity.provider as AcademicProfile["externalIdentities"][number]["provider"], externalId: identity.externalId ?? undefined, profileUrl: identity.profileUrl ?? undefined, status: identity.status as AcademicProfile["externalIdentities"][number]["status"], source: identity.source as AcademicProfile["externalIdentities"][number]["source"], linkedAt: identity.linkedAt?.toISOString(), verifiedAt: identity.verifiedAt?.toISOString() })),
    featuredWorks: works.map((work) => ({ paperId: work.paperId ?? undefined, doi: work.doi ?? undefined, title: work.title ?? undefined, year: work.year ?? undefined, source: work.source as AcademicFeaturedWork["source"], canonical: work.paperId !== null })),
    supportAvailability: { enabled: support.enabled === true, types: normalizeSupportTypes(support.types), preferredTopics: stringArray(support.preferredTopics), note: stringValue(support.note), updatedAt: iso(support.updatedAt) },
    reviewAvailability: { enabled: review.enabled === true, types: normalizeReviewTypes(review.types), preferredTopics: stringArray(review.preferredTopics), acceptedFields: stringArray(review.acceptedFields), maximumActiveReviews: typeof review.maximumActiveReviews === "number" ? review.maximumActiveReviews : 3, preferredReviewWorkload: stringValue(review.preferredReviewWorkload), note: stringValue(review.note), temporarilyUnavailableUntil: iso(review.temporarilyUnavailableUntil), autoRecommendationEnabled: review.autoRecommendationEnabled !== false, updatedAt: iso(review.updatedAt) },
    verificationStatus: status, verification: { status, requestedAt: profile.verificationRequestedAt?.toISOString(), verifiedAt: profile.verifiedAt?.toISOString(), verifiedBy: profile.verifiedById ?? undefined, rejectedAt: profile.rejectedAt?.toISOString(), rejectedBy: profile.rejectedById ?? undefined, rejectionReason: profile.rejectionReason ?? undefined, method: profile.verificationMethod ?? undefined, adminNote: profile.verificationNote ?? undefined },
    verificationEvidence: evidence.map((item) => ({ type: item.type as AcademicProfile["verificationEvidence"][number]["type"], value: item.value ?? undefined, status: item.status as AcademicProfile["verificationEvidence"][number]["status"], source: item.source as AcademicProfile["verificationEvidence"][number]["source"], createdAt: item.createdAt.toISOString(), validatedAt: item.validatedAt?.toISOString() })),
    createdAt: profile.createdAt.toISOString(), updatedAt: profile.updatedAt.toISOString(),
  };
}

function toPublicProfile(profile: AcademicProfile): PublicAcademicProfile { const { id: _id, institutionalEmail: _email, verification: _verification, verificationEvidence: _evidence, affiliation, reviewAvailability, ...safe } = profile; const unavailable = reviewAvailability.temporarilyUnavailableUntil ? new Date(reviewAvailability.temporarilyUnavailableUntil).getTime() > Date.now() : false; return { ...safe, affiliation: { institutionName: affiliation.institutionName, rorId: affiliation.rorId, department: affiliation.department, position: affiliation.position, startYear: affiliation.startYear }, reviewAvailability: { enabled: reviewAvailability.enabled && !unavailable, types: reviewAvailability.types, preferredTopics: reviewAvailability.preferredTopics, acceptedFields: reviewAvailability.acceptedFields, note: reviewAvailability.note, updatedAt: reviewAvailability.updatedAt } }; }
function assertVisible(profile: AcademicProfile, viewerId?: string) { if (profile.userId === viewerId || profile.profileVisibility === "PUBLIC" || profile.profileVisibility === "MEMBERS_ONLY" && viewerId) return; throw AppError.notFound("Academic profile not found"); }
function compact(profile: PublicAcademicProfile): CompactAcademicProfile { return { userId: profile.userId, publicHandle: profile.publicHandle, displayName: profile.displayName, avatarUrl: profile.avatarUrl, academicTitle: profile.academicTitle, institutionName: profile.affiliation.institutionName, verificationStatus: profile.verificationStatus, expertiseAreas: profile.expertiseAreas, supportAvailable: profile.supportAvailability.enabled, reviewAvailable: profile.reviewAvailability.enabled }; }

export const academicProfileService = {
  async getMine(userId: string) { return buildPrivateProfile(userId); },
  async getPublic(userId: string, viewerId?: string) { const profile = await buildPrivateProfile(userId); assertVisible(profile, viewerId); return toPublicProfile(profile); },
  async getPublicByHandle(handle: string, viewerId?: string) { const normalized = normalizePublicHandle(handle); if (!isValidPublicHandle(normalized)) throw AppError.notFound("Academic profile not found"); const claimed = await getPrisma().academicProfileHandle.findUnique({ where: { handle: normalized }, select: { userId: true } }); if (!claimed) throw AppError.notFound("Academic profile not found"); const profile = await buildPrivateProfile(claimed.userId); assertVisible(profile, viewerId); return toPublicProfile(profile); },
  async setPublicHandle(userId: string, rawHandle: string) { const handle = normalizePublicHandle(rawHandle); if (!isValidPublicHandle(handle)) throw AppError.badRequest("Invalid public profile URL"); const user = await resolveUser(userId); const current = await buildPrivateProfile(user.id); if (current.publicHandle === handle) return current; const prisma = getPrisma(); const existing = await prisma.academicProfileHandle.findUnique({ where: { handle } }); if (existing && existing.userId !== user.id) throw AppError.conflict("This public URL is already taken"); if (!existing && await prisma.academicProfileHandle.count({ where: { userId: user.id } }) >= 20) throw AppError.conflict("Public URL change limit reached"); try { await prisma.$transaction(async (tx) => { await tx.academicProfileHandle.upsert({ where: { handle }, create: { handle, userId: user.id }, update: {} }); await tx.academicProfile.upsert({ where: { userId: user.id }, create: { userId: user.id, publicHandle: handle }, update: { publicHandle: handle } }); }); } catch (error) { if ((error as { code?: string }).code === "P2002") throw AppError.conflict("This public URL is already taken"); throw error; } await auditService.log("academic_profile.public_handle.updated", { userId, targetTableName: "academic_profiles", targetRecordId: current.id, details: { previousHandle: current.publicHandle, newHandle: handle } }); return buildPrivateProfile(user.id); },
  async getCompact(userId: string, viewerId?: string) { const profile = await buildPrivateProfile(userId); assertVisible(profile, viewerId); return compact(toPublicProfile(profile)); },

  async updateMine(userId: string, input: UpdateAcademicProfileDetailsInput) {
    const prisma = getPrisma(); const user = await resolveUser(userId); const profile = await prisma.academicProfile.upsert({ where: { userId: user.id }, create: { userId: user.id }, update: {} }); const previousType = user.academicProfileType ?? legacyType(user.role); const requested = input.affiliation ?? {}; const requestedEmail = requested.institutionalEmail ?? input.institutionalEmail; const emailChanged = requestedEmail !== undefined && requestedEmail.toLowerCase() !== profile.institutionalEmail?.toLowerCase();
    const identities = await prisma.academicExternalIdentity.findMany({ where: { profileId: profile.id } }); const materialChanged = Boolean(input.academicType !== undefined && input.academicType !== previousType || input.displayName !== undefined && input.displayName !== user.fullName || (requested.institutionName ?? input.institution) !== undefined && (requested.institutionName ?? input.institution) !== user.institution || (requested.department ?? input.department) !== undefined && (requested.department ?? input.department) !== profile.affiliationDepartment || emailChanged || requested.rorId !== undefined && requested.rorId !== profile.affiliationRorId || requested.position !== undefined && requested.position !== profile.affiliationPosition || input.externalIdentities !== undefined && JSON.stringify(input.externalIdentities) !== JSON.stringify(identities.map((i) => ({ provider: i.provider, externalId: i.externalId ?? undefined, profileUrl: i.profileUrl ?? undefined }))));
    const featured = input.featuredWorks ?? []; const resolvedWorks = await Promise.all(featured.map(async (work) => { if (work.source !== "LUMIGAP") return { paperId: null, doi: work.doi ?? null, title: work.title ?? null, year: work.year ?? null, source: work.source }; const paper = await prisma.paper.findUnique({ where: idWhere(work.paperId!), select: { id: true } }); if (!paper) throw AppError.badRequest("One or more featured papers do not exist"); return { paperId: paper.id, doi: null, title: null, year: null, source: "LUMIGAP" }; })); const now = new Date();
    await prisma.$transaction(async (tx) => {
      await tx.user.update({ where: { id: user.id }, data: { ...(input.academicType !== undefined ? { academicProfileType: input.academicType } : {}), ...(input.displayName !== undefined ? { fullName: input.displayName } : {}), ...((requested.institutionName ?? input.institution) !== undefined ? { institution: (requested.institutionName ?? input.institution) || null } : {}), ...(input.researchInterests !== undefined ? { researchInterests: input.researchInterests } : {}) } });
      await tx.academicProfile.update({ where: { id: profile.id }, data: { ...(input.headline !== undefined ? { headline: input.headline || null } : {}), ...(input.profileVisibility !== undefined ? { profileVisibility: input.profileVisibility } : {}), ...((input.biography ?? input.bio) !== undefined ? { biography: (input.biography ?? input.bio) || null } : {}), ...(input.academicTitle !== undefined ? { academicTitle: input.academicTitle } : {}), ...(input.expertiseAreas !== undefined ? { expertiseAreas: input.expertiseAreas } : {}), ...(input.skills !== undefined ? { skills: input.skills } : {}), ...(input.researchKeywords !== undefined ? { researchKeywords: input.researchKeywords } : {}), ...(requested.rorId !== undefined ? { affiliationRorId: requested.rorId || null } : {}), ...((requested.department ?? input.department) !== undefined ? { affiliationDepartment: (requested.department ?? input.department) || null } : {}), ...(requested.position !== undefined ? { affiliationPosition: requested.position || null } : {}), ...(requested.startYear !== undefined ? { affiliationStartYear: requested.startYear } : {}), ...(requestedEmail !== undefined ? { institutionalEmail: requestedEmail || null } : {}), ...(input.supportAvailability !== undefined ? { supportAvailability: { ...input.supportAvailability, updatedAt: now.toISOString() } as never } : {}), ...(input.reviewAvailability !== undefined ? { reviewAvailability: { ...input.reviewAvailability, updatedAt: now.toISOString() } as never } : {}), ...(emailChanged ? { institutionalEmailVerifiedAt: null } : {}), ...(materialChanged && ["VERIFIED", "PENDING"].includes(profile.verificationStatus) ? { verificationStatus: "SELF_DECLARED", verificationRequestedAt: null, verifiedAt: null, verifiedById: null, rejectedAt: null, rejectedById: null, rejectionReason: null, verificationMethod: null, verificationNote: null } : {}) } });
      if (input.externalIdentities !== undefined) { await tx.academicExternalIdentity.deleteMany({ where: { profileId: profile.id } }); if (input.externalIdentities.length) await tx.academicExternalIdentity.createMany({ data: input.externalIdentities.map((identity, position) => { const old = identities.find((item) => item.provider === identity.provider && item.externalId === (identity.externalId ?? null) && item.profileUrl === (identity.profileUrl ?? null)); const trusted = old && ["OAUTH", "SYSTEM", "ADMIN"].includes(old.source); return { profileId: profile.id, provider: identity.provider, externalId: identity.externalId, profileUrl: identity.profileUrl, status: trusted ? old.status : "UNVERIFIED", source: trusted ? old.source : "SELF_ASSERTED", linkedAt: trusted ? old.linkedAt : null, verifiedAt: trusted ? old.verifiedAt : null, position }; }) }); }
      if (input.featuredWorks !== undefined) { await tx.academicFeaturedWork.deleteMany({ where: { profileId: profile.id } }); if (resolvedWorks.length) await tx.academicFeaturedWork.createMany({ data: resolvedWorks.map((work, position) => ({ profileId: profile.id, ...work, position })) }); }
      if (emailChanged || materialChanged && ["VERIFIED", "PENDING"].includes(profile.verificationStatus)) await tx.academicVerificationEvidence.deleteMany({ where: { profileId: profile.id } });
    });
    if (emailChanged) await institutionalEmailVerificationService.invalidate(user.id); await auditService.log("academic_profile.updated", { userId, targetTableName: "academic_profiles", targetRecordId: profile.id, details: { fields: Object.keys(input).filter((field) => !["institutionalEmail", "affiliation"].includes(field)) } }); if (materialChanged && ["VERIFIED", "PENDING"].includes(profile.verificationStatus)) await auditService.log("academic_profile.verification.reset", { userId, targetTableName: "academic_profiles", targetRecordId: profile.id, details: { previousStatus: profile.verificationStatus, reason: "identity_material_changed" } }); return buildPrivateProfile(user.id);
  },

  async getVerificationStatus(userId: string) { const profile = await this.getMine(userId); return { academicType: profile.academicType, verification: profile.verification }; },
  async requestVerification(userId: string) { const prisma = getPrisma(); const user = await resolveUser(userId); if ((user.academicProfileType ?? legacyType(user.role)) !== "lecturer") throw AppError.forbidden("Only lecturer profiles can request verification"); const profile = await prisma.academicProfile.findUnique({ where: { userId: user.id } }); if (!profile || !profile.institutionalEmail || !user.institution || !profile.affiliationDepartment) throw AppError.badRequest("Institution, department, and institutional email are required"); if (!profile.institutionalEmailVerifiedAt) throw AppError.badRequest("Verify the institutional email before requesting Lecturer verification"); if (["PENDING", "VERIFIED"].includes(profile.verificationStatus)) throw AppError.conflict("Verification is already pending or approved"); const identities = await prisma.academicExternalIdentity.findMany({ where: { profileId: profile.id, provider: "ORCID" } }); const existing = await prisma.academicVerificationEvidence.findMany({ where: { profileId: profile.id, type: { not: "ORCID" } } }); const now = new Date(); const evidence: AcademicVerificationEvidence[] = [...existing.map((item) => ({ type: item.type as VerificationEvidenceType, value: item.value ?? undefined, status: item.status as AcademicVerificationEvidence["status"], source: item.source as AcademicVerificationEvidence["source"], createdAt: item.createdAt.toISOString(), validatedAt: item.validatedAt?.toISOString() })), ...identities.map((identity) => ({ type: "ORCID" as const, value: identity.externalId ?? identity.profileUrl ?? undefined, status: "SUBMITTED" as const, source: "USER" as const, createdAt: now.toISOString() }))]; const domain = profile.institutionalEmail.slice(profile.institutionalEmail.lastIndexOf("@") + 1).toLowerCase(); const trustedDomain = await prisma.trustedInstitutionDomain.findUnique({ where: { domain } }); const institution = trustedDomain ? await prisma.trustedInstitution.findUnique({ where: { id: trustedDomain.institutionId } }) : null; const policyRecord = record(institution?.verificationPolicy); const policy = evaluateLecturerVerificationEvidence({ institutionalEmailVerified: true, evidence, allowedAutoVerifyMethods: stringArray(policyRecord.autoVerifyMethods) as VerificationEvidenceType[] }); if (policy.decision === "NOT_ELIGIBLE") throw AppError.badRequest("Verified institutional email evidence is required"); const auto = policy.decision === "AUTO_VERIFIED";
    await prisma.$transaction(async (tx) => { await tx.academicVerificationEvidence.deleteMany({ where: { profileId: profile.id } }); if (evidence.length) await tx.academicVerificationEvidence.createMany({ data: evidence.map((item) => ({ profileId: profile.id, type: item.type, value: item.value, status: item.status, source: item.source, createdAt: new Date(item.createdAt), validatedAt: item.validatedAt ? new Date(item.validatedAt) : null })) }); await tx.academicProfile.update({ where: { id: profile.id }, data: { verificationStatus: auto ? "VERIFIED" : "PENDING", verificationRequestedAt: now, verifiedAt: auto ? now : null, verificationMethod: auto ? "DETERMINISTIC_EVIDENCE_POLICY" : null, rejectionReason: null, rejectedAt: null, rejectedById: null } }); }); await auditService.log("academic_profile.verification.requested", { userId, targetTableName: "academic_profiles", targetRecordId: profile.id, details: { evidenceTypes: evidence.map((item) => item.type), policyDecision: policy.decision, reasons: policy.reasons } }); return buildPrivateProfile(user.id);
  },
  async listVerificationRequests(status: string, page: number, pageSize: number) { const where = { verificationStatus: status }; const [profiles, total] = await Promise.all([getPrisma().academicProfile.findMany({ where, orderBy: { verificationRequestedAt: "asc" }, skip: (page - 1) * pageSize, take: pageSize }), getPrisma().academicProfile.count({ where })]); return { data: await Promise.all(profiles.map((profile) => buildPrivateProfile(profile.userId))), meta: { page, pageSize, total, totalPages: Math.max(1, Math.ceil(total / pageSize)) } }; },
  async getVerificationDetails(profileId: string) { return buildPrivateProfile((await resolveProfile(profileId)).userId); },
  async decideVerification(profileId: string, input: VerificationDecisionInput, adminId: string) { const prisma = getPrisma(); const [profile, admin] = await Promise.all([resolveProfile(profileId), resolveUser(adminId)]); if (profile.verificationStatus !== "PENDING" || profile.userId === admin.id) throw AppError.conflict("Only a pending verification can be decided by another user"); const now = new Date(); const approved = input.decision === "approve"; await prisma.$transaction(async (tx) => { await tx.academicProfile.update({ where: { id: profile.id }, data: approved ? { verificationStatus: "VERIFIED", verifiedAt: now, verifiedById: admin.id, rejectedAt: null, rejectedById: null, rejectionReason: null, verificationMethod: input.method ?? "ADMIN_REVIEW", verificationNote: input.note } : { verificationStatus: "REJECTED", verifiedAt: null, verifiedById: null, rejectedAt: now, rejectedById: admin.id, rejectionReason: input.reason, verificationMethod: "ADMIN_REVIEW", verificationNote: input.note } }); await tx.academicVerificationEvidence.updateMany({ where: { profileId: profile.id, status: "SUBMITTED" }, data: { status: approved ? "VALIDATED" : "REJECTED", ...(approved ? { validatedAt: now } : {}) } }); }); await auditService.log(`academic_profile.verification.${input.decision}d`, { userId: adminId, targetTableName: "academic_profiles", targetRecordId: profile.id, details: { decision: input.decision, targetUserId: profile.userId } }); await notificationService.create({ userId: profile.userId, title: approved ? "Lecturer verification approved" : "Lecturer verification rejected", message: approved ? "Your lecturer academic profile is now verified." : "Your lecturer verification request needs changes. Open Academic Profile for details.", type: `lecturer_verification_${approved ? "approved" : "rejected"}`, targetKind: "academic_profile", targetId: profile.id }); return buildPrivateProfile(profile.userId); },
  async listLecturers(query: LecturerListQueryInput) { const prisma = getPrisma(); const users = await prisma.user.findMany({ where: { isActive: true, OR: [{ academicProfileType: "lecturer" }, { academicProfileType: null, role: "lecturer" }], ...(query.institution ? { institution: { contains: query.institution, mode: "insensitive" } } : {}), ...(query.researchInterest ? { researchInterests: { has: query.researchInterest } } : {}) }, select: { id: true } }); const ids = users.map((user) => user.id); const where = { userId: { in: ids }, profileVisibility: "PUBLIC", ...(query.verifiedOnly ? { verificationStatus: "VERIFIED" } : {}), ...(query.expertise ? { expertiseAreas: { has: query.expertise } } : {}), ...(query.supportAvailable !== undefined ? { supportAvailability: { path: ["enabled"], equals: query.supportAvailable } } : {}), ...(query.reviewAvailable !== undefined ? { reviewAvailability: { path: ["enabled"], equals: query.reviewAvailable } } : {}) }; const [profiles, total] = await Promise.all([prisma.academicProfile.findMany({ where, orderBy: [{ verifiedAt: "desc" }, { updatedAt: "desc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.academicProfile.count({ where })]); return { data: await Promise.all(profiles.map((profile) => this.getCompact(profile.userId))), meta: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.max(1, Math.ceil(total / query.pageSize)) } }; },
  async isVerifiedLecturer(userId: string) { const user = await resolveUser(userId); const profile = await getPrisma().academicProfile.findUnique({ where: { userId: user.id }, select: { verificationStatus: true } }); return (user.academicProfileType ?? legacyType(user.role)) === "lecturer" && profile?.verificationStatus === "VERIFIED"; },
};
