import crypto from "node:crypto";
import { parseDatabaseId } from "../../../infrastructure/database/database-id.js";
import { getPrisma } from "../../../infrastructure/database/prisma.js";
import { fetchOpenAlexPage } from "../providers/openalex.client.js";
import { ingestOpenAlexWorks } from "../sync.service.js";
import { ingestCampaignService } from "./ingest-campaign.service.js";
import { OPENALEX_CAMPAIGN_SAMPLE_SIZE } from "./campaign-planner.js";

export type CampaignPartitionRunResult = { status: "not-running" | "no-partition" } | { status: "completed" | "continued"; campaignId: string; partitionId: string; acceptedCount: number };
function whereId(value: string) { const parsed = parseDatabaseId(value); return parsed ? (parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }) : null; }
const sha256 = (value: string) => crypto.createHash("sha256").update(value).digest("hex");

export async function runCampaignPartitionPage(input: { campaignId: string; workerId: string; leaseMs: number }): Promise<CampaignPartitionRunResult> {
  const campaignWhere = whereId(input.campaignId); if (!campaignWhere) return { status: "not-running" }; const campaign = await getPrisma().openAlexIngestCampaign.findUnique({ where: campaignWhere }); if (!campaign || campaign.state !== "running") return { status: "not-running" };
  const partition = await ingestCampaignService.claimNextPartition(input); if (!partition) { await ingestCampaignService.reconcileCampaignProgress(input.campaignId); await ingestCampaignService.completeIfFinished(input.campaignId); return { status: "no-partition" }; }
  const partitionId = partition._id.toString(), cursorBefore = partition.checkpoint?.cursor ?? "*", remaining = Math.max(0, partition.targetCount - (partition.checkpoint?.acceptedCount ?? 0));
  if (!remaining) { await ingestCampaignService.markPartition({ partitionId, workerId: input.workerId, state: "completed" }); return { status: "completed", campaignId: input.campaignId, partitionId, acceptedCount: 0 }; }
  if (partition.selectionMethod === "repair" || (partition.selectionMethod === "seeded-sample" && (!Number.isInteger(partition.seed) || remaining > OPENALEX_CAMPAIGN_SAMPLE_SIZE))) { await getPrisma().ingestDeadLetter.create({ data: { campaignId: campaign.id, partitionId: partition.id, state: "open", reasonCode: "INVALID_PARTITION", details: { selectionMethod: partition.selectionMethod, seed: partition.seed, remaining } as never } }); await ingestCampaignService.markPartition({ partitionId, workerId: input.workerId, state: "dead_letter", errorMessage: "Invalid or unsupported partition" }); return { status: "completed", campaignId: input.campaignId, partitionId, acceptedCount: 0 }; }
  const request = { filterExpression: partition.filterExpression, cursor: cursorBefore, ...(partition.selectionMethod === "seeded-sample" ? { sample: partition.targetCount, seed: partition.seed! } : {}), perPage: Math.min(100, remaining) }; const fingerprint = sha256(JSON.stringify(request)); const attempt = await ingestCampaignService.beginAttempt({ campaignId: input.campaignId, partitionId, cursorBefore, seed: partition.seed ?? undefined, requestFingerprint: fingerprint });
  try { await ingestCampaignService.renewPartitionLease({ partitionId, workerId: input.workerId, leaseMs: input.leaseMs }); const page = await fetchOpenAlexPage(request); const provider = await getPrisma().apiProvider.findUnique({ where: { providerName: "openalex" } }); if (!provider) throw new Error("openalex provider is not seeded"); const ingested = await ingestOpenAlexWorks(page.results, provider.id); await getPrisma().paperCohortMembership.createMany({ data: ingested.records.map(({ paper }) => ({ paperId: paper.id, cohortId: partition.cohortId, campaignId: campaign.id, stratumKey: partition.stratumKey, selectionMethod: partition.selectionMethod, policyVersion: "openalex-domain-proportional-v1", reason: "campaign", selectedAt: new Date() })), skipDuplicates: true }); const committed = await ingestCampaignService.commitAttemptAndAdvanceCheckpoint({ attemptId: attempt._id.toString(), partitionId, expectedCheckpointVersion: partition.checkpoint?.version ?? 0, cursorAfter: page.nextCursor ?? undefined, responseHash: sha256(JSON.stringify(page.results)), expectedResultCount: page.results.length, acceptedCount: ingested.records.length, rejectedCount: ingested.rejectedCount, conflictCount: 0 }); if (!committed.checkpointAdvanced) throw new Error("Partition checkpoint CAS failed"); const refreshed = await getPrisma().openAlexIngestPartition.findUniqueOrThrow({ where: { id: partition.id } }); const finished = !page.nextCursor || !page.results.length || refreshed.acceptedCount >= refreshed.targetCount; await ingestCampaignService.markPartition({ partitionId, workerId: input.workerId, state: finished ? "completed" : "retry_wait" }); await ingestCampaignService.reconcileCampaignProgressIfDue(input.campaignId); if (finished) await ingestCampaignService.completeIfFinished(input.campaignId); return { status: finished ? "completed" : "continued", campaignId: input.campaignId, partitionId, acceptedCount: ingested.records.length }; } catch (error) { await getPrisma().openAlexIngestPageAttempt.update({ where: { id: attempt.id }, data: { state: "failed", errorMessage: (error instanceof Error ? error.message : String(error)).slice(0, 2000) } }).catch(() => undefined); await ingestCampaignService.markPartition({ partitionId, workerId: input.workerId, state: "retry_wait", errorMessage: error instanceof Error ? error.message : String(error) }); throw error; }
}
