import crypto from "node:crypto";
import { AppError } from "../../../common/exceptions/app-error.js";
import { parseDatabaseId, publicDatabaseId } from "../../../infrastructure/database/database-id.js";
import { getPrisma } from "../../../infrastructure/database/prisma.js";
import { OPENALEX_CAMPAIGN_SAMPLE_SIZE } from "./campaign-planner.js";

export interface CreateCampaignInput { campaignKey: string; campaignKind: "backfill" | "refresh" | "repair"; targetUniqueWorks: number; manifest: Record<string, unknown> }
export interface PlannedPartitionInput { partitionKey: string; cohortId: string; stratumKey: string; filterExpression: string; plannedPopulation: number; targetCount: number; selectionMethod: "seeded-sample" | "cursor" | "repair"; seed?: number }
export interface CreatePlannedCampaignInput extends CreateCampaignInput { partitions: PlannedPartitionInput[] }
export interface ClaimInput { campaignId: string; workerId: string; leaseMs: number; now?: Date }
export interface BeginAttemptInput { campaignId: string; partitionId: string; cursorBefore?: string; seed?: number; requestFingerprint: string }
export interface CommitAttemptInput { attemptId: string; partitionId: string; expectedCheckpointVersion: number; cursorAfter?: string; responseHash: string; expectedResultCount: number; acceptedCount: number; rejectedCount: number; conflictCount: number }
export interface MarkPartitionInput { partitionId: string; workerId: string; state: "completed" | "retry_wait" | "dead_letter"; errorMessage?: string }
function whereId(value: string) { const parsed = parseDatabaseId(value); if (!parsed) throw AppError.badRequest("Invalid identifier"); return parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; }
function present<T extends { id: string; legacyMongoId?: string | null }>(row: T) { const id = publicDatabaseId(row); const value = row as T & { checkpointCursor?: string | null; acceptedCount?: number; committedAttempts?: number; checkpointVersion?: number }; return { ...row, _id: { toString: () => id }, checkpoint: "checkpointCursor" in row ? { cursor: value.checkpointCursor, acceptedCount: value.acceptedCount, committedAttempts: value.committedAttempts, version: value.checkpointVersion } : undefined }; }
export function buildAttemptIdempotencyKey(input: BeginAttemptInput) { return crypto.createHash("sha256").update([input.campaignId, input.partitionId, input.cursorBefore ?? "", input.seed ?? "", input.requestFingerprint].join("\0")).digest("hex"); }

export const ingestCampaignService = {
  async createDraft(input: CreateCampaignInput): Promise<any> { return present(await getPrisma().openAlexIngestCampaign.create({ data: { ...input, manifest: input.manifest as never, state: "draft" } })); },
  async createPlanned(input: CreatePlannedCampaignInput): Promise<any> { if (!input.partitions.length) throw AppError.badRequest("A campaign requires at least one partition"); if (input.campaignKind === "backfill" && input.partitions.some((partition) => partition.selectionMethod === "cursor")) throw AppError.badRequest("Backfill partitions must use a planner-approved seeded sample; cursor scans are reserved for repair/refresh paths."); if (input.partitions.some((partition) => partition.selectionMethod === "seeded-sample" && partition.targetCount > OPENALEX_CAMPAIGN_SAMPLE_SIZE)) throw AppError.badRequest("Seeded sample partition exceeds provider limit"); try { const row = await getPrisma().$transaction(async (tx) => { const campaign = await tx.openAlexIngestCampaign.create({ data: { campaignKey: input.campaignKey, campaignKind: input.campaignKind, targetUniqueWorks: input.targetUniqueWorks, manifest: input.manifest as never, progress: { plannedPartitions: input.partitions.length } as never, state: "planned" } }); await tx.openAlexIngestPartition.createMany({ data: input.partitions.map((partition) => ({ ...partition, campaignId: campaign.id })) }); return campaign; }); return present(row); } catch (error) { if ((error as { code?: string }).code === "P2002") throw AppError.conflict("Campaign key already exists"); throw error; } },
  async start(value: string): Promise<any> { const row = await getPrisma().openAlexIngestCampaign.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Ingest campaign not found"); if (!["planned", "paused"].includes(row.state)) throw AppError.conflict("Campaign cannot be started from its current state"); return present(await getPrisma().openAlexIngestCampaign.update({ where: { id: row.id }, data: { state: "running", startedAt: row.startedAt ?? new Date(), failureReason: null } })); },
  async pause(value: string): Promise<any> { const row = await getPrisma().openAlexIngestCampaign.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Ingest campaign not found"); return present(await getPrisma().openAlexIngestCampaign.update({ where: { id: row.id }, data: { state: "paused" } })); },
  async resume(value: string) { return this.start(value); },
  async cancel(value: string): Promise<any> { const row = await getPrisma().openAlexIngestCampaign.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Ingest campaign not found"); return present(await getPrisma().openAlexIngestCampaign.update({ where: { id: row.id }, data: { state: "cancelled", completedAt: new Date() } })); },
  async claimNextPartition(input: ClaimInput): Promise<any | null> { const campaign = await getPrisma().openAlexIngestCampaign.findUnique({ where: whereId(input.campaignId) }); if (!campaign || campaign.state !== "running") return null; const now = input.now ?? new Date(), leaseExpiresAt = new Date(now.getTime() + input.leaseMs); const candidates = await getPrisma().openAlexIngestPartition.findMany({ where: { campaignId: campaign.id, state: { in: ["planned", "retry_wait", "running"] }, OR: [{ leaseExpiresAt: null }, { leaseExpiresAt: { lt: now } }] }, orderBy: { createdAt: "asc" } }); for (const candidate of candidates) { const claimed = await getPrisma().openAlexIngestPartition.updateMany({ where: { id: candidate.id, OR: [{ leaseExpiresAt: null }, { leaseExpiresAt: { lt: now } }] }, data: { state: "running", leaseOwnerId: input.workerId, leaseExpiresAt, leaseHeartbeatAt: now } }); if (claimed.count) return present(await getPrisma().openAlexIngestPartition.findUniqueOrThrow({ where: { id: candidate.id } })); } return null; },
  async beginAttempt(input: BeginAttemptInput): Promise<any> { const campaign = await getPrisma().openAlexIngestCampaign.findUnique({ where: whereId(input.campaignId) }); const partition = await getPrisma().openAlexIngestPartition.findUnique({ where: whereId(input.partitionId) }); if (!campaign || !partition) throw AppError.notFound("Campaign partition not found"); const key = buildAttemptIdempotencyKey(input); const row = await getPrisma().openAlexIngestPageAttempt.upsert({ where: { partitionId_idempotencyKey: { partitionId: partition.id, idempotencyKey: key } }, create: { campaignId: campaign.id, partitionId: partition.id, idempotencyKey: key, cursorBefore: input.cursorBefore, requestFingerprint: input.requestFingerprint }, update: {} }); return present(row); },
  async renewPartitionLease(input: { partitionId: string; workerId: string; leaseMs: number }) { const row = await getPrisma().openAlexIngestPartition.findUnique({ where: whereId(input.partitionId) }); if (!row || row.leaseOwnerId !== input.workerId) throw AppError.conflict("Partition lease is no longer owned by this worker"); await getPrisma().openAlexIngestPartition.update({ where: { id: row.id }, data: { leaseExpiresAt: new Date(Date.now() + input.leaseMs), leaseHeartbeatAt: new Date() } }); },
  async commitAttemptAndAdvanceCheckpoint(input: CommitAttemptInput) { const attempt = await getPrisma().openAlexIngestPageAttempt.findUnique({ where: whereId(input.attemptId) }); const partition = await getPrisma().openAlexIngestPartition.findUnique({ where: whereId(input.partitionId) }); if (!attempt || !partition) throw AppError.notFound("Campaign attempt not found"); const changed = await getPrisma().$transaction(async (tx) => { const advanced = await tx.openAlexIngestPartition.updateMany({ where: { id: partition.id, checkpointVersion: input.expectedCheckpointVersion }, data: { checkpointCursor: input.cursorAfter, acceptedCount: { increment: input.acceptedCount }, committedAttempts: { increment: 1 }, checkpointVersion: { increment: 1 } } }); await tx.openAlexIngestPageAttempt.update({ where: { id: attempt.id }, data: { cursorAfter: input.cursorAfter, responseHash: input.responseHash, state: "committed", expectedResultCount: input.expectedResultCount, acceptedCount: input.acceptedCount, rejectedCount: input.rejectedCount, conflictCount: input.conflictCount, committedAt: new Date() } }); return advanced.count > 0; }); return { checkpointAdvanced: changed }; },
  async markPartition(input: MarkPartitionInput) { const row = await getPrisma().openAlexIngestPartition.findUnique({ where: whereId(input.partitionId) }); if (!row) return; await getPrisma().openAlexIngestPartition.updateMany({ where: { id: row.id, leaseOwnerId: input.workerId }, data: { state: input.state, lastError: input.errorMessage, leaseOwnerId: null, leaseExpiresAt: null } }); },
  async completeIfFinished(value: string) { const campaign = await getPrisma().openAlexIngestCampaign.findUnique({ where: whereId(value) }); if (!campaign) return false; const remaining = await getPrisma().openAlexIngestPartition.count({ where: { campaignId: campaign.id, state: { notIn: ["completed", "dead_letter"] } } }); if (remaining) return false; await getPrisma().openAlexIngestCampaign.update({ where: { id: campaign.id }, data: { state: "completed", completedAt: new Date() } }); return true; },
  async reconcileCampaignProgressIfDue(value: string) { await this.reconcileCampaignProgress(value); return true; },
  async reconcileCampaignProgress(value: string) { const campaign = await getPrisma().openAlexIngestCampaign.findUnique({ where: whereId(value) }); if (!campaign) return; const rows = await getPrisma().openAlexIngestPartition.findMany({ where: { campaignId: campaign.id } }); const progress = { plannedPartitions: rows.length, completedPartitions: rows.filter((row) => row.state === "completed").length, acceptedCount: rows.reduce((sum, row) => sum + row.acceptedCount, 0), committedPages: rows.reduce((sum, row) => sum + row.committedAttempts, 0) }; await getPrisma().openAlexIngestCampaign.update({ where: { id: campaign.id }, data: { progress: progress as never } }); },
};
