import { aiModel } from "../user-ai/user-ai.runtime.js";
import type { AgreementBucket, AgreementStats, QualityEvaluation, QualityTargetKind, QualityView, RatingSummary } from "@trend/shared-types";
import { AppError } from "../../common/exceptions/app-error.js";
import { env } from "../../config/env.js";
import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import { syncUserPoints } from "../auth/points.service.js";
import { cachedGenerateJSON } from "../llm/llm.run.js";
import { LlmQuotaError } from "../llm/gemini.client.js";
import type { EvaluateInput, RateInput } from "./dto/quality.schema.js";
import { QUALITY_JUDGE_SYSTEM_PROMPT, QUALITY_PROMPT_VERSION, buildGapJudgePrompt, buildPaperJudgePrompt, buildReportJudgePrompt, type JudgeEvidence } from "./quality.prompt.js";

interface JudgeRaw { relevance: number; groundedness: number; completeness: number; rationale: string }
function whereId(value: string) { const parsed = parseDatabaseId(value); if (!parsed) throw AppError.badRequest("Invalid identifier"); return parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; }
async function user(value: string) { const row = await getPrisma().user.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("User not found"); return row; }
async function target(kind: QualityTargetKind, value: string) { const where = whereId(value); if (kind === "paper") return getPrisma().paper.findUnique({ where }); if (kind === "report") return getPrisma().report.findUnique({ where }); return getPrisma().researchGap.findUnique({ where }); }
function targetWhere(kind: QualityTargetKind, id: string) { return kind === "paper" ? { paperId: id } : kind === "report" ? { reportId: id } : { gapId: id }; }
function targetData(kind: QualityTargetKind, id: string) { return targetWhere(kind, id); }
function targetKindOf(row: { paperId: string | null; reportId: string | null; gapId: string | null }): QualityTargetKind { return row.paperId ? "paper" : row.reportId ? "report" : "gap"; }
function targetIdOf(row: { paperId: string | null; reportId: string | null; gapId: string | null }) { return row.paperId ?? row.reportId ?? row.gapId!; }
function clampScore(value: unknown) { const number = Math.round(Number(value)); return Number.isFinite(number) ? Math.max(1, Math.min(5, number)) : 3; }
function toEvaluationDto(row: { paperId: string | null; reportId: string | null; gapId: string | null; relevance: number; groundedness: number; completeness: number; overall: number; rationale: string; model: string; createdAt: Date }): QualityEvaluation { return { targetKind: targetKindOf(row), targetId: targetIdOf(row), relevance: row.relevance, groundedness: row.groundedness, completeness: row.completeness, overall: row.overall, rationale: row.rationale, model: row.model, createdAt: row.createdAt.toISOString() }; }
async function loadEvidence(ids: string[]): Promise<JudgeEvidence[]> { const rows = await getPrisma().paper.findMany({ where: { id: { in: ids } }, select: { title: true, abstractText: true } }); return rows.map((row) => ({ title: row.title, abstractText: row.abstractText ?? undefined })); }
async function assertCanAccess(userIdInput: string, kind: QualityTargetKind, id: string) { const [owner, row] = await Promise.all([user(userIdInput), target(kind, id)]); if (!row || (kind === "paper" && "dataStatus" in row && row.dataStatus !== "active") || (kind === "report" && "userId" in row && row.userId !== owner.id)) throw AppError.notFound(kind === "gap" ? "Research gap not found" : `${kind[0]!.toUpperCase()}${kind.slice(1)} not found`); return { owner, row }; }
async function buildPromptForTarget(userId: string, kind: QualityTargetKind, id: string) { const { row } = await assertCanAccess(userId, kind, id); if (kind === "paper") { const paper = row as Awaited<ReturnType<typeof getPrisma>>["paper"] extends never ? never : any; if (!paper.abstractText?.trim()) throw AppError.badRequest("Bài không đủ dữ liệu để AI chấm (thiếu abstract)."); return buildPaperJudgePrompt({ title: paper.title, abstractText: paper.abstractText }); } if (kind === "report") { const report = row as any; if (report.status !== "ready" || !report.markdown) throw AppError.badRequest("Report is not ready to evaluate yet"); const links = await getPrisma().reportPaper.findMany({ where: { reportId: report.id, kind: "grounding" } }); return buildReportJudgePrompt(report.query, report.markdown, await loadEvidence(links.map((link) => link.paperId))); } const gap = row as any; const links = await getPrisma().researchGapPaper.findMany({ where: { gapId: gap.id, kind: "supporting" } }); return buildGapJudgePrompt({ topic: gap.topic, title: gap.title, description: gap.description, rationale: gap.rationale }, await loadEvidence(links.map((link) => link.paperId))); }
async function summarize(kind: QualityTargetKind, id: string): Promise<RatingSummary> { const rows = await getPrisma().userRating.groupBy({ by: ["userId"], where: targetWhere(kind, id), _avg: { stars: true } }); if (!rows.length) return { avg: 0, count: 0 }; return { avg: Math.round((rows.reduce((sum, row) => sum + (row._avg.stars ?? 0), 0) / rows.length) * 10) / 10, count: rows.length }; }

export const qualityService = {
  async evaluate(userId: string, input: EvaluateInput) { const { targetKind, targetId, force } = input; const resolved = await target(targetKind, targetId); if (!resolved) throw AppError.notFound("Target not found"); const current = await getPrisma().qualityEvaluation.findFirst({ where: targetWhere(targetKind, resolved.id) }); if (current && !force) return toEvaluationDto(current); const prompt = await buildPromptForTarget(userId, targetKind, targetId); let raw: JudgeRaw; try { raw = await cachedGenerateJSON<JudgeRaw>({ task: "judge", promptVersion: QUALITY_PROMPT_VERSION, keyParts: { targetKind, targetId }, model: aiModel(), bypassCache: force, prompt, validate: (candidate) => { for (const field of ["relevance", "groundedness", "completeness"] as const) if (!Number.isFinite(Number(candidate[field])) || Number(candidate[field]) < 1 || Number(candidate[field]) > 5) throw new Error(`Invalid ${field}`); if (!candidate.rationale?.trim()) throw new Error("Empty rationale"); return candidate; }, options: { system: QUALITY_JUDGE_SYSTEM_PROMPT, temperature: 0.2, maxOutputTokens: 4096 } }); } catch (error) { if (error instanceof LlmQuotaError) throw error; throw AppError.serviceUnavailable("AI evaluation is temporarily unavailable. Please try again."); } const relevance = clampScore(raw.relevance), groundedness = clampScore(raw.groundedness), completeness = clampScore(raw.completeness), overall = Math.round(((relevance + groundedness + completeness) / 3) * 10) / 10; const saved = await getPrisma().$transaction(async (tx) => { if (current) return tx.qualityEvaluation.update({ where: { id: current.id }, data: { relevance, groundedness, completeness, overall, rationale: raw.rationale.slice(0, 2000), model: aiModel(), promptVersion: QUALITY_PROMPT_VERSION } }); return tx.qualityEvaluation.create({ data: { ...targetData(targetKind, resolved.id), relevance, groundedness, completeness, overall, rationale: raw.rationale.slice(0, 2000), model: aiModel(), promptVersion: QUALITY_PROMPT_VERSION } }); }); return toEvaluationDto(saved); },
  async rate(userIdInput: string, input: RateInput) { const { owner, row } = await assertCanAccess(userIdInput, input.targetKind, input.targetId); if (owner.role === "admin") throw AppError.forbidden("Administrators are not allowed to rate papers/reports/gaps"); if (input.targetKind === "paper" && "uploadedById" in row && (row.uploadedById === owner.id || row.requestedById === owner.id)) throw AppError.forbidden("You cannot review a paper that you uploaded or requested"); const existing = await getPrisma().userRating.findFirst({ where: { userId: owner.id, ...targetWhere(input.targetKind, row.id) } }); if (existing) await getPrisma().userRating.update({ where: { id: existing.id }, data: { stars: input.stars, comment: input.comment } }); else await getPrisma().userRating.create({ data: { userId: owner.id, ...targetData(input.targetKind, row.id), stars: input.stars, comment: input.comment } }); const ratingSummary = await summarize(input.targetKind, row.id); await syncUserPoints(owner.id); return { ratingSummary, myRating: { stars: input.stars, comment: input.comment } }; },
  async deleteRate(userIdInput: string, ratingId: string) { const owner = await user(userIdInput); const rating = await getPrisma().userRating.findUnique({ where: whereId(ratingId) }); if (!rating) throw AppError.notFound("Rating not found"); if (rating.userId !== owner.id) throw AppError.forbidden("You are only allowed to delete your own rating"); await getPrisma().userRating.delete({ where: { id: rating.id } }); const ratingSummary = await summarize(targetKindOf(rating), targetIdOf(rating)); await syncUserPoints(owner.id); return { ratingSummary }; },
  async view(userIdInput: string, kind: QualityTargetKind, id: string): Promise<QualityView> { const { owner, row } = await assertCanAccess(userIdInput, kind, id); const where = targetWhere(kind, row.id); const [evaluation, ratingSummary, mine, ratings] = await Promise.all([getPrisma().qualityEvaluation.findFirst({ where }), summarize(kind, row.id), getPrisma().userRating.findFirst({ where: { userId: owner.id, ...where } }), getPrisma().userRating.findMany({ where, orderBy: { updatedAt: "desc" } })]); const users = await getPrisma().user.findMany({ where: { id: { in: ratings.map((rating) => rating.userId) } }, select: { id: true, legacyMongoId: true, fullName: true, avatarUrl: true } }); const byId = new Map(users.map((item) => [item.id, item])); return { evaluation: evaluation ? toEvaluationDto(evaluation) : undefined, ratingSummary, myRating: mine ? { stars: mine.stars, comment: mine.comment ?? undefined } : undefined, allRatings: ratings.map((rating) => { const author = byId.get(rating.userId); return { id: publicDatabaseId(rating), user: author ? { id: publicDatabaseId(author), fullName: author.fullName, avatarUrl: author.avatarUrl ?? undefined } : null, stars: rating.stars, comment: rating.comment ?? undefined, updatedAt: rating.updatedAt.toISOString() }; }) }; },
  async agreement(): Promise<AgreementStats> { const evaluations = await getPrisma().qualityEvaluation.findMany(); if (!evaluations.length) return emptyAgreement(); const ratings = await getPrisma().userRating.findMany(); const grouped = new Map<string, number[]>(); for (const rating of ratings) { const key = `${targetKindOf(rating)}:${targetIdOf(rating)}`; grouped.set(key, [...(grouped.get(key) ?? []), rating.stars]); } const pairs = evaluations.flatMap((evaluation) => { const kind = targetKindOf(evaluation), values = grouped.get(`${kind}:${targetIdOf(evaluation)}`); return values?.length ? [{ kind, llm: evaluation.overall, user: values.reduce((a, b) => a + b, 0) / values.length }] : []; }); const all = bucketize(pairs); return { sampleSize: all.sampleSize, mae: all.mae, withinOnePct: all.withinOnePct, correlation: all.correlation, byKind: { report: bucketize(pairs.filter((pair) => pair.kind === "report")), gap: bucketize(pairs.filter((pair) => pair.kind === "gap")), paper: bucketize(pairs.filter((pair) => pair.kind === "paper")) } }; },
};
function bucketize(pairs: { llm: number; user: number }[]): AgreementBucket { const n = pairs.length; if (!n) return { sampleSize: 0, mae: 0, withinOnePct: 0, correlation: null }; const mae = pairs.reduce((sum, pair) => sum + Math.abs(pair.llm - pair.user), 0) / n; return { sampleSize: n, mae: Math.round(mae * 100) / 100, withinOnePct: Math.round((pairs.filter((pair) => Math.abs(pair.llm - pair.user) <= 1).length / n) * 100), correlation: n >= 3 ? pearson(pairs.map((pair) => pair.llm), pairs.map((pair) => pair.user)) : null }; }
function pearson(xs: number[], ys: number[]) { const n = xs.length, mx = xs.reduce((a, b) => a + b, 0) / n, my = ys.reduce((a, b) => a + b, 0) / n; let numerator = 0, dx = 0, dy = 0; for (let index = 0; index < n; index++) { const a = xs[index]! - mx, b = ys[index]! - my; numerator += a * b; dx += a * a; dy += b * b; } const denominator = Math.sqrt(dx * dy); return denominator ? Math.round((numerator / denominator) * 100) / 100 : null; }
function emptyAgreement(): AgreementStats { const zero: AgreementBucket = { sampleSize: 0, mae: 0, withinOnePct: 0, correlation: null }; return { sampleSize: 0, mae: 0, withinOnePct: 0, correlation: null, byKind: { report: zero, gap: zero, paper: zero } }; }
