import type { AddProjectMemberRequest, CreateProjectRequest, UpdateProjectRequest } from "@trend/shared-types";
import { AppError } from "../../common/exceptions/app-error.js";
import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import type { ProjectAiFeature } from "./project-scope.js";

function whereId(value: string): { id: string } | { legacyMongoId: string } { const parsed = parseDatabaseId(value); if (!parsed) throw AppError.badRequest("Invalid identifier"); return parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; }
async function uid(value: string) { const row = await getPrisma().user.findUnique({ where: whereId(value), select: { id: true } }); if (!row) throw AppError.notFound("User not found"); return row.id; }
async function pid(value: string) { const row = await getPrisma().paper.findUnique({ where: whereId(value), select: { id: true, dataStatus: true } }); if (!row || row.dataStatus !== "active") throw AppError.notFound("Paper not found"); return row.id; }
async function project(value: string) { const row = await getPrisma().project.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Project not found"); return row; }
const present = <T extends { id: string; legacyMongoId?: string | null }>(row: T) => ({ ...row, id: publicDatabaseId(row), _id: publicDatabaseId(row) });
async function access(row: Awaited<ReturnType<typeof project>>, actorId: string) { const actor = await uid(actorId); const membership = await getPrisma().projectMember.findUnique({ where: { projectId_userId: { projectId: row.id, userId: actor } } }); return { actor, allowed: row.ownerId === actor || membership?.status === "active", owner: row.ownerId === actor || membership?.role === "owner" }; }
async function hydrate(row: Awaited<ReturnType<typeof project>>) { const prisma = getPrisma(); const [members, papers] = await Promise.all([prisma.projectMember.findMany({ where: { projectId: row.id, status: "active" } }), prisma.projectPaper.findMany({ where: { projectId: row.id }, orderBy: { createdAt: "asc" } })]); const [users, paperRows] = await Promise.all([prisma.user.findMany({ where: { id: { in: members.map((m) => m.userId) } }, select: { id: true, legacyMongoId: true, fullName: true, email: true, avatarUrl: true } }), prisma.paper.findMany({ where: { id: { in: papers.map((p) => p.paperId) } }, select: { id: true, legacyMongoId: true, title: true, publicationYear: true, abstractText: true } })]); const userMap = new Map(users.map((u) => [u.id, u])), paperMap = new Map(paperRows.map((p) => [p.id, p])); return { ...present(row), members: members.map((m) => ({ targetKind: "User", targetId: userMap.get(m.userId) ? present(userMap.get(m.userId)!) : m.userId, role: m.role })), papers: papers.map((p) => ({ targetKind: "Paper", targetId: paperMap.get(p.paperId) ? present(paperMap.get(p.paperId)!) : p.paperId })) }; }

export class ProjectService {
  async createProject(data: CreateProjectRequest, ownerId: string) { const owner = await uid(ownerId); const row = await getPrisma().$transaction(async (tx) => { const created = await tx.project.create({ data: { title: data.title, description: data.description, ownerId: owner } }); await tx.projectMember.create({ data: { projectId: created.id, userId: owner, role: "owner", status: "active" } }); return created; }); return hydrate(row); }
  async getProjectsByUser(userId: string) { const actor = await uid(userId); const memberships = await getPrisma().projectMember.findMany({ where: { userId: actor, status: "active" }, select: { projectId: true } }); const rows = await getPrisma().project.findMany({ where: { OR: [{ ownerId: actor }, { id: { in: memberships.map((m) => m.projectId) } }] }, orderBy: { updatedAt: "desc" } }); return Promise.all(rows.map(hydrate)); }
  async getProjectById(projectId: string, userId: string, userRole?: string) { const row = await project(projectId); const rights = await access(row, userId); if (!rights.allowed && userRole !== "admin") throw AppError.forbidden("Access denied to this project"); return hydrate(row); }
  async getProjectPaperIdsForUser(projectId: string, userId: string, feature?: ProjectAiFeature) { const row = await project(projectId); const rights = await access(row, userId); if (!rights.allowed) throw AppError.forbidden("Access denied to this project"); const papers = await getPrisma().projectPaper.findMany({ where: { projectId: row.id }, orderBy: { createdAt: "asc" } }); if (feature && !papers.length) throw AppError.badRequest(`Add papers to the project before using ${feature}`); const publicRows = await getPrisma().paper.findMany({ where: { id: { in: papers.map((p) => p.paperId) } }, select: { id: true, legacyMongoId: true } }); const byId = new Map(publicRows.map((p) => [p.id, publicDatabaseId(p)])); return papers.map((p) => byId.get(p.paperId) ?? p.paperId); }
  async updateProject(projectId: string, data: UpdateProjectRequest, userId: string) { const row = await project(projectId); if (!(await access(row, userId)).owner) throw AppError.forbidden("Only owners can update the project details"); return hydrate(await getPrisma().project.update({ where: { id: row.id }, data: { ...(data.title !== undefined ? { title: data.title } : {}), ...(data.description !== undefined ? { description: data.description } : {}) } })); }
  async deleteProject(projectId: string, userId: string) { const row = await project(projectId); const actor = await uid(userId); if (row.ownerId !== actor) throw AppError.forbidden("Only the primary owner can delete the project"); await getPrisma().project.delete({ where: { id: row.id } }); }
  async addPaperToProject(projectId: string, paperId: string, userId: string) { const row = await project(projectId); const rights = await access(row, userId); if (!rights.allowed) throw AppError.forbidden("Only project members can modify papers"); const paper = await pid(paperId); if (await getPrisma().projectPaper.findUnique({ where: { projectId_paperId: { projectId: row.id, paperId: paper } } })) throw AppError.badRequest("Paper already exists in the project"); await getPrisma().projectPaper.create({ data: { projectId: row.id, paperId: paper, addedById: rights.actor } }); return hydrate(row); }
  async removePaperFromProject(projectId: string, paperId: string, userId: string) { const row = await project(projectId); const rights = await access(row, userId); if (!rights.allowed) throw AppError.forbidden("Only project members can modify papers"); const paper = await pid(paperId); await getPrisma().projectPaper.deleteMany({ where: { projectId: row.id, paperId: paper } }); return hydrate(row); }
  async addMemberToProject(projectId: string, memberData: AddProjectMemberRequest, userId: string) { const row = await project(projectId); if (!(await access(row, userId)).owner) throw AppError.forbidden("Only owners can modify project members"); if (memberData.targetKind !== "User") throw AppError.badRequest("Only user members are supported"); const member = await uid(memberData.targetId); if (await getPrisma().projectMember.findUnique({ where: { projectId_userId: { projectId: row.id, userId: member } } })) throw AppError.badRequest("Member already exists in the project"); await getPrisma().projectMember.create({ data: { projectId: row.id, userId: member, role: memberData.role, status: "active" } }); return hydrate(row); }
  async removeMemberFromProject(projectId: string, targetId: string, userId: string) { const row = await project(projectId); const [target, rights] = await Promise.all([uid(targetId), access(row, userId)]); if (row.ownerId === target) throw AppError.badRequest("Cannot remove the primary owner"); if (!rights.owner && target !== rights.actor) throw AppError.forbidden("Only owners can remove other members"); await getPrisma().projectMember.deleteMany({ where: { projectId: row.id, userId: target } }); return hydrate(row); }
}
export const projectService = new ProjectService();
