import type { UserRole } from "@trend/shared-types";
import { AppError } from "../../common/exceptions/app-error.js";
import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import { auditService } from "../audit/audit.service.js";

const manager = (role: UserRole) => role === "moderator" || role === "admin";
function whereId(value: string): { id: string } | { legacyMongoId: string } { const parsed = parseDatabaseId(value); if (!parsed) throw AppError.badRequest("Invalid identifier"); return parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; }
async function uid(value: string) { const row = await getPrisma().user.findUnique({ where: whereId(value), select: { id: true } }); if (!row) throw AppError.notFound("User not found"); return row.id; }
async function workspace(value: string) { const row = await getPrisma().draftWorkspace.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Draft workspace not found"); return row; }
async function project(value: string) { const row = await getPrisma().project.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Project not found"); return row; }
async function access(workspaceId: string, actorId: string, role: UserRole) { const [row, actor] = await Promise.all([workspace(workspaceId), uid(actorId)]); if (manager(role)) return { row, actor }; const direct = await getPrisma().draftWorkspaceMember.findUnique({ where: { workspaceId_userId: { workspaceId: row.id, userId: actor } } }); if (direct) return { row, actor }; const target = await project(row.projectId); const member = await getPrisma().projectMember.findUnique({ where: { projectId_userId: { projectId: target.id, userId: actor } } }); if (target.ownerId !== actor && member?.status !== "active") throw AppError.forbidden("Workspace membership is required"); return { row, actor }; }
const present = <T extends { id: string; legacyMongoId?: string | null }>(row: T) => ({ ...row, id: publicDatabaseId(row), _id: publicDatabaseId(row) });

export const workspaceService = {
  async create(input: { projectId: string; name: string; memberIds?: string[] }, actorId: string, actorRole: UserRole) {
    const [target, actor] = await Promise.all([project(input.projectId), uid(actorId)]); const membership = await getPrisma().projectMember.findUnique({ where: { projectId_userId: { projectId: target.id, userId: actor } } }); if (!manager(actorRole) && target.ownerId !== actor && membership?.status !== "active") throw AppError.forbidden("Project membership is required");
    if (await getPrisma().draftWorkspace.findUnique({ where: { projectId: target.id } })) throw AppError.conflict("This project already has a draft workspace");
    const members = [...new Set([actor, ...(await Promise.all((input.memberIds ?? []).map(uid)))])]; const row = await getPrisma().$transaction(async (tx) => { const created = await tx.draftWorkspace.create({ data: { projectId: target.id, name: input.name, createdById: actor } }); await tx.draftWorkspaceMember.createMany({ data: members.map((userId) => ({ workspaceId: created.id, userId })) }); return created; });
    await auditService.log("workspace.created", { userId: actorId, targetTableName: "draft_workspaces", targetRecordId: row.id, details: { projectId: target.id } }); return present(row);
  },
  async get(workspaceId: string, actorId: string, actorRole: UserRole) { const { row } = await access(workspaceId, actorId, actorRole); const [sections, comments, members] = await Promise.all([getPrisma().workspaceSection.findMany({ where: { workspaceId: row.id }, orderBy: [{ order: "asc" }, { createdAt: "asc" }] }), getPrisma().workspaceComment.findMany({ where: { workspaceId: row.id }, orderBy: { createdAt: "asc" } }), getPrisma().draftWorkspaceMember.findMany({ where: { workspaceId: row.id } })]); const users = await getPrisma().user.findMany({ where: { id: { in: comments.map((comment) => comment.authorId) } }, select: { id: true, legacyMongoId: true, fullName: true, avatarUrl: true } }); const byId = new Map(users.map((user) => [user.id, user])); return { workspace: { ...present(row), memberIds: members.map((member) => member.userId) }, sections: sections.map(present), comments: comments.map((comment) => ({ ...present(comment), authorId: byId.get(comment.authorId) ? present(byId.get(comment.authorId)!) : comment.authorId })) }; },
  async createSection(workspaceId: string, input: { title: string; content?: string; order?: number }, actorId: string, actorRole: UserRole) { const { row, actor } = await access(workspaceId, actorId, actorRole); const order = input.order ?? await getPrisma().workspaceSection.count({ where: { workspaceId: row.id } }); const section = await getPrisma().$transaction(async (tx) => { const created = await tx.workspaceSection.create({ data: { workspaceId: row.id, title: input.title, content: input.content ?? "", order, version: 1, createdById: actor, updatedById: actor } }); await tx.sectionRevision.create({ data: { workspaceId: row.id, sectionId: created.id, version: 1, title: created.title, content: created.content, order: created.order, changedById: actor, changeSummary: "Initial section" } }); return created; }); await auditService.log("workspace.section.created", { userId: actorId, targetTableName: "workspace_sections", targetRecordId: section.id, details: { workspaceId: row.id, version: 1 } }); return present(section); },
  async updateSection(workspaceId: string, sectionId: string, input: { expectedVersion: number; title?: string; content?: string; order?: number; changeSummary?: string }, actorId: string, actorRole: UserRole) { const { row, actor } = await access(workspaceId, actorId, actorRole); const parsed = whereId(sectionId); const current = await getPrisma().workspaceSection.findUnique({ where: parsed }); if (!current || current.workspaceId !== row.id) throw AppError.notFound("Workspace section not found"); const updated = await getPrisma().$transaction(async (tx) => { const claimed = await tx.workspaceSection.updateMany({ where: { id: current.id, workspaceId: row.id, version: input.expectedVersion }, data: { ...(input.title !== undefined ? { title: input.title } : {}), ...(input.content !== undefined ? { content: input.content } : {}), ...(input.order !== undefined ? { order: input.order } : {}), updatedById: actor, version: { increment: 1 } } }); if (!claimed.count) throw AppError.conflict("Section was changed by another editor; reload before saving"); const section = await tx.workspaceSection.findUniqueOrThrow({ where: { id: current.id } }); await tx.sectionRevision.create({ data: { workspaceId: row.id, sectionId: section.id, version: section.version, title: section.title, content: section.content, order: section.order, changedById: actor, changeSummary: input.changeSummary } }); return section; }); await auditService.log("workspace.section.updated", { userId: actorId, targetTableName: "workspace_sections", targetRecordId: updated.id, details: { workspaceId: row.id, previousVersion: input.expectedVersion, version: updated.version } }); return present(updated); },
  async listSectionRevisions(workspaceId: string, sectionId: string, actorId: string, actorRole: UserRole) { const { row } = await access(workspaceId, actorId, actorRole); const section = await getPrisma().workspaceSection.findUnique({ where: whereId(sectionId) }); if (!section || section.workspaceId !== row.id) throw AppError.notFound("Workspace section not found"); return (await getPrisma().sectionRevision.findMany({ where: { workspaceId: row.id, sectionId: section.id }, orderBy: { version: "desc" } })).map(present); },
  async addComment(workspaceId: string, sectionId: string, body: string, actorId: string, actorRole: UserRole) { const { row, actor } = await access(workspaceId, actorId, actorRole); const section = await getPrisma().workspaceSection.findUnique({ where: whereId(sectionId) }); if (!section || section.workspaceId !== row.id) throw AppError.notFound("Workspace section not found"); const comment = await getPrisma().workspaceComment.create({ data: { workspaceId: row.id, sectionId: section.id, authorId: actor, body, sectionVersion: section.version } }); await auditService.log("workspace.comment.created", { userId: actorId, targetTableName: "workspace_comments", targetRecordId: comment.id, details: { workspaceId: row.id, sectionId: section.id, sectionVersion: section.version } }); return present(comment); },
  async updateComment(workspaceId: string, commentId: string, status: "open" | "resolved", actorId: string, actorRole: UserRole) { const { row, actor } = await access(workspaceId, actorId, actorRole); const comment = await getPrisma().workspaceComment.findUnique({ where: whereId(commentId) }); if (!comment || comment.workspaceId !== row.id) throw AppError.notFound("Workspace comment not found"); const updated = await getPrisma().workspaceComment.update({ where: { id: comment.id }, data: { status, resolvedById: status === "resolved" ? actor : null, resolvedAt: status === "resolved" ? new Date() : null } }); await auditService.log("workspace.comment.status_updated", { userId: actorId, targetTableName: "workspace_comments", targetRecordId: comment.id, details: { workspaceId: row.id, status } }); return present(updated); },
};
