import { Link, useParams } from "react-router-dom";
import { Users } from "lucide-react";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button";
import { useCommunity, useForumPosts, useJoinCommunity } from "@/features/forum";
import { useAuthStore } from "@/stores/auth-store";

export function CommunityDetailPage() {
  const { slug = "" } = useParams(); const { data: community, isLoading } = useCommunity(slug); const join = useJoinCommunity(); const isAuthed = useAuthStore((state) => Boolean(state.tokens?.accessToken)); const { data: posts } = useForumPosts({ page: 1, pageSize: 20, communityId: community?.id });
  if (isLoading) return <p className="text-sm text-slate-500">Loading community…</p>; if (!community) return <p>Community not found.</p>;
  return <div className="mx-auto max-w-6xl space-y-6"><Link to="/communities" className="text-sm font-medium text-blue-600">← All communities</Link><header className="rounded-xl border bg-white p-6 dark:bg-zinc-950"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Badge variant="outline">{community.visibility}</Badge><span className="inline-flex items-center gap-1 text-xs text-slate-500"><Users className="h-3.5 w-3.5" />{community.memberCount} members</span></div><h1 className="mt-3 text-3xl font-bold">{community.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">{community.description}</p><div className="mt-4 flex flex-wrap gap-2">{community.researchTopics.map((topic) => <Badge key={topic} variant="secondary">{topic}</Badge>)}</div></div>{isAuthed && <Button disabled={join.isPending} onClick={() => join.mutate(community.id)}>{join.isPending ? "Joining…" : "Join community"}</Button>}</div></header><section><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-bold">Recent discussions</h2>{isAuthed && <Button size="sm" asChild><Link to="/forum/new">New post</Link></Button>}</div><div className="divide-y overflow-hidden rounded-xl border bg-white dark:divide-slate-800 dark:bg-zinc-950">{posts?.data.length ? posts.data.map((post) => <Link key={post.id} to={`/forum/${post.id}`} className="block p-5 hover:bg-slate-50 dark:hover:bg-zinc-900"><div className="flex items-center gap-2"><Badge>{post.type}</Badge><span className="text-xs text-slate-500">{post.commentCount} responses</span></div><h3 className="mt-2 font-semibold">{post.title}</h3><p className="mt-1 line-clamp-2 text-sm text-slate-500">{post.content}</p></Link>) : <p className="p-8 text-center text-sm text-slate-500">No discussions yet.</p>}</div></section></div>;
}
