// @vitest-environment jsdom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { MemoryRouter } from "react-router-dom";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import type { LecturerVerificationTracking, LecturerTrackingRequest } from "@trend/shared-types";
import { LecturerVerificationStatusPage } from "../components/lecturer-verification-status";
const mocks = vi.hoisted(() => ({ data: undefined as LecturerVerificationTracking | undefined, error: false, pending: false, refresh: vi.fn() }));
vi.mock("../hooks/use-academic-profile", () => ({ useLecturerVerificationTracking: () => ({ data: { lecturer: mocks.data }, isError: mocks.error, isPending: mocks.pending, refetch: mocks.refresh }), useAcademicProfile: () => ({ data: { academicRole: "LECTURER" } }), useInstitutionalEmailStatus: () => ({ data: { verified: true, email: "lecturer@institution.edu" } }) }));
vi.mock("../components/position-verification-panel", () => ({ PositionVerificationPanel: ({ supplement }: { supplement?: LecturerTrackingRequest }) => <div data-testid="supplement">{supplement?.id ?? "new request"}</div> }));
vi.mock("@/i18n", () => ({ useI18n: () => ({ t: (key: string) => key, language: "en" }) }));
const request = (): LecturerTrackingRequest => ({ id: "owned-request", revision: 1, status: "PENDING", institutionName: "Fixture University", position: "Lecturer", submittedAt: "2026-10-08T12:00:00Z", evidence: [] });
let container: HTMLDivElement, root: Root;
beforeEach(() => { mocks.error = false; mocks.pending = false; mocks.data = { status: "NOT_SUBMITTED", academicRole: "LECTURER", accountEmailVerified: true, institutionName: "Fixture University", position: "Lecturer", allowedActions: ["START"], selectedRequest: null, history: [], timeline: [], page: 1, totalPages: 1 }; container = document.createElement("div"); document.body.append(container); root = createRoot(container); (globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true; });
afterEach(async () => { await act(async () => root.unmount()); container.remove(); });
async function render(url = "/settings/verification/lecturer") { await act(async () => root.render(<MemoryRouter initialEntries={[url]}><LecturerVerificationStatusPage /></MemoryRouter>)); }
const button = (label: string) => [...container.querySelectorAll<HTMLButtonElement>("button")].find(item => item.textContent === label);
it("shows normal UNVERIFIED and the permitted existing form", async () => { await render(); expect(container.textContent).toContain("Lecturer position is not verified"); expect(container.textContent).not.toContain("Verification timeline"); await act(async () => button("Start verification")!.click()); expect(container.querySelector('[data-testid="supplement"]')!.textContent).toBe("new request"); });
it("shows authoritative PENDING after reload without allowing another request", async () => { mocks.data!.status = "PENDING"; mocks.data!.allowedActions = []; mocks.data!.selectedRequest = request(); mocks.data!.currentRequestId = "owned-request"; await render("/settings/verification/lecturer?requestId=owned-request&submitted=1"); expect(container.textContent).toContain("Awaiting Admin review"); expect(container.textContent).toContain("Verification request submitted"); expect(button("Start verification")).toBeUndefined(); expect(button("View request details")).toBeDefined(); });
it("shows requested changes and preserves original context in supplement mode", async () => { mocks.data!.status = "NEEDS_MORE_INFORMATION"; mocks.data!.allowedActions = ["SUPPLEMENT"]; mocks.data!.currentRequestId = "owned-request"; mocks.data!.selectedRequest = { ...request(), status: "NEEDS_MORE_INFORMATION", applicantMessage: "Provide a current appointment record", reviewedAt: "2026-10-08T13:00:00Z" }; await render(); expect(container.textContent).toContain("Provide a current appointment record"); await act(async () => button("Supplement evidence")!.click()); expect(container.querySelector('[data-testid="supplement"]')!.textContent).toBe("owned-request"); });
it("shows VERIFIED eligibility without promising project access or an assignment", async () => { mocks.data!.status = "VERIFIED"; mocks.data!.allowedActions = ["MENTORING_SETTINGS", "WORKSPACE"]; await render(); expect(container.textContent).toContain("Lecturer position verified"); expect(container.textContent).toContain("requires an accepted assignment"); expect(container.textContent).toContain("Verification does not grant project access"); expect(button("Configure mentoring availability")).toBeDefined(); expect(container.querySelector('a[href="/academic-support"]')).not.toBeNull(); });
it("preserves rejection feedback/history and honors server retry restrictions", async () => { mocks.data!.status = "REJECTED"; mocks.data!.allowedActions = []; const rejected = { ...request(), status: "REJECTED" as const, applicantMessage: "Cannot confirm current position" }; mocks.data!.selectedRequest = rejected; mocks.data!.history = [rejected]; await render(); expect(container.textContent).toContain("Cannot confirm current position"); expect(container.textContent).toContain("Verification history"); expect(button("Submit new verification")).toBeUndefined(); });
it("does not interpret loading failure or URL params as rejection or success", async () => { mocks.error = true; await render("/settings/verification/lecturer?requestId=other&submitted=1"); expect(container.querySelector('[role="alert"]')).not.toBeNull(); expect(container.textContent).not.toContain("Verification request submitted"); expect(container.textContent).not.toContain("Lecturer position could not be verified"); });
it("shows removed evidence and actual timeline without a view action", async () => { mocks.data!.selectedRequest = { ...request(), evidence: [{ id: "removed", type: "STAFF_ID", sourceKind: "DOCUMENT", displayName: "Staff card", isAvailable: false, replaced: true, submittedAt: "2026-10-08T12:00:00Z" }] }; mocks.data!.timeline = [{ id: "submitted", requestId: "owned-request", eventType: "SUBMITTED", createdAt: "2026-10-08T12:00:00Z" }]; await render(); expect(container.textContent).toContain("This document is no longer stored."); expect(container.textContent).toContain("Replaced in a later revision"); expect(button("View evidence")).toBeUndefined(); expect(container.querySelector("time")?.dateTime).toBe("2026-10-08T12:00:00Z"); });
