import { randomUUID } from "node:crypto";
import { AppError } from "../../common/exceptions/app-error.js";
import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import type { CreditAction } from "./credit-policy.js";

export type CreditTransactionDoc = Record<string, any> & { _id: any; id?: string; amount?: number; status?: string };
export interface ChargeParams { userId: string; action: CreditAction; amount: number; targetKind?: string; targetId?: string; idempotencyKey: string; metadata?: Record<string, unknown> }
export interface RefundParams { transactionId: string; reason?: string }
export interface RewardParams { userId: string; amount: number; targetId: string; idempotencyKey: string; action?: CreditAction; targetKind?: string; metadata?: Record<string, unknown> }
export interface OwnedChargeResult { transaction: CreditTransactionDoc | null; created: boolean }

async function user(value: string) { const parsed = parseDatabaseId(value); if (!parsed) return null; return getPrisma().user.findUnique({ where: parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value } }); }
async function target(kind: string | undefined, value: string) { const parsed = parseDatabaseId(value); if (!parsed || !kind) return null; const where = parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; if (kind === "paper") return getPrisma().paper.findUnique({ where, select: { id: true, legacyMongoId: true } }); if (kind === "report") return getPrisma().report.findUnique({ where, select: { id: true, legacyMongoId: true } }); if (kind === "gap") return getPrisma().researchGap.findUnique({ where, select: { id: true, legacyMongoId: true } }); if (kind === "project") return getPrisma().project.findUnique({ where, select: { id: true, legacyMongoId: true } }); if (kind === "payment_order") return getPrisma().paymentOrder.findUnique({ where, select: { id: true, legacyMongoId: true } }); return null; }
function dto(transaction: { id: string; legacyMongoId: string | null; targetLegacyMongoId: string | null; targetUuid: string | null; [key: string]: unknown }): CreditTransactionDoc { const publicId = publicDatabaseId(transaction); return { ...transaction, id: publicId, _id: { toString: () => publicId }, targetId: transaction.targetLegacyMongoId ?? transaction.targetUuid ?? undefined }; }

export const creditService = {
  async rewardCreditsOnce({ userId, amount, targetId, idempotencyKey, action = "paper_upload_reward", targetKind = "paper", metadata }: RewardParams): Promise<CreditTransactionDoc | null> { if (amount <= 0) return null; const prisma = getPrisma(); const owner = await user(userId); if (!owner) throw AppError.notFound("User not found"); const existing = await prisma.creditTransaction.findUnique({ where: { idempotencyKey } }); if (existing?.status === "applied") return dto(existing); const resolved = await target(targetKind, targetId); try { const transaction = await prisma.$transaction(async (tx) => { const updated = await tx.user.update({ where: { id: owner.id }, data: { credits: { increment: amount } } }); return tx.creditTransaction.create({ data: { id: randomUUID(), userId: owner.id, type: "reward", action, amount, balanceAfter: updated.credits, targetKind, targetLegacyMongoId: resolved?.legacyMongoId, targetUuid: resolved?.id, idempotencyKey, status: "applied", metadata: action === "paper_upload_reward" ? { ...metadata, uploaderName: updated.fullName } as never : metadata as never } }); }, { isolationLevel: "Serializable" }); return dto(transaction); } catch (error) { if ((error as { code?: string }).code === "P2002") { const concurrent = await prisma.creditTransaction.findUnique({ where: { idempotencyKey } }); if (concurrent) return dto(concurrent); } throw error; } },
  async chargeCreditsCheckedOwned({ userId, action, amount, targetKind, targetId, idempotencyKey, metadata }: ChargeParams): Promise<OwnedChargeResult> { if (amount <= 0) return { transaction: null, created: false }; const prisma = getPrisma(); const owner = await user(userId); if (!owner) throw AppError.notFound("User not found"); const existing = await prisma.creditTransaction.findUnique({ where: { idempotencyKey } }); if (existing?.status === "applied") return { transaction: dto(existing), created: false }; const resolved = targetId ? await target(targetKind, targetId) : null; try { const transaction = await prisma.$transaction(async (tx) => { const charged = await tx.user.updateMany({ where: { id: owner.id, credits: { gte: amount } }, data: { credits: { decrement: amount } } }); if (!charged.count) { const current = await tx.user.findUnique({ where: { id: owner.id }, select: { credits: true } }); throw AppError.badRequest(`Insufficient credits. Required: ${amount}, available: ${current?.credits ?? 0}`, { required: amount, available: current?.credits ?? 0, action }); } const current = await tx.user.findUniqueOrThrow({ where: { id: owner.id }, select: { credits: true } }); return tx.creditTransaction.create({ data: { id: randomUUID(), userId: owner.id, type: "charge", action, amount, balanceAfter: current.credits, targetKind, targetLegacyMongoId: resolved?.legacyMongoId, targetUuid: resolved?.id, idempotencyKey, status: "applied", metadata: metadata as never } }); }, { isolationLevel: "Serializable" }); return { transaction: dto(transaction), created: true }; } catch (error) { if ((error as { code?: string }).code === "P2002") { const concurrent = await prisma.creditTransaction.findUnique({ where: { idempotencyKey } }); if (concurrent) return { transaction: dto(concurrent), created: false }; } throw error; } },
  async chargeCreditsChecked(params: ChargeParams) { return (await this.chargeCreditsCheckedOwned(params)).transaction; },
  async refundCreditsOnce({ transactionId, reason }: RefundParams) { const parsed = parseDatabaseId(transactionId); if (!parsed) return; await getPrisma().$transaction(async (tx) => { const original = await tx.creditTransaction.findUnique({ where: parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value } }); if (!original || original.type !== "charge" || original.status !== "applied") return; const claimed = await tx.creditTransaction.updateMany({ where: { id: original.id, type: "charge", status: "applied" }, data: { status: "refunded" } }); if (!claimed.count) return; const owner = await tx.user.update({ where: { id: original.userId }, data: { credits: { increment: original.amount } }, select: { credits: true } }); await tx.creditTransaction.create({ data: { userId: original.userId, type: "refund", action: original.action, amount: original.amount, balanceAfter: owner.credits, targetKind: original.targetKind, targetLegacyMongoId: original.targetLegacyMongoId, targetUuid: original.targetUuid, idempotencyKey: `refund:${original.id}`, status: "applied", refundedTransactionId: original.id, metadata: reason ? { reason } : undefined } }); }, { isolationLevel: "Serializable" }); },
  async getBalance(userId: string) { const owner = await user(userId); if (!owner) throw AppError.notFound("User not found"); return owner.credits; },
  async getSummary(userId: string) {
    const owner = await user(userId);
    if (!owner) throw AppError.notFound("User not found");
    const prisma = getPrisma();
    const [spent, refunded, purchased, rewards, paidOrders, transactionCount] = await Promise.all([
      prisma.creditTransaction.aggregate({ where: { userId: owner.id, type: "charge" }, _sum: { amount: true } }),
      prisma.creditTransaction.aggregate({ where: { userId: owner.id, type: "refund" }, _sum: { amount: true } }),
      prisma.creditTransaction.aggregate({ where: { userId: owner.id, type: "reward", action: "credit_topup" }, _sum: { amount: true } }),
      prisma.creditTransaction.aggregate({ where: { userId: owner.id, type: "reward", action: { not: "credit_topup" } }, _sum: { amount: true } }),
      prisma.paymentOrder.aggregate({ where: { userId: owner.id, status: "paid" }, _sum: { amount: true, credits: true } }),
      prisma.creditTransaction.count({ where: { userId: owner.id } }),
    ]);
    return {
      balance: owner.credits,
      totalSpent: spent._sum.amount ?? 0,
      totalRefunded: refunded._sum.amount ?? 0,
      totalRewards: rewards._sum.amount ?? 0,
      totalPurchased: paidOrders._sum.credits ?? purchased._sum.amount ?? 0,
      totalTopupVnd: paidOrders._sum.amount ?? 0,
      transactionCount,
    };
  },
  async listTransactions({ userId, page = 1, pageSize = 20, type, action }: { userId: string; page?: number; pageSize?: number; type?: string; action?: string }) { const owner = await user(userId); if (!owner) throw AppError.notFound("User not found"); const where = { userId: owner.id, ...(type ? { type } : {}), ...(action ? { action } : {}) }; const [transactions, total] = await Promise.all([getPrisma().creditTransaction.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize }), getPrisma().creditTransaction.count({ where })]); return { data: transactions.map(dto), meta: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } }; },
};
