import { useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowDown, ArrowUp, CheckCircle2, Flag, MessageSquare } from "lucide-react";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button";
import { forumApi, useAcceptAnswer, useAddForumComment, useForumComments, useForumPost, useForumVote } from "@/features/forum";
import { useAuthStore } from "@/stores/auth-store";

export function ForumDetailPage() {
  const { id = "" } = useParams(); const { data: post, isLoading } = useForumPost(id); const { data: comments } = useForumComments(id); const add = useAddForumComment(); const vote = useForumVote(); const accept = useAcceptAnswer(); const [content, setContent] = useState(""); const [message, setMessage] = useState(""); const user = useAuthStore((state) => state.user); const isAuthed = useAuthStore((state) => Boolean(state.tokens?.accessToken));
  if (isLoading) return <p className="text-sm text-slate-500">Loading post…</p>; if (!post) return <p>Post not found.</p>;
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!content.trim()) return; await add.mutateAsync({ postId: post.id, content }); setContent(""); };
  const report = async (targetType: "post" | "comment", targetId: string) => { try { await forumApi.report(targetType, targetId, "other", "Reported from the forum interface"); setMessage("Report submitted for moderator review."); } catch { setMessage("This content could not be reported, or you already reported it."); } };
  return <div className="mx-auto max-w-5xl space-y-6"><Link to="/forum" className="text-sm font-medium text-blue-600">← Back to forum</Link><article className="rounded-xl border bg-white p-6 dark:bg-zinc-950"><div className="flex flex-wrap items-center gap-2"><Badge>{post.type}</Badge>{post.community && <Badge variant="outline">{post.community.name}</Badge>}{post.status === "locked" && <Badge variant="secondary">Locked</Badge>}</div><h1 className="mt-4 text-3xl font-bold tracking-tight">{post.title}</h1><div className="mt-3 text-sm text-slate-500">By {post.author.fullName}{post.author.institution && ` · ${post.author.institution}`}{post.author.academicProfileType === "lecturer" && " · Lecturer"}</div><p className="mt-6 whitespace-pre-wrap text-[15px] leading-7 text-slate-800 dark:text-slate-200">{post.content}</p><div className="mt-5 flex flex-wrap gap-2">{post.tags.map((tag) => <Badge key={tag} variant="secondary">{tag}</Badge>)}</div>{post.references.length > 0 && <div className="mt-6 border-t pt-4"><h2 className="text-sm font-semibold">References</h2><ul className="mt-2 space-y-1 text-sm text-slate-600">{post.references.map((reference, index) => <li key={`${reference.title}-${index}`}>{reference.url ? <a className="text-blue-600 underline" href={reference.url} rel="noreferrer" target="_blank">{reference.title || reference.url}</a> : reference.title || reference.doi}{reference.verified && <span className="ml-2 text-emerald-600">Internal paper</span>}</li>)}</ul></div>}<div className="mt-6 flex items-center gap-2 border-t pt-4"><Button size="sm" variant="outline" disabled={!isAuthed} onClick={() => vote.mutate({ kind: "post", id: post.id, value: 1 })}><ArrowUp className="h-4 w-4" /></Button><span className="min-w-8 text-center text-sm font-semibold">{post.voteScore}</span><Button size="sm" variant="outline" disabled={!isAuthed} onClick={() => vote.mutate({ kind: "post", id: post.id, value: -1 })}><ArrowDown className="h-4 w-4" /></Button>{isAuthed && <Button size="sm" variant="ghost" className="ml-auto" onClick={() => report("post", post.id)}><Flag className="mr-2 h-4 w-4" />Report</Button>}</div></article>
    <section className="space-y-4"><div className="flex items-center gap-2"><MessageSquare className="h-5 w-5" /><h2 className="text-xl font-bold">Responses</h2><span className="text-sm text-slate-500">{comments?.length ?? 0}</span></div>{comments?.map((comment) => { const accepted = post.acceptedCommentId === comment.id; return <article key={comment.id} className={`rounded-xl border bg-white p-5 dark:bg-zinc-950 ${accepted ? "border-emerald-400" : ""}`}><div className="flex flex-wrap justify-between gap-2"><div className="text-sm font-semibold">{comment.author.fullName}{comment.author.academicProfileType === "lecturer" && <span className="ml-2 text-xs text-blue-600">Lecturer</span>}</div>{accepted && <Badge className="bg-emerald-600"><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Accepted answer</Badge>}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{comment.content}</p><div className="mt-4 flex items-center gap-2"><Button size="sm" variant="ghost" disabled={!isAuthed} onClick={() => vote.mutate({ kind: "comment", id: comment.id, value: 1 })}><ArrowUp className="h-4 w-4" /> {comment.voteScore}</Button>{post.type === "question" && user?.id === post.author.id && !accepted && <Button size="sm" variant="outline" onClick={() => accept.mutate({ postId: post.id, commentId: comment.id })}>Accept answer</Button>}{isAuthed && <Button size="sm" variant="ghost" className="ml-auto" onClick={() => report("comment", comment.id)}><Flag className="h-4 w-4" /></Button>}</div></article>; })}{isAuthed && post.status !== "locked" ? <form onSubmit={submit} className="rounded-xl border bg-white p-5 dark:bg-zinc-950"><label className="text-sm font-semibold">Add a response</label><textarea className="mt-2 min-h-32 w-full rounded-md border bg-transparent px-3 py-2 text-sm" value={content} onChange={(e) => setContent(e.target.value)} /><div className="mt-3 flex justify-end"><Button disabled={add.isPending}>{add.isPending ? "Posting…" : "Post response"}</Button></div></form> : !isAuthed && <p className="rounded-lg border border-dashed p-4 text-sm text-slate-500">Sign in to comment, vote, or report content.</p>}{message && <p className="text-sm text-slate-600">{message}</p>}</section></div>;
}
