import { Link } from "react-router-dom";
import { MessageSquare, Plus, Users, ArrowUp } from "lucide-react";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useForumPosts, useCommunities } from "@/features/forum";
import { useAuthStore } from "@/stores/auth-store";

export function ForumListPage() {
  const [type, setType] = useState(""); const [communityId, setCommunityId] = useState(""); const [tag, setTag] = useState("");
  const { data, isLoading } = useForumPosts({ page: 1, pageSize: 30, type: type || undefined, communityId: communityId || undefined, tag: tag || undefined });
  const { data: communities } = useCommunities(); const isAuthed = useAuthStore((state) => Boolean(state.tokens?.accessToken));
  return <div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-slate-200 pb-5 dark:border-slate-800"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">Academic exchange</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Research Forum</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Questions and evidence-led discussions connected to papers, research gaps, and projects.</p></div><div className="flex gap-2"><Button variant="outline" asChild><Link to="/communities"><Users className="mr-2 h-4 w-4" />Communities</Link></Button>{isAuthed && <Button asChild><Link to="/forum/new"><Plus className="mr-2 h-4 w-4" />New post</Link></Button>}</div></header>
    <div className="grid gap-3 rounded-xl border bg-white p-4 dark:bg-zinc-950 md:grid-cols-3"><select aria-label="Post type" className="h-10 rounded-md border bg-transparent px-3 text-sm" value={type} onChange={(e) => setType(e.target.value)}><option value="">All post types</option><option value="question">Questions</option><option value="discussion">Discussions</option></select><select aria-label="Community" className="h-10 rounded-md border bg-transparent px-3 text-sm" value={communityId} onChange={(e) => setCommunityId(e.target.value)}><option value="">All communities</option>{communities?.map((community) => <option key={community.id} value={community.id}>{community.name}</option>)}</select><input className="h-10 rounded-md border bg-transparent px-3 text-sm" placeholder="Filter by exact tag" value={tag} onChange={(e) => setTag(e.target.value)} /></div>
    {isLoading ? <p className="text-sm text-slate-500">Loading discussions…</p> : data?.data.length ? <div className="divide-y overflow-hidden rounded-xl border bg-white dark:divide-slate-800 dark:bg-zinc-950">{data.data.map((post) => <Link key={post.id} to={`/forum/${post.id}`} className="grid gap-4 p-5 transition-colors hover:bg-slate-50 dark:hover:bg-zinc-900 sm:grid-cols-[56px_1fr]"><div className="flex h-12 flex-col items-center justify-center rounded-lg bg-slate-100 text-xs font-semibold dark:bg-zinc-900"><ArrowUp className="h-4 w-4" />{post.voteScore}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge variant={post.type === "question" ? "default" : "secondary"}>{post.type}</Badge>{post.community && <span className="text-xs font-medium text-blue-600">{post.community.name}</span>}</div><h2 className="mt-2 text-lg font-semibold text-slate-950 dark:text-white">{post.title}</h2><p className="mt-1 line-clamp-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{post.content}</p><div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span>{post.author.fullName}</span>{post.author.academicProfileType === "lecturer" && <span>· Lecturer</span>}<span className="inline-flex items-center gap-1"><MessageSquare className="h-3.5 w-3.5" />{post.commentCount}</span>{post.tags.map((item) => <Badge key={item} variant="outline">{item}</Badge>)}</div></div></Link>)}</div> : <div className="rounded-xl border border-dashed p-12 text-center"><MessageSquare className="mx-auto h-8 w-8 text-slate-400" /><p className="mt-3 font-medium">No discussions match these filters.</p></div>}
  </div>;
}
