import { useState, type FormEvent } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { useCommunities, useCreateForumPost } from "@/features/forum";

export function ForumNewPage() {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const create = useCreateForumPost(); const { data: communities } = useCommunities();
  const [type, setType] = useState<"discussion" | "question">("question"); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [communityId, setCommunityId] = useState(searchParams.get("community") ?? ""); const [tags, setTags] = useState(""); const [error, setError] = useState("");
  const joinedCommunities = communities?.filter((community) => community.viewerMembership?.status === "active") ?? [];
  const selectedCommunityId = joinedCommunities.some((community) => community.id === communityId) ? communityId : "";
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); try { const post = await create.mutateAsync({ type, title, content, communityId: selectedCommunityId || undefined, tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean) }); navigate(`/forum/${post.id}`); } catch (reason: any) { setError(reason?.response?.data?.error?.message ?? "Could not publish this post."); } };
  return <div className="mx-auto max-w-3xl"><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">Forum contribution</p><h1 className="mt-2 text-3xl font-bold">Start an academic discussion</h1><p className="mt-2 text-sm text-slate-500">State a focused question or claim and include enough research context for useful responses.</p></div><form onSubmit={submit} className="space-y-5 rounded-xl border bg-white p-6 dark:bg-zinc-950"><div className="grid gap-4 sm:grid-cols-2"><Field label="Post type"><select className="h-10 w-full rounded-md border bg-transparent px-3 text-sm" value={type} onChange={(e) => setType(e.target.value as typeof type)}><option value="question">Question</option><option value="discussion">Discussion</option></select></Field><Field label="Community"><select className="h-10 w-full rounded-md border bg-transparent px-3 text-sm" value={selectedCommunityId} onChange={(e) => setCommunityId(e.target.value)}><option value="">General forum</option>{joinedCommunities.map((community) => <option key={community.id} value={community.id}>{community.name}</option>)}</select></Field></div><Field label="Title"><Input required minLength={3} value={title} onChange={(e) => setTitle(e.target.value)} /></Field><Field label="Content"><textarea required className="min-h-56 w-full rounded-md border bg-transparent px-3 py-2 text-sm leading-6" value={content} onChange={(e) => setContent(e.target.value)} /></Field><Field label="Tags (comma separated)"><Input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="machine learning, methodology" /></Field>{error && <p className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => navigate(-1)}>Cancel</Button><Button type="submit" disabled={create.isPending}>{create.isPending ? "Publishing…" : "Publish post"}</Button></div></form></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
