import { useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { BadgeCheck, Bell, BellOff, BookOpen, Check, ChevronUp, EyeOff, Flag, Link2, Lock, MessageSquare, Pencil, Pin, Reply, Send, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { forumApi, useAcceptAnswer, useAddForumComment, useDeleteForumComment, useDeleteForumPost, useFollowThread, useForumComments, useForumContext, useForumPost, useForumVote, useModerateForumContent, useUnacceptAnswer, useUpdateForumComment, useUpdateForumPost, type ForumCommentView, type ForumReferenceView } from "@/features/forum";
import { useI18n } from "@/i18n";
import { useAuthStore } from "@/stores/auth-store";
import { cn } from "@/utils/cn";

export function ForumDetailPage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const { t } = useI18n(); const postQuery = useForumPost(id); const commentsQuery = useForumComments(id);
  const add = useAddForumComment(); const vote = useForumVote(); const accept = useAcceptAnswer(); const unaccept = useUnacceptAnswer(); const follow = useFollowThread();
  const moderate = useModerateForumContent();
  const updatePost = useUpdateForumPost(); const deletePost = useDeleteForumPost(); const updateComment = useUpdateForumComment(); const deleteComment = useDeleteForumComment();
  const currentUser = useAuthStore((state) => state.user); const isAuthed = useAuthStore((state) => Boolean(state.tokens?.accessToken));
  const [content, setContent] = useState(""); const [replyTo, setReplyTo] = useState<ForumCommentView>(); const [paperId, setPaperId] = useState(""); const [doi, setDoi] = useState(""); const [citationTitle, setCitationTitle] = useState("");
  const [reportTarget, setReportTarget] = useState<{ type: "post" | "comment"; id: string }>(); const [reportReason, setReportReason] = useState("OFF_TOPIC"); const [reportDescription, setReportDescription] = useState("");
  const [moderationTarget, setModerationTarget] = useState<{ type: "post" | "comment"; id: string; action: "THREAD_HIDDEN" | "RESPONSE_HIDDEN" }>(); const [moderationReason, setModerationReason] = useState("");
  const [postEditorOpen, setPostEditorOpen] = useState(false); const [editTitle, setEditTitle] = useState(""); const [editContent, setEditContent] = useState(""); const [editTags, setEditTags] = useState("");
  const [editComment, setEditComment] = useState<ForumCommentView>(); const [editCommentContent, setEditCommentContent] = useState(""); const [deleteTarget, setDeleteTarget] = useState<{ type: "post" | "comment"; id: string }>();
  const { data: context } = useForumContext(undefined, isAuthed);
  const post = postQuery.data; const comments = commentsQuery.data ?? [];
  const rootComments = useMemo(() => comments.filter((comment) => !comment.parentCommentId), [comments]);
  const replies = useMemo(() => { const map = new Map<string, ForumCommentView[]>(); for (const comment of comments) if (comment.parentCommentId) map.set(comment.parentCommentId, [...(map.get(comment.parentCommentId) ?? []), comment]); return map; }, [comments]);
  if (postQuery.isLoading) return <main className="mx-auto max-w-6xl px-4 py-10"><div className="h-96 animate-pulse rounded-xl bg-muted" /></main>;
  if (!post) return <main className="mx-auto max-w-3xl px-4 py-16"><h1 className="text-xl font-semibold">{t("Discussion unavailable")}</h1><p className="mt-2 text-sm text-muted-foreground">{t("This discussion may be private, hidden, or no longer available.")}</p></main>;
  const isOwner = currentUser?.id === post.author.id; const locked = post.status === "locked"; const removed = post.status === "deleted";

  async function submit(event: FormEvent) {
    event.preventDefault(); if (!post || !content.trim()) return;
    const references: ForumReferenceView[] = [];
    if (paperId) { const paper = context?.papers.find((item) => item.id === paperId); references.push({ paperId, title: paper?.title, year: paper?.publicationYear, doi: paper?.doi }); }
    if (doi.trim() && citationTitle.trim()) references.push({ doi: doi.trim(), title: citationTitle.trim() });
    try { await add.mutateAsync({ postId: post.id, content, parentCommentId: replyTo?.id, references }); setContent(""); setReplyTo(undefined); setPaperId(""); setDoi(""); setCitationTitle(""); toast.success(t("Response posted")); } catch { toast.error(t("Could not post this response.")); }
  }

  async function submitReport() {
    if (!reportTarget) return;
    try { await forumApi.report(reportTarget.type, reportTarget.id, reportReason, reportDescription || undefined); toast.success(t("Report submitted for moderator review.")); setReportTarget(undefined); setReportDescription(""); } catch { toast.error(t("This content could not be reported, or you already reported it.")); }
  }

  async function submitModeration() {
    if (!moderationTarget || moderationReason.trim().length < 3) return;
    try { await moderate.mutateAsync({ targetType: moderationTarget.type, targetId: moderationTarget.id, action: moderationTarget.action, reason: moderationReason.trim() }); toast.success(t("Content hidden from the forum")); setModerationTarget(undefined); setModerationReason(""); }
    catch { toast.error(t("Could not complete the moderation action.")); }
  }

  async function savePostEdit() {
    if (!post || editTitle.trim().length < 3 || !editContent.trim()) return;
    try { await updatePost.mutateAsync({ postId: post.id, input: { title: editTitle.trim(), content: editContent.trim(), tags: editTags.split(",").map((tag) => tag.trim()).filter(Boolean) } }); setPostEditorOpen(false); toast.success(t("Discussion updated")); }
    catch { toast.error(t("Could not update this discussion.")); }
  }

  async function saveCommentEdit() {
    if (!post || !editComment || !editCommentContent.trim()) return;
    try { await updateComment.mutateAsync({ postId: post.id, commentId: editComment.id, content: editCommentContent.trim() }); setEditComment(undefined); toast.success(t("Response updated")); }
    catch { toast.error(t("Could not update this response.")); }
  }

  async function confirmDelete() {
    if (!post || !deleteTarget) return;
    try {
      if (deleteTarget.type === "post") { await deletePost.mutateAsync(post.id); toast.success(t("Discussion removed")); navigate("/forum", { replace: true }); }
      else { await deleteComment.mutateAsync({ postId: post.id, commentId: deleteTarget.id }); toast.success(t("Response removed")); setDeleteTarget(undefined); }
    } catch { toast.error(t("Could not remove this content.")); }
  }

  return <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6"><Link to="/forum" className="text-sm font-medium text-blue-700">← {t("Back to Forum")}</Link>
    <div className="mt-5 grid gap-8 lg:grid-cols-[minmax(0,7fr)_minmax(280px,3fr)]"><div className="min-w-0">
      <article><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{t(post.type)}</Badge>{post.community ? <Link to={`/communities/${post.community.slug}`} className="text-xs font-medium text-muted-foreground hover:text-foreground">{post.community.name}</Link> : null}{locked ? <Badge variant="secondary"><Lock className="mr-1 h-3 w-3" />{t("Locked")}</Badge> : null}</div><h1 className="mt-4 text-2xl font-semibold tracking-tight sm:text-3xl">{post.title}</h1>
        <div className="mt-4 flex flex-wrap items-center gap-2 text-sm text-muted-foreground"><span className="font-medium text-foreground">{post.author.fullName}</span>{post.author.academicTitle ? <span>· {post.author.academicTitle}</span> : null}{post.author.institution ? <span>· {post.author.institution}</span> : null}{post.author.affiliationVerified ? <span className="inline-flex items-center gap-1 text-emerald-700"><BadgeCheck className="h-4 w-4" />{t("Affiliation verified")}</span> : null}<span>· {new Date(post.createdAt).toLocaleString()}</span>{post.editedAt ? <span>· {t("Edited")}</span> : null}</div>
        <p className="mt-6 whitespace-pre-wrap text-[15px] leading-7">{post.content}</p><div className="mt-5 flex flex-wrap gap-2">{post.tags.map((tag) => <Badge key={tag} variant="secondary" className="font-normal">{tag}</Badge>)}</div>
        <div className="mt-6 flex flex-wrap items-center gap-2 border-y py-3"><VoteButton active={post.viewerVote === 1} score={post.voteScore} disabled={!isAuthed} onClick={() => vote.mutate({ kind: "post", id: post.id, value: post.viewerVote === 1 ? 0 : 1 })} label={t("Helpful")} /><Button variant="ghost" size="sm" disabled={!isAuthed} onClick={() => follow.mutate({ postId: post.id, following: !post.isFollowing })}>{post.isFollowing ? <BellOff className="h-4 w-4" /> : <Bell className="h-4 w-4" />}{t(post.isFollowing ? "Following" : "Follow")}</Button>{isOwner && !locked && !removed ? <><Button variant="ghost" size="sm" onClick={() => { setEditTitle(post.title); setEditContent(post.content); setEditTags(post.tags.join(", ")); setPostEditorOpen(true); }}><Pencil className="h-4 w-4" />{t("Edit")}</Button><Button variant="ghost" size="sm" className="text-red-600" onClick={() => setDeleteTarget({ type: "post", id: post.id })}><Trash2 className="h-4 w-4" />{t("Remove")}</Button></> : null}{post.canModerate ? <><Button variant="ghost" size="sm" disabled={moderate.isPending} onClick={() => moderate.mutate({ targetType: "post", targetId: post.id, action: post.isPinned ? "THREAD_UNPINNED" : "THREAD_PINNED" })}><Pin className="h-4 w-4" />{t(post.isPinned ? "Unpin" : "Pin")}</Button><Button variant="ghost" size="sm" disabled={moderate.isPending} onClick={() => moderate.mutate({ targetType: "post", targetId: post.id, action: locked ? "THREAD_UNLOCKED" : "THREAD_LOCKED" })}><Lock className="h-4 w-4" />{t(locked ? "Unlock" : "Lock")}</Button><Button variant="ghost" size="sm" className="text-red-600" onClick={() => setModerationTarget({ type: "post", id: post.id, action: "THREAD_HIDDEN" })}><EyeOff className="h-4 w-4" />{t("Hide")}</Button></> : null}{isAuthed ? <Button variant="ghost" size="sm" className="ml-auto" onClick={() => setReportTarget({ type: "post", id: post.id })}><Flag className="h-4 w-4" />{t("Report")}</Button> : null}</div>
      </article>
      <section className="mt-8"><div className="flex items-end justify-between border-b pb-3"><div><h2 className="text-lg font-semibold">{t("Responses")} {comments.length}</h2><p className="mt-1 text-xs text-muted-foreground">{t("Most helpful responses appear first within each conversation.")}</p></div></div>
        {commentsQuery.isLoading ? <div className="mt-4 h-40 animate-pulse rounded-lg bg-muted" /> : rootComments.length ? <div className="divide-y">{rootComments.map((comment) => <div key={comment.id}><ResponseCard comment={comment} isQuestion={post.type === "QUESTION"} isPostOwner={isOwner} isCommentOwner={currentUser?.id === comment.author.id} isAuthed={isAuthed} onReply={setReplyTo} onEdit={(target) => { setEditComment(target); setEditCommentContent(target.content); }} onDelete={(targetId) => setDeleteTarget({ type: "comment", id: targetId })} onReport={(targetId) => setReportTarget({ type: "comment", id: targetId })} onVote={(value) => vote.mutate({ kind: "comment", id: comment.id, value })} onAccept={() => comment.isAccepted ? unaccept.mutate(post.id) : accept.mutate({ postId: post.id, commentId: comment.id })} t={t} />{(replies.get(comment.id) ?? []).sort((a,b) => b.voteScore - a.voteScore).map((reply) => <div key={reply.id} className="ml-6 border-l pl-4 sm:ml-12"><ResponseCard comment={reply} isQuestion={post.type === "QUESTION"} isPostOwner={isOwner} isCommentOwner={currentUser?.id === reply.author.id} isAuthed={isAuthed} onReply={setReplyTo} onEdit={(target) => { setEditComment(target); setEditCommentContent(target.content); }} onDelete={(targetId) => setDeleteTarget({ type: "comment", id: targetId })} onReport={(targetId) => setReportTarget({ type: "comment", id: targetId })} onVote={(value) => vote.mutate({ kind: "comment", id: reply.id, value })} onAccept={() => reply.isAccepted ? unaccept.mutate(post.id) : accept.mutate({ postId: post.id, commentId: reply.id })} t={t} /></div>)}</div>)}</div> : <div className="py-12 text-center"><MessageSquare className="mx-auto h-7 w-7 text-muted-foreground" /><h3 className="mt-3 font-medium">{t("No responses yet.")}</h3><p className="mt-1 text-sm text-muted-foreground">{t("Be the first to contribute to this discussion.")}</p></div>}
      </section>
      {locked ? <div className="mt-6 flex gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-200"><Lock className="h-5 w-5 shrink-0" />{t("This discussion has been locked by a moderator. Existing responses remain visible, but new responses are disabled.")}</div> : removed ? null : isAuthed ? <form onSubmit={submit} className="mt-6 rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">{replyTo ? t("Reply to response") : t("Add a response")}</h2>{replyTo ? <button type="button" className="text-xs text-muted-foreground" onClick={() => setReplyTo(undefined)}>{t("Cancel reply")}</button> : null}</div><textarea required minLength={1} maxLength={10000} rows={7} value={content} onChange={(event) => setContent(event.target.value)} className="mt-3 w-full resize-y rounded-md border bg-background px-3 py-2 text-sm leading-6 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder={t("Contribute a focused response. Cite evidence where it strengthens your argument.")} /><div className="mt-3 grid gap-2 sm:grid-cols-3"><select value={paperId} onChange={(event) => setPaperId(event.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">{t("Add Paper")}</option>{context?.papers.map((paper) => <option key={paper.id} value={paper.id}>{paper.title}</option>)}</select><Input value={doi} onChange={(event) => setDoi(event.target.value)} placeholder={t("DOI (optional)")} /><Input value={citationTitle} onChange={(event) => setCitationTitle(event.target.value)} placeholder={t("Citation title")} /></div><div className="mt-4 flex justify-end"><Button disabled={add.isPending}><Send className="h-4 w-4" />{add.isPending ? t("Posting…") : t("Post response")}</Button></div></form> : <p className="mt-6 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">{t("Sign in to respond, vote, follow, or report content.")}</p>}
    </div>
      <aside className="space-y-6 lg:sticky lg:top-20 lg:self-start"><section className="rounded-xl border bg-card p-5"><h2 className="text-sm font-semibold">{t("Linked Research Context")}</h2>{post.references.length || post.linkedPaper || post.linkedResearchGap || post.linkedProject ? <div className="mt-3 space-y-3">{post.references.map((reference, index) => <ContextLink key={`${reference.doi}-${index}`} icon={BookOpen} title={reference.title || reference.doi || t("Citation")} meta={[reference.year, reference.doi].filter(Boolean).join(" · ")} href={reference.paperId ? `/papers/${reference.paperId}` : reference.url} />)}{post.linkedPaper && !post.references.some((reference) => reference.paperId === post.linkedPaper?.id) ? <ContextLink icon={BookOpen} title={post.linkedPaper.title} meta={[post.linkedPaper.publicationYear, post.linkedPaper.doi].filter(Boolean).join(" · ")} href={`/papers/${post.linkedPaper.id}`} /> : null}{post.linkedResearchGap ? <ContextLink icon={Link2} title={post.linkedResearchGap.title} meta={post.linkedResearchGap.topic} href={`/research-gaps?gap=${post.linkedResearchGap.id}`} /> : null}{post.linkedProject ? <ContextLink icon={Link2} title={post.linkedProject.title} meta={t("Public project summary")} href={`/projects/${post.linkedProject.id}`} /> : null}</div> : <p className="mt-2 text-sm text-muted-foreground">{t("No research objects are linked to this discussion.")}</p>}</section>{post.community ? <section className="border-b pb-5"><h2 className="text-sm font-semibold">{post.community.name}</h2><Link to={`/communities/${post.community.slug}`} className="mt-2 inline-block text-sm font-medium text-blue-700">{t("View community")}</Link></section> : null}</aside>
    </div>
    <Dialog open={Boolean(reportTarget)} onOpenChange={(open) => { if (!open) setReportTarget(undefined); }}><DialogContent><DialogHeader><DialogTitle>{t("Report content")}</DialogTitle><DialogDescription>{t("Reports are for policy or community-rule issues, not ordinary academic disagreement.")}</DialogDescription></DialogHeader><label className="space-y-2 text-sm font-medium"><span>{t("Reason")}</span><select value={reportReason} onChange={(event) => setReportReason(event.target.value)} className="h-10 w-full rounded-md border bg-background px-3"><option value="SPAM">{t("Spam")}</option><option value="OFF_TOPIC">{t("Off topic")}</option><option value="HARASSMENT">{t("Harassment")}</option><option value="PLAGIARISM_OR_COPYRIGHT">{t("Plagiarism or copyright")}</option><option value="INAPPROPRIATE_CONTENT">{t("Inappropriate content")}</option><option value="OTHER">{t("Other")}</option></select></label><textarea value={reportDescription} onChange={(event) => setReportDescription(event.target.value)} maxLength={2000} rows={4} className="w-full rounded-md border bg-background px-3 py-2 text-sm" placeholder={t("Optional context for moderators")} /><DialogFooter><Button variant="ghost" onClick={() => setReportTarget(undefined)}>{t("Cancel")}</Button><Button onClick={submitReport}>{t("Submit report")}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(moderationTarget)} onOpenChange={(open) => { if (!open) setModerationTarget(undefined); }}><DialogContent><DialogHeader><DialogTitle>{t("Hide this forum content?")}</DialogTitle><DialogDescription>{t("The content will leave normal forum views and this decision will be recorded in moderation history.")}</DialogDescription></DialogHeader><label className="space-y-2 text-sm font-medium"><span>{t("Moderation reason")}</span><textarea value={moderationReason} onChange={(event) => setModerationReason(event.target.value)} maxLength={2000} rows={4} className="w-full rounded-md border bg-background px-3 py-2 text-sm" /></label><DialogFooter><Button variant="ghost" onClick={() => setModerationTarget(undefined)}>{t("Cancel")}</Button><Button variant="destructive" disabled={moderationReason.trim().length < 3 || moderate.isPending} onClick={submitModeration}>{t("Hide content")}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={postEditorOpen} onOpenChange={setPostEditorOpen}><DialogContent><DialogHeader><DialogTitle>{t("Edit discussion")}</DialogTitle><DialogDescription>{t("Your changes will be visible in this discussion.")}</DialogDescription></DialogHeader><label className="space-y-2 text-sm font-medium"><span>{t("Title")}</span><Input value={editTitle} onChange={(event) => setEditTitle(event.target.value)} minLength={3} maxLength={180} /></label><label className="space-y-2 text-sm font-medium"><span>{t("Body")}</span><textarea value={editContent} onChange={(event) => setEditContent(event.target.value)} minLength={1} maxLength={20000} rows={8} className="w-full resize-y rounded-md border bg-background px-3 py-2 text-sm leading-6" /></label><label className="space-y-2 text-sm font-medium"><span>{t("Tags")}</span><Input value={editTags} onChange={(event) => setEditTags(event.target.value)} placeholder={t("Separate tags with commas")} /></label><DialogFooter><Button variant="ghost" onClick={() => setPostEditorOpen(false)}>{t("Cancel")}</Button><Button disabled={editTitle.trim().length < 3 || !editContent.trim() || updatePost.isPending} onClick={savePostEdit}>{t("Save changes")}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(editComment)} onOpenChange={(open) => { if (!open) setEditComment(undefined); }}><DialogContent><DialogHeader><DialogTitle>{t("Edit response")}</DialogTitle><DialogDescription>{t("Your changes will be visible in this discussion.")}</DialogDescription></DialogHeader><label className="space-y-2 text-sm font-medium"><span>{t("Response")}</span><textarea value={editCommentContent} onChange={(event) => setEditCommentContent(event.target.value)} minLength={1} maxLength={10000} rows={7} className="w-full resize-y rounded-md border bg-background px-3 py-2 text-sm leading-6" /></label><DialogFooter><Button variant="ghost" onClick={() => setEditComment(undefined)}>{t("Cancel")}</Button><Button disabled={!editCommentContent.trim() || updateComment.isPending} onClick={saveCommentEdit}>{t("Save changes")}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(undefined); }}><DialogContent><DialogHeader><DialogTitle>{t(deleteTarget?.type === "post" ? "Remove this discussion?" : "Remove this response?")}</DialogTitle><DialogDescription>{t("This action cannot be undone.")}</DialogDescription></DialogHeader><DialogFooter><Button variant="ghost" onClick={() => setDeleteTarget(undefined)}>{t("Cancel")}</Button><Button variant="destructive" disabled={deletePost.isPending || deleteComment.isPending} onClick={confirmDelete}>{t("Remove")}</Button></DialogFooter></DialogContent></Dialog>
  </main>;
}

function ResponseCard({ comment, isQuestion, isPostOwner, isCommentOwner, isAuthed, onReply, onEdit, onDelete, onReport, onVote, onAccept, t }: { comment: ForumCommentView; isQuestion: boolean; isPostOwner: boolean; isCommentOwner: boolean; isAuthed: boolean; onReply: (comment: ForumCommentView) => void; onEdit: (comment: ForumCommentView) => void; onDelete: (id: string) => void; onReport: (id: string) => void; onVote: (value: -1 | 0 | 1) => void; onAccept: () => void; t: (key: string) => string }) {
  return <article className={cn("py-5", comment.isAccepted && "rounded-lg bg-emerald-50/60 px-4 dark:bg-emerald-950/15")}><div className="flex flex-wrap items-center gap-2 text-sm"><span className="font-medium">{comment.author.fullName}</span>{comment.author.academicTitle ? <span className="text-muted-foreground">· {comment.author.academicTitle}</span> : null}{comment.author.institution ? <span className="text-muted-foreground">· {comment.author.institution}</span> : null}{comment.author.affiliationVerified ? <BadgeCheck className="h-4 w-4 text-emerald-700" aria-label={t("Affiliation verified")} /> : null}{comment.isAccepted ? <Badge className="bg-emerald-700"><Check className="mr-1 h-3 w-3" />{t("Accepted by question author")}</Badge> : null}{comment.editedAt ? <span className="text-xs text-muted-foreground">· {t("Edited")}</span> : null}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{comment.content}</p>{comment.references.length ? <ul className="mt-3 space-y-1 text-xs text-muted-foreground">{comment.references.map((reference, index) => <li key={`${reference.doi}-${index}`}><BookOpen className="mr-1 inline h-3.5 w-3.5" />{reference.title || reference.doi}{reference.year ? ` (${reference.year})` : ""}</li>)}</ul> : null}<div className="mt-4 flex flex-wrap items-center gap-1"><VoteButton active={comment.viewerVote === 1} score={comment.voteScore} disabled={!isAuthed} onClick={() => onVote(comment.viewerVote === 1 ? 0 : 1)} label={t("Helpful")} />{isAuthed && comment.status === "active" ? <Button variant="ghost" size="sm" onClick={() => onReply(comment)}><Reply className="h-4 w-4" />{t("Reply")}</Button> : null}{isQuestion && isPostOwner && comment.status === "active" ? <Button variant="ghost" size="sm" onClick={onAccept}>{t(comment.isAccepted ? "Unaccept response" : "Accept response")}</Button> : null}{isCommentOwner && comment.status === "active" ? <><Button variant="ghost" size="sm" onClick={() => onEdit(comment)}><Pencil className="h-4 w-4" />{t("Edit")}</Button><Button variant="ghost" size="sm" className="text-red-600" onClick={() => onDelete(comment.id)}><Trash2 className="h-4 w-4" />{t("Remove")}</Button></> : null}{isAuthed ? <Button variant="ghost" size="sm" className="ml-auto" onClick={() => onReport(comment.id)}><Flag className="h-4 w-4" />{t("Report")}</Button> : null}</div></article>;
}
function VoteButton({ active, score, disabled, onClick, label }: { active: boolean; score: number; disabled: boolean; onClick: () => void; label: string }) { return <Button variant="ghost" size="sm" disabled={disabled} onClick={onClick} className={active ? "text-blue-700" : undefined}><ChevronUp className={cn("h-4 w-4", active && "fill-current")} />{score} {label}</Button>; }
function ContextLink({ icon: Icon, title, meta, href }: { icon: typeof BookOpen; title: string; meta?: string; href?: string }) { const content = <><Icon className="mt-0.5 h-4 w-4 shrink-0 text-blue-700" /><span className="min-w-0"><span className="block text-sm font-medium leading-5">{title}</span>{meta ? <span className="mt-0.5 block text-xs text-muted-foreground">{meta}</span> : null}</span></>; return href ? href.startsWith("http") ? <a href={href} target="_blank" rel="noreferrer" className="flex gap-2 rounded-md border p-3 hover:bg-muted/30">{content}</a> : <Link to={href} className="flex gap-2 rounded-md border p-3 hover:bg-muted/30">{content}</Link> : <div className="flex gap-2 rounded-md border p-3">{content}</div>; }
