import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import { notificationQueue } from "../../infrastructure/queue.js";
import type { RegisterDeviceTokenInput } from "./dto/device-token.schema.js";
import type { Prisma } from "../../generated/prisma/client.js";

async function user(value: string) { const parsed = parseDatabaseId(value); if (!parsed) return null; return getPrisma().user.findUnique({ where: parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }, select: { id: true, legacyMongoId: true } }); }
async function target(kind: string | undefined, value: string) { const parsed = parseDatabaseId(value); if (!parsed || !kind) return undefined; const where = parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; switch (kind) { case "paper": return getPrisma().paper.findUnique({ where, select: { id: true, legacyMongoId: true } }) ?? undefined; case "report": return getPrisma().report.findUnique({ where, select: { id: true, legacyMongoId: true } }) ?? undefined; case "gap": return getPrisma().researchGap.findUnique({ where, select: { id: true, legacyMongoId: true } }) ?? undefined; case "project": return getPrisma().project.findUnique({ where, select: { id: true, legacyMongoId: true } }) ?? undefined; case "forum_post": return getPrisma().forumPost.findUnique({ where, select: { id: true, legacyMongoId: true } }) ?? undefined; case "community": return getPrisma().community.findUnique({ where, select: { id: true, legacyMongoId: true } }) ?? undefined; case "academic_profile": return getPrisma().academicProfile.findUnique({ where, select: { id: true, legacyMongoId: true } }) ?? undefined; default: return undefined; } }

export const notificationService = {
  async create(input: { userId?: string | { toString(): string }; role?: string; title: string; message: string; type: string; paperId?: string | { toString(): string }; targetKind?: "paper" | "report" | "gap" | "project" | "forum_post" | "academic_profile" | "community"; targetId?: string | { toString(): string } }, transaction?: Prisma.TransactionClient) {
    const kind = input.targetKind ?? (input.paperId ? "paper" : undefined); const targetValue = input.targetId ?? input.paperId; const recipient = input.userId ? await user(String(input.userId)) : null; if (input.userId && !recipient) throw new Error("Notification user does not exist"); const resolved = targetValue ? await target(kind, String(targetValue)) : undefined; const paper = input.paperId ? await target("paper", String(input.paperId)) : undefined;
    const row = await (transaction ?? getPrisma()).notification.create({ data: { userId: recipient?.id, role: input.role, title: input.title, message: input.message, type: input.type, paperId: paper?.id, targetKind: kind, targetLegacyMongoId: resolved?.legacyMongoId, targetUuid: resolved?.id } });
    if (!transaction && row.userId) await notificationService.dispatch(row); return row;
  },
  async dispatch(row: { id: string; legacyMongoId: string | null; userId: string | null }) {
    if (row.userId) await notificationQueue.add("send-push", { notificationId: publicDatabaseId(row) }, { jobId: publicDatabaseId(row) });
  },
  async registerDeviceToken(userId: string, input: RegisterDeviceTokenInput) { const owner = await user(userId); if (!owner) throw new Error("Device-token user does not exist"); return getPrisma().deviceToken.upsert({ where: { token: input.token }, create: { userId: owner.id, token: input.token, platform: input.platform, deviceName: input.deviceName, lastSeenAt: new Date() }, update: { userId: owner.id, platform: input.platform, deviceName: input.deviceName, lastSeenAt: new Date(), disabledAt: null } }); },
  async list(userId: string, role: string) { const owner = await user(userId); if (!owner) return []; const prisma = getPrisma(); const rows = await prisma.notification.findMany({ where: role === "admin" ? { OR: [{ userId: owner.id }, { role: "admin" }] } : { userId: owner.id }, orderBy: { createdAt: "desc" } }); const readIds = role === "admin" ? new Set((await prisma.notificationRead.findMany({ where: { userId: owner.id, notificationId: { in: rows.map((row) => row.id) } }, select: { notificationId: true } })).map((entry) => entry.notificationId)) : new Set<string>(); return rows.map((row) => ({ id: publicDatabaseId(row), title: row.title, message: row.message, type: row.type, paperId: row.paperId, targetKind: row.targetKind ?? (row.paperId ? "paper" : null), targetId: row.targetLegacyMongoId ?? row.targetUuid ?? row.paperId, isRead: row.role === "admin" ? readIds.has(row.id) : row.isRead, createdAt: row.createdAt })); },
  async markAsRead(id: string, userId: string) { const parsed = parseDatabaseId(id); const owner = await user(userId); if (!parsed || !owner) return null; const row = await getPrisma().notification.findUnique({ where: parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value } }); if (!row) return null; if (row.role === "admin") { await getPrisma().notificationRead.upsert({ where: { notificationId_userId: { notificationId: row.id, userId: owner.id } }, create: { notificationId: row.id, userId: owner.id }, update: { readAt: new Date() } }); return row; } if (row.userId !== owner.id) return null; return getPrisma().notification.update({ where: { id: row.id }, data: { isRead: true } }); },
  async markAllAsRead(userId: string, role: string) { const owner = await user(userId); if (!owner) return; const prisma = getPrisma(); await prisma.notification.updateMany({ where: { userId: owner.id, isRead: false }, data: { isRead: true } }); if (role === "admin") { const rows = await prisma.notification.findMany({ where: { role: "admin" }, select: { id: true } }); await prisma.notificationRead.createMany({ data: rows.map((row) => ({ notificationId: row.id, userId: owner.id })), skipDuplicates: true }); } },
};
