import { AppError } from "../../common/exceptions/app-error.js";
import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import { auditService } from "../audit/audit.service.js";
import { capabilityService } from "../authorization/capability.service.js";

type GapCandidateInput = { topic: string; projectId?: string; corpusId?: string; title: string; gapType: string; scope?: string; establishedKnowledge: string; observedLimitation: string; missingEvidence: string; significanceExplanation: string; suggestedResearchQuestion?: string; gapConfidence: "LOW" | "MODERATE" | "HIGH"; researchPriority: "LOW" | "MODERATE" | "HIGH" };
function whereId(value: string) { const parsed = parseDatabaseId(value); if (!parsed) throw AppError.badRequest("Invalid identifier"); return parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; }
function present<T extends { id: string; legacyMongoId?: string | null }>(row: T) { return { ...row, id: publicDatabaseId(row), _id: publicDatabaseId(row) }; }
async function user(value: string) { const row = await getPrisma().user.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("User not found"); return row; }
async function gap(value: string) { const row = await getPrisma().researchGap.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Research gap candidate not found"); return row; }
async function project(value: string) { const row = await getPrisma().project.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Project not found"); return row; }
async function corpus(value: string) { const row = await getPrisma().literatureCorpus.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Literature corpus not found"); return row; }
async function paper(value: string) { const row = await getPrisma().paper.findUnique({ where: whereId(value) }); if (!row) throw AppError.badRequest("Evidence paper does not exist in the LumiGap corpus"); return row; }
async function accessProject(projectId: string, userId: string) { const row = await getPrisma().project.findUnique({ where: { id: projectId } }); if (!row || row.status === "ARCHIVED") return false; if (row.ownerId === userId) return true; const member = await getPrisma().projectMember.findUnique({ where: { projectId_userId: { projectId, userId } } }); return member?.status === "ACTIVE"; }
async function ownedGap(gapId: string, userIdInput: string) { const [row, owner] = await Promise.all([gap(gapId), user(userIdInput)]); if (row.userId !== owner.id) throw AppError.notFound("Research gap candidate not found"); return { row, owner }; }
async function assertExpert(userIdInput: string) { const owner = await user(userIdInput); const [profile, capabilities] = await Promise.all([getPrisma().academicProfile.findUnique({ where: { userId: owner.id } }), capabilityService.list(owner.id)]); if (owner.accountStatus !== "ACTIVE" || !capabilities.includes("GAP_VALIDATION")) throw AppError.forbidden("Verified academic identity and GAP_VALIDATION capability are required"); return { owner, profile }; }

export const gapValidationService = {
  async createCandidate(userIdInput: string, input: GapCandidateInput) {
    const owner = await user(userIdInput); let projectId: string | undefined; let corpusId: string | undefined;
    if (input.projectId) { const row = await project(input.projectId); if (!await accessProject(row.id, owner.id)) throw AppError.forbidden("Project membership is required"); projectId = row.id; }
    if (input.corpusId) { const row = await corpus(input.corpusId); if (row.ownerId !== owner.id && (!row.projectId || !await accessProject(row.projectId, owner.id))) throw AppError.forbidden("Access denied to this literature corpus"); if (projectId && row.projectId !== projectId) throw AppError.badRequest("The literature corpus does not belong to the selected project"); corpusId = row.id; }
    const numericConfidence = { LOW: 0.3, MODERATE: 0.6, HIGH: 0.85 }[input.gapConfidence];
    const created = await getPrisma().$transaction(async (tx) => {
      const row = await tx.researchGap.create({ data: { topic: input.topic, normalizedTopic: input.topic.trim().toLocaleLowerCase(), title: input.title, description: input.observedLimitation, rationale: input.significanceExplanation, userId: owner.id, projectId, corpusId, source: "standalone", origin: "HUMAN", gapType: input.gapType, scope: input.scope, establishedKnowledge: input.establishedKnowledge, observedLimitation: input.observedLimitation, missingEvidence: input.missingEvidence, significanceExplanation: input.significanceExplanation, suggestedResearchQuestion: input.suggestedResearchQuestion, validationStatus: "CANDIDATE", gapConfidence: input.gapConfidence, researchPriority: input.researchPriority, confidence: numericConfidence } });
      if (projectId) await tx.projectActivity.create({ data: { projectId, actorId: owner.id, type: "GAP_CREATED", entityKind: "GAP", entityId: publicDatabaseId(row), metadata: { title: row.title, status: "CANDIDATE" } } });
      return row;
    });
    await auditService.log("research_gap.candidate.created", { userId: userIdInput, targetTableName: "research_gaps", targetRecordId: created.id, details: { gapType: input.gapType, origin: "HUMAN" } }); return present(created);
  },
  async requestValidation(gapId: string, userIdInput: string) { const { row, owner } = await ownedGap(gapId, userIdInput); const changed = await getPrisma().researchGap.updateMany({ where: { id: row.id, userId: owner.id, validationStatus: { in: ["DRAFT", "CANDIDATE", "REFINED"] } }, data: { validationStatus: "UNDER_VALIDATION" } }); if (!changed.count) throw AppError.conflict("This gap cannot be submitted for validation"); const updated = await gap(row.id); await auditService.log("research_gap.validation.requested", { userId: userIdInput, targetTableName: "research_gaps", targetRecordId: row.id }); return present(updated); },
  async addEvidence(gapId: string, userIdInput: string, input: { paperId: string; evidenceKind: "SUPPORTING" | "COUNTER"; evidenceType?: string; excerpt?: string; explanation: string }) { const [{ row, owner }, sourcePaper] = await Promise.all([ownedGap(gapId, userIdInput), paper(input.paperId)]); try { const evidence = await getPrisma().$transaction(async (tx) => { const created = await tx.gapEvidenceRecord.create({ data: { gapId: row.id, paperId: sourcePaper.id, addedById: owner.id, evidenceKind: input.evidenceKind, evidenceType: input.evidenceType, excerpt: input.excerpt, explanation: input.explanation } }); await tx.researchGapPaper.upsert({ where: { gapId_paperId_kind: { gapId: row.id, paperId: sourcePaper.id, kind: input.evidenceKind === "SUPPORTING" ? "supporting" : "evidence" } }, create: { gapId: row.id, paperId: sourcePaper.id, kind: input.evidenceKind === "SUPPORTING" ? "supporting" : "evidence", position: 0 }, update: {} }); if (row.projectId) await tx.projectActivity.create({ data: { projectId: row.projectId, actorId: owner.id, type: "EVIDENCE_ADDED", entityKind: "GAP", entityId: publicDatabaseId(row), metadata: { title: row.title, evidenceKind: input.evidenceKind, paperId: publicDatabaseId(sourcePaper) } } }); return created; }); await auditService.log("research_gap.evidence.added", { userId: userIdInput, targetTableName: "gap_evidence_records", targetRecordId: evidence.id, details: { gapId, evidenceKind: input.evidenceKind, paperId: input.paperId } }); return present(evidence); } catch (error) { if ((error as { code?: string }).code === "P2002") throw AppError.conflict("This paper is already linked with the same evidence kind"); throw error; } },
  async getEvidence(gapId: string, userIdInput: string) { const [row, viewer] = await Promise.all([gap(gapId), user(userIdInput)]); if (row.userId !== viewer.id && !["UNDER_VALIDATION", "REFINED", "VALIDATED"].includes(row.validationStatus)) throw AppError.notFound("Research gap candidate not found"); const records = await getPrisma().gapEvidenceRecord.findMany({ where: { gapId: row.id }, orderBy: [{ evidenceKind: "asc" }, { createdAt: "asc" }] }); const papers = await getPrisma().paper.findMany({ where: { id: { in: records.map((item) => item.paperId) } }, select: { id: true, legacyMongoId: true, title: true, publicationYear: true, journalName: true, doi: true } }); const byId = new Map(papers.map((item) => [item.id, present(item)])); return records.map((item) => ({ ...present(item), paperId: byId.get(item.paperId) })); },
  async addValidation(gapId: string, reviewerIdInput: string, input: { action: "VALIDATE" | "CHALLENGE" | "REQUEST_EVIDENCE" | "SUGGEST_EVIDENCE" | "REFINE_SCOPE" | "REJECT"; comment: string; suggestedChanges?: string }) { const [{ owner: reviewer }, row] = await Promise.all([assertExpert(reviewerIdInput), gap(gapId)]); if (row.userId === reviewer.id) throw AppError.conflict("Owners cannot expert-validate their own research gap"); if (!["UNDER_VALIDATION", "REFINED"].includes(row.validationStatus)) throw AppError.conflict("This gap is not open for expert validation"); const status = input.action === "VALIDATE" ? "VALIDATED" : input.action === "REJECT" ? "REJECTED" : input.action === "REFINE_SCOPE" ? "REFINED" : "UNDER_VALIDATION"; const validation = await getPrisma().$transaction(async (tx) => { const created = await tx.gapValidation.create({ data: { gapId: row.id, reviewerId: reviewer.id, action: input.action, comment: input.comment, suggestedChanges: input.suggestedChanges } }); await tx.researchGap.update({ where: { id: row.id }, data: { validationStatus: status } }); if (row.projectId) await tx.projectActivity.create({ data: { projectId: row.projectId, actorId: reviewer.id, type: "GAP_STATUS_CHANGED", entityKind: "GAP", entityId: publicDatabaseId(row), metadata: { title: row.title, from: row.validationStatus, to: status } } }); return created; }); await auditService.log("research_gap.validation.recorded", { userId: reviewerIdInput, targetTableName: "gap_validations", targetRecordId: validation.id, details: { gapId, action: input.action } }); return present(validation); },
  async getValidations(gapId: string, userIdInput: string) { const [row, viewer] = await Promise.all([gap(gapId), user(userIdInput)]); if (row.userId !== viewer.id && !["UNDER_VALIDATION", "REFINED", "VALIDATED", "REJECTED"].includes(row.validationStatus)) throw AppError.notFound("Research gap candidate not found"); const validations = await getPrisma().gapValidation.findMany({ where: { gapId: row.id }, orderBy: { createdAt: "asc" } }); const reviewers = await getPrisma().user.findMany({ where: { id: { in: validations.map((item) => item.reviewerId) } }, select: { id: true, legacyMongoId: true, fullName: true, avatarUrl: true, institution: true, academicProfileType: true } }); const byId = new Map(reviewers.map((item) => [item.id, present(item)])); return validations.map((item) => ({ ...present(item), reviewerId: byId.get(item.reviewerId) })); },
};
