import crypto from "node:crypto";
import type { GapDirections, GapEvidenceMode, GapProbe, PreviewGapEvidenceResponse } from "@trend/shared-types";
import { AppError } from "../../common/exceptions/app-error.js";
import { env } from "../../config/env.js";
import { gapsQueue } from "../../infrastructure/queue.js";
import { logger } from "../../infrastructure/logger.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { creditService } from "../credits/credit.service.js";
import { getEmbeddingProvider } from "../embeddings/embedding.factory.js";
import { LlmContentError } from "../llm/gemini.client.js";
import { cachedGenerateJSON } from "../llm/llm.run.js";
import { retrieve } from "../retrieval/retriever.js";
import { computeGapEvidence } from "./gap-evidence.js";
import { fillMissingYears, truncateToCompleteYears, yoyGrowthPct } from "../trends/trend.formulas.js";
import { buildDirectionsPrompt, buildDirectionsEvidenceHash, sanitizeDirections, DIRECTIONS_PROMPT_VERSION, DIRECTIONS_SYSTEM_PROMPT, type DirectionsRaw } from "./gaps-directions.js";
import { buildGapsCacheKey, buildGapsPrompt, GAP_PROMPT_VERSION, GAPS_SYSTEM_PROMPT, type GapEvidencePaper, type GapsLlmOutput } from "./gaps.prompt.js";
import type { AnalyzeGapDto, ListGapsQuery, PatchGapDto, PreviewGapEvidenceDto } from "./dto/gaps.schema.js";
import { toGapListItem, type GapListDoc } from "./gap-presenter.js";
import { projectService } from "../projects/project.service.js";

export interface GapJob { analysisId: string }
type GapEvidenceCandidate = GapEvidencePaper & { journalName?: string; citationCount?: number; authorNames: string[]; score: number; source: "selected" | "retrieved" };
interface CollectGapEvidenceInput { topic: string; queryVector?: number[]; selectedPaperIds?: string[]; evidenceMode: GapEvidenceMode; yearFrom?: number; yearTo?: number; projectPaperIds?: string[] }
interface CollectGapEvidenceResult { papers: GapEvidenceCandidate[]; selectedPaperIds: string[]; retrievedPaperIds: string[]; missingSelectedPaperIds: string[] }

const normalizeTopicStr = (value: string) => value.trim().toLowerCase();
const clamp01 = (value: unknown) => { const number = Number(value); return Number.isFinite(number) ? Math.max(0, Math.min(1, number)) : 0.5; };
const GAP_WINDOW_YEARS = 5;
function idWhere(value: string): { id?: string; legacyMongoId?: string } { const parsed = parseDatabaseId(value); if (!parsed) throw AppError.badRequest("Invalid database identifier"); return parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; }

async function resolveUser(value: string) { const user = await getPrisma().user.findFirst({ where: idWhere(value) }); if (!user || !user.isActive) throw AppError.unauthorized(); return user; }
async function resolvePaperIds(values: string[]) { if (!values.length) return []; const papers = await getPrisma().paper.findMany({ where: { OR: values.map(idWhere) }, select: { id: true, legacyMongoId: true } }); const map = new Map<string, string>(); for (const paper of papers) { map.set(paper.id, paper.id); if (paper.legacyMongoId) map.set(paper.legacyMongoId, paper.id); } return values.flatMap((value) => { const id = map.get(value); return id ? [id] : []; }); }
async function resolveProject(value?: string) { if (!value) return null; const project = await getPrisma().project.findFirst({ where: idWhere(value) }); if (!project) throw AppError.notFound("Project not found"); return project; }
async function resolveAnalysis(value: string) { return getPrisma().gapAnalysis.findFirst({ where: idWhere(value) }); }
async function resolveGap(value: string) { return getPrisma().researchGap.findFirst({ where: idWhere(value) }); }

function paperTextWhere(phrases: string[]) {
  return { AND: phrases.map((phrase) => ({ OR: [{ title: { contains: phrase.trim(), mode: "insensitive" as const } }, { abstractText: { contains: phrase.trim(), mode: "insensitive" as const } }] })) };
}

async function conceptGrowthPct(phrase: string, years: { yearFrom?: number; yearTo?: number; paperIds?: string[] }) {
  const now = new Date().getFullYear(), yearTo = years.yearTo ?? now, yearFrom = years.yearFrom ?? yearTo - GAP_WINDOW_YEARS;
  const ids = years.paperIds ? await resolvePaperIds(years.paperIds) : undefined;
  const rows = await getPrisma().paper.groupBy({ by: ["publicationYear"], where: { dataStatus: "active", ...paperTextWhere([phrase]), ...(ids ? { id: { in: ids } } : {}), publicationYear: { gte: yearFrom, lte: yearTo } }, _count: { _all: true }, orderBy: { publicationYear: "asc" } });
  const series = fillMissingYears(rows.map((row) => ({ year: row.publicationYear, count: row._count._all })), yearFrom, yearTo);
  return yoyGrowthPct(truncateToCompleteYears(series, Math.min(yearTo, now - 1)));
}

async function scoreGapEvidence(probe: GapProbe | undefined, paperIds?: string[]) {
  if (!probe?.topicA || !probe?.topicB) return null;
  const prisma = getPrisma(), resolvedIds = paperIds ? await resolvePaperIds(paperIds) : undefined;
  const base = { dataStatus: "active", ...(resolvedIds ? { id: { in: resolvedIds } } : {}), ...((probe.yearFrom !== undefined || probe.yearTo !== undefined) ? { publicationYear: { ...(probe.yearFrom !== undefined ? { gte: probe.yearFrom } : {}), ...(probe.yearTo !== undefined ? { lte: probe.yearTo } : {}) } } : {}) };
  const [intersectionCount, aCount, bCount, growthA, growthB] = await Promise.all([
    prisma.paper.count({ where: { ...base, ...paperTextWhere([probe.topicA, probe.topicB]) } }),
    prisma.paper.count({ where: { ...base, ...paperTextWhere([probe.topicA]) } }),
    prisma.paper.count({ where: { ...base, ...paperTextWhere([probe.topicB]) } }),
    conceptGrowthPct(probe.topicA, { yearFrom: probe.yearFrom, yearTo: probe.yearTo, paperIds }),
    conceptGrowthPct(probe.topicB, { yearFrom: probe.yearFrom, yearTo: probe.yearTo, paperIds }),
  ]);
  const parentTrend = growthA >= growthB ? { topic: probe.topicA, growthRatePct: growthA } : { topic: probe.topicB, growthRatePct: growthB };
  const evidence = computeGapEvidence({ intersectionCount, parentCounts: { a: aCount, b: bCount }, parentRisingGrowthPct: parentTrend.growthRatePct }, { scarceAbs: env.GAP_SCARCE_ABS, scarcePct: env.GAP_SCARCE_PCT, parentRisingMin: env.GAP_PARENT_RISING_MIN });
  return { ...evidence, probe, parentTrend };
}

async function assertCanReadGap(userInput: string, gap: { userId: string; projectId: string | null }) {
  const user = await resolveUser(userInput); if (gap.userId === user.id) return user;
  if (gap.projectId) { const project = await getPrisma().project.findUnique({ where: { id: gap.projectId } }); if (project?.ownerId === user.id || await getPrisma().projectMember.findFirst({ where: { projectId: gap.projectId, userId: user.id, status: "ACTIVE" } })) return user; }
  throw AppError.notFound("Research gap not found");
}

async function analysisDto(analysis: NonNullable<Awaited<ReturnType<typeof resolveAnalysis>>>) {
  const [gaps, papers] = await Promise.all([getPrisma().researchGap.findMany({ where: { analysisId: analysis.id }, select: { id: true, legacyMongoId: true } }), getPrisma().gapAnalysisPaper.findMany({ where: { analysisId: analysis.id }, orderBy: { position: "asc" } })]);
  const paperRows = await getPrisma().paper.findMany({ where: { id: { in: papers.map((row) => row.paperId) } }, select: { id: true, legacyMongoId: true } }); const paperMap = new Map(paperRows.map((row) => [row.id, publicDatabaseId(row)]));
  return { id: publicDatabaseId(analysis), topic: analysis.topic, status: analysis.status, gapIds: gaps.map(publicDatabaseId), errorMessage: analysis.errorMessage ?? undefined, yearFrom: analysis.yearFrom ?? undefined, yearTo: analysis.yearTo ?? undefined, selectedPaperIds: papers.flatMap((row) => { const id = paperMap.get(row.paperId); return id ? [id] : []; }), evidenceMode: analysis.evidenceMode as GapEvidenceMode, createdAt: analysis.createdAt.toISOString(), updatedAt: analysis.updatedAt.toISOString() };
}

async function directionsDto(row: { id: string; gapId: string; model: string; updatedAt: Date }): Promise<GapDirections> {
  const items = await getPrisma().gapDirectionItem.findMany({ where: { directionsId: row.id }, orderBy: { position: "asc" } });
  const links = await getPrisma().gapDirectionPaper.findMany({ where: { directionId: { in: items.map((item) => item.id) } }, orderBy: { position: "asc" } });
  const papers = await getPrisma().paper.findMany({ where: { id: { in: links.map((link) => link.paperId) } }, select: { id: true, legacyMongoId: true } }); const paperMap = new Map(papers.map((paper) => [paper.id, publicDatabaseId(paper)]));
  return { gapId: row.gapId, directions: items.map((item) => ({ title: item.title, rationale: item.rationale, suggestedApproach: item.suggestedApproach, relatedPaperIds: links.filter((link) => link.directionId === item.id).flatMap((link) => { const id = paperMap.get(link.paperId); return id ? [id] : []; }) })), model: row.model, updatedAt: row.updatedAt.toISOString() };
}

export const gapsService = {
  async previewEvidence(userId: string, dto: PreviewGapEvidenceDto): Promise<PreviewGapEvidenceResponse> {
    const projectPaperIds = dto.projectId ? await projectService.getProjectPaperIdsForUser(dto.projectId, userId, "gap analysis") : undefined; const mode = dto.evidenceMode ?? "hybrid"; let queryVector: number[] | undefined, usedTextFallback = false;
    if (mode !== "selected") { try { queryVector = await getEmbeddingProvider().embed(dto.topic); } catch (error) { usedTextFallback = true; logger.warn({ err: error }, "gap evidence preview embedding failed; using text fallback"); } }
    const evidence = await collectGapEvidence({ topic: dto.topic, queryVector, selectedPaperIds: dto.selectedPaperIds, evidenceMode: mode, yearFrom: dto.yearFrom, yearTo: dto.yearTo, projectPaperIds });
    const warnings = evidence.missingSelectedPaperIds.map((id) => `Selected paper ${id} is unavailable in this evidence scope and was skipped.`); if (usedTextFallback) warnings.push("Semantic retrieval was unavailable, so keyword fallback was used."); if (evidence.papers.length < 3) warnings.push("Fewer than 3 evidence papers were found. Broaden the topic or year range.");
    return { papers: evidence.papers.map(toPreviewGapPaper), selectedPaperIds: evidence.selectedPaperIds, retrievedPaperIds: evidence.retrievedPaperIds, maxEvidencePapers: env.GAPS_TOP_K, warnings };
  },

  async enqueue(userInput: string, dto: AnalyzeGapDto): Promise<string> {
    if ((dto.selectedPaperIds?.length ?? 0) > env.GAPS_TOP_K) throw AppError.badRequest(`Gap evidence cannot exceed ${env.GAPS_TOP_K} papers.`);
    const user = await resolveUser(userInput), project = await resolveProject(dto.projectId); let projectPaperIds: string[] | undefined;
    if (dto.projectId) projectPaperIds = await projectService.getProjectPaperIdsForUser(dto.projectId, userInput, "gap analysis");
    if (dto.evidenceMode === "selected") { const evidence = await collectGapEvidence({ topic: dto.topic, selectedPaperIds: dto.selectedPaperIds, evidenceMode: "selected", yearFrom: dto.yearFrom, yearTo: dto.yearTo, projectPaperIds }); if (evidence.papers.length < 3 || evidence.missingSelectedPaperIds.length) throw AppError.badRequest("The reviewed evidence pack must contain at least 3 active papers in this scope.", { missingPaperIds: evidence.missingSelectedPaperIds }); }
    const analysisId = crypto.randomUUID(); const tx = await creditService.chargeCreditsChecked({ userId: user.id, action: "generate_gaps", amount: 30, targetKind: "gap_analysis", targetId: analysisId, idempotencyKey: `gap_analysis:${analysisId}` });
    try {
      const selectedIds = await resolvePaperIds(dto.selectedPaperIds ?? []); const analysis = await getPrisma().$transaction(async (db) => { const row = await db.gapAnalysis.create({ data: { id: analysisId, userId: user.id, projectId: project?.id, topic: dto.topic, yearFrom: dto.yearFrom, yearTo: dto.yearTo, evidenceMode: dto.evidenceMode ?? "auto", status: "queued", creditTransactionId: tx?.id, creditCost: 30, creditAction: "generate_gaps" } }); if (selectedIds.length) await db.gapAnalysisPaper.createMany({ data: selectedIds.map((paperId, position) => ({ analysisId: row.id, paperId, position })) }); return row; });
      await gapsQueue.add("gap-analysis", { analysisId: analysis.id }); return publicDatabaseId(analysis);
    } catch (error) { if (tx?.id) await creditService.refundCreditsOnce({ transactionId: tx.id, reason: "Failed to create gap analysis or enqueue job" }); throw error; }
  },

  async getAnalysis(userInput: string, analysisInput: string) { const user = await resolveUser(userInput); const row = await getPrisma().gapAnalysis.findFirst({ where: { ...idWhere(analysisInput), userId: user.id } }); if (!row) throw AppError.notFound("Gap analysis not found"); return analysisDto(row); },
  async getActiveAnalysis(userInput: string) { const user = await resolveUser(userInput); const row = await getPrisma().gapAnalysis.findFirst({ where: { userId: user.id, status: { in: ["queued", "analyzing"] } }, orderBy: { createdAt: "desc" } }); return row ? analysisDto(row) : null; },
  async retryAnalysis(userInput: string, analysisInput: string) { const user = await resolveUser(userInput); const failed = await getPrisma().gapAnalysis.findFirst({ where: { ...idWhere(analysisInput), userId: user.id, status: "failed" } }); if (!failed) throw AppError.conflict("Only a failed gap analysis can be retried"); const dto = await analysisDto(failed); const project = failed.projectId ? await getPrisma().project.findUnique({ where: { id: failed.projectId } }) : null; return this.enqueue(userInput, { topic: failed.topic, projectId: project ? publicDatabaseId(project) : undefined, yearFrom: failed.yearFrom ?? undefined, yearTo: failed.yearTo ?? undefined, selectedPaperIds: dto.selectedPaperIds, evidenceMode: failed.evidenceMode as GapEvidenceMode }); },

  async runGapPipeline(job: GapJob): Promise<void> {
    const analysis = await resolveAnalysis(job.analysisId); if (!analysis) { logger.warn({ analysisId: job.analysisId }, "gap analysis vanished before processing"); return; } if (analysis.status === "ready") return;
    await getPrisma().gapAnalysis.update({ where: { id: analysis.id }, data: { status: "analyzing" } });
    const evidenceMode = analysis.evidenceMode as GapEvidenceMode; const queryVector = evidenceMode === "selected" ? undefined : await getEmbeddingProvider().embed(analysis.topic);
    const user = await getPrisma().user.findUniqueOrThrow({ where: { id: analysis.userId } }); const project = analysis.projectId ? await getPrisma().project.findUnique({ where: { id: analysis.projectId } }) : null;
    const projectPaperIds = project ? await projectService.getProjectPaperIdsForUser(publicDatabaseId(project), publicDatabaseId(user), "gap analysis") : undefined;
    const selectedLinks = await getPrisma().gapAnalysisPaper.findMany({ where: { analysisId: analysis.id }, orderBy: { position: "asc" } }); const selectedRows = await getPrisma().paper.findMany({ where: { id: { in: selectedLinks.map((row) => row.paperId) } }, select: { id: true, legacyMongoId: true } }); const selectedMap = new Map(selectedRows.map((row) => [row.id, publicDatabaseId(row)]));
    const evidence = await collectGapEvidence({ topic: analysis.topic, queryVector, selectedPaperIds: selectedLinks.flatMap((row) => { const id = selectedMap.get(row.paperId); return id ? [id] : []; }), evidenceMode, yearFrom: analysis.yearFrom ?? undefined, yearTo: analysis.yearTo ?? undefined, projectPaperIds }); const papers = evidence.papers;
    if (!papers.length || (evidenceMode === "selected" && papers.length < 3)) { await this.markAnalysisFailed(job.analysisId, evidenceMode === "selected" ? "The reviewed evidence pack no longer contains at least 3 active papers." : "Not enough corpus data for this topic — try a broader question."); return; }
    const normalizedTopic = normalizeTopicStr(analysis.topic), model = env.GEMINI_MODEL_DEEP; const cacheKey = buildGapsCacheKey({ normalizedTopic, yearFrom: analysis.yearFrom ?? undefined, yearTo: analysis.yearTo ?? undefined, model, retrievedPaperIds: papers.map((paper) => paper.id) }); let cacheHit = false;
    const output = await cachedGenerateJSON<GapsLlmOutput>({ task: "gap", promptVersion: GAP_PROMPT_VERSION, keyParts: { legacyCacheKey: cacheKey, normalizedTopic, yearFrom: analysis.yearFrom, yearTo: analysis.yearTo, retrievedPaperIds: papers.map((paper) => paper.id) }, model, prompt: buildGapsPrompt(analysis.topic, papers), onCacheHit: () => { cacheHit = true; }, validate: (candidate) => { if (!candidate || !Array.isArray(candidate.gaps) || !candidate.gaps.length) throw new LlmContentError("LLM returned empty gaps output"); return candidate; }, options: { system: GAPS_SYSTEM_PROMPT, temperature: 0.2, maxOutputTokens: env.GAPS_MAX_OUTPUT_TOKENS } });
    const evidenceScopePaperIds = evidenceMode === "auto" ? projectPaperIds : papers.map((paper) => paper.id); const paperRows = await getPrisma().paper.findMany({ where: { OR: papers.map((paper) => idWhere(paper.id)) }, select: { id: true, legacyMongoId: true } }); const paperMap = new Map<string, string>(); for (const row of paperRows) { paperMap.set(publicDatabaseId(row), row.id); paperMap.set(row.id, row.id); }
    const prepared = await Promise.all(output.gaps.slice(0, 5).map(async (gap) => ({ gap, evidence: await scoreGapEvidence(gap.probe, evidenceScopePaperIds) })));
    const gapRows = await getPrisma().$transaction(async (db) => {
      const old = await db.researchGap.findMany({ where: { analysisId: analysis.id }, select: { id: true } }); if (old.length) { await db.researchGapPaper.deleteMany({ where: { gapId: { in: old.map((row) => row.id) } } }); await db.researchGap.deleteMany({ where: { id: { in: old.map((row) => row.id) } } }); }
      const created = [];
      for (const item of prepared) { const gap = item.gap, scored = item.evidence; const row = await db.researchGap.create({ data: { topic: analysis.topic, normalizedTopic, analysisId: analysis.id, title: String(gap.title ?? "").slice(0, 200), description: String(gap.description ?? ""), rationale: String(gap.rationale ?? ""), confidence: clamp01(gap.confidence), probe: scored?.probe as never, intersectionCount: scored?.intersectionCount, parentCounts: scored?.parentCounts as never, parentTrend: (scored?.parentTrend ?? null) as never, evidenceConfidence: scored?.evidenceConfidence ?? clamp01(gap.confidence), source: "standalone", userId: analysis.userId, projectId: analysis.projectId } }); const evidenceIds = papers.flatMap((paper) => { const id = paperMap.get(paper.id); return id ? [id] : []; }); const supportingIds = (gap.supportingEvidence ?? []).filter((index) => Number.isInteger(index) && index >= 1 && index <= papers.length).flatMap((index) => { const paper = papers[index - 1]; const id = paper ? paperMap.get(paper.id) : undefined; return id ? [id] : []; }); await db.researchGapPaper.createMany({ data: [...new Set(evidenceIds)].map((paperId, position) => ({ gapId: row.id, paperId, kind: "evidence", position })).concat([...new Set(supportingIds)].map((paperId, position) => ({ gapId: row.id, paperId, kind: "supporting", position }))), skipDuplicates: true }); created.push(row); }
      await db.gapAnalysis.update({ where: { id: analysis.id }, data: { status: "ready", promptVersion: GAP_PROMPT_VERSION, modelVersion: model, ...(cacheHit ? { creditRefundedAt: new Date() } : {}) } }); if (analysis.projectId && created.length) await db.projectActivity.create({ data: { projectId: analysis.projectId, actorId: analysis.userId, type: "GAP_CREATED", entityKind: "GAP_ANALYSIS", entityId: publicDatabaseId(analysis), metadata: { count: created.length, origin: "AI_ASSISTED", status: "CANDIDATE" } } }); return created;
    });
    if (cacheHit && analysis.creditTransactionId) await creditService.refundCreditsOnce({ transactionId: analysis.creditTransactionId, reason: "Gap analysis cache hit" }); logger.info({ analysisId: job.analysisId, gaps: gapRows.length, cacheHit }, "gap analysis ready");
  },

  async fanOutGapsFromReport(report: { _id: unknown; userId: unknown; projectId?: unknown; projectPaperIds?: unknown[]; evidencePaperIds?: unknown[]; query: string; researchGaps: Array<{ title: string; description: string; rationale: string; supportingPaperIds: unknown[]; confidence: number; probe?: GapProbe }> }) {
    if (!report.researchGaps?.length) return; const user = await resolveUser(String(report.userId)), project = report.projectId ? await resolveProject(String(report.projectId)) : null; const reportRow = await getPrisma().report.findFirst({ where: idWhere(String(report._id)) }); if (!reportRow) throw AppError.notFound("Report not found"); const scopedPaperIds = project ? (report.projectPaperIds ?? []).map(String) : undefined;
    for (const gap of report.researchGaps) { const scored = await scoreGapEvidence(gap.probe, scopedPaperIds); const row = await getPrisma().researchGap.create({ data: { topic: report.query, normalizedTopic: normalizeTopicStr(report.query), title: gap.title.slice(0, 200), description: gap.description, rationale: gap.rationale, confidence: clamp01(gap.confidence), probe: scored?.probe as never, intersectionCount: scored?.intersectionCount, parentCounts: scored?.parentCounts as never, parentTrend: (scored?.parentTrend ?? null) as never, evidenceConfidence: scored?.evidenceConfidence ?? clamp01(gap.confidence), source: "report", sourceReportId: reportRow.id, userId: user.id, projectId: project?.id } }); const evidenceIds = await resolvePaperIds((report.evidencePaperIds ?? gap.supportingPaperIds).map(String)); const supportIds = await resolvePaperIds(gap.supportingPaperIds.map(String)); await getPrisma().researchGapPaper.createMany({ data: [...new Set(evidenceIds)].map((paperId, position) => ({ gapId: row.id, paperId, kind: "evidence", position })).concat([...new Set(supportIds)].map((paperId, position) => ({ gapId: row.id, paperId, kind: "supporting", position }))), skipDuplicates: true }); }
  },

  async list(userInput: string, query: ListGapsQuery) {
    const user = await resolveUser(userInput); let projectId: string | undefined; if (query.projectId) { const project = await resolveProject(query.projectId); if (!project) throw AppError.notFound("Project not found"); if (project.ownerId !== user.id && !await getPrisma().projectMember.findFirst({ where: { projectId: project.id, userId: user.id, status: "ACTIVE" } })) throw AppError.notFound("Project not found"); projectId = project.id; }
    const where = { ...(projectId ? { projectId } : { userId: user.id }), status: query.status, ...(query.topic ? { normalizedTopic: { contains: normalizeTopicStr(query.topic), mode: "insensitive" as const } } : {}), ...(query.source ? { source: query.source } : {}), ...(query.minConfidence !== undefined ? { confidence: { gte: query.minConfidence } } : {}), ...(query.search ? { OR: [{ title: { contains: query.search, mode: "insensitive" as const } }, { description: { contains: query.search, mode: "insensitive" as const } }, { topic: { contains: query.search, mode: "insensitive" as const } }] } : {}) };
    const [all, total] = await Promise.all([getPrisma().researchGap.findMany({ where }), getPrisma().researchGap.count({ where })]); const links = await getPrisma().researchGapPaper.findMany({ where: { gapId: { in: all.map((row) => row.id) } }, orderBy: { position: "asc" } }); const linkCount = new Map<string, number>(); for (const link of links.filter((row) => row.kind === "supporting")) linkCount.set(link.gapId, (linkCount.get(link.gapId) ?? 0) + 1);
    all.sort(query.sortBy === "newest" ? (a, b) => b.createdAt.getTime() - a.createdAt.getTime() : query.sortBy === "papers" ? (a, b) => (linkCount.get(b.id) ?? 0) - (linkCount.get(a.id) ?? 0) || (b.evidenceConfidence ?? b.confidence) - (a.evidenceConfidence ?? a.confidence) : (a, b) => (b.evidenceConfidence ?? b.confidence) - (a.evidenceConfidence ?? a.confidence) || b.createdAt.getTime() - a.createdAt.getTime());
    const pageRows = all.slice((query.page - 1) * query.pageSize, query.page * query.pageSize); const selectedLinks = links.filter((link) => pageRows.some((row) => row.id === link.gapId)); const papers = await getPrisma().paper.findMany({ where: { id: { in: selectedLinks.map((row) => row.paperId) } }, select: { id: true, legacyMongoId: true, title: true, publicationYear: true, journalName: true, citationCount: true } }); const publicPaper = new Map(papers.map((paper) => [paper.id, { id: publicDatabaseId(paper), title: paper.title, publicationYear: paper.publicationYear, journalName: paper.journalName ?? undefined, citationCount: paper.citationCount }])); const supportingPapersById = new Map([...publicPaper.values()].map((paper) => [paper.id, paper]));
    const gaps = pageRows.map((row) => { const evidenceIds = selectedLinks.filter((link) => link.gapId === row.id && link.kind === "evidence").flatMap((link) => { const paper = publicPaper.get(link.paperId); return paper ? [paper.id] : []; }); const supportingIds = selectedLinks.filter((link) => link.gapId === row.id && link.kind === "supporting").flatMap((link) => { const paper = publicPaper.get(link.paperId); return paper ? [paper.id] : []; }); const probe = row.probe as GapListDoc["probe"], parentCounts = row.parentCounts as GapListDoc["parentCounts"], parentTrend = row.parentTrend as GapListDoc["parentTrend"]; return toGapListItem({ _id: publicDatabaseId(row), topic: row.topic, normalizedTopic: row.normalizedTopic, title: row.title, description: row.description, rationale: row.rationale, evidencePaperIds: evidenceIds, supportingPaperIds: supportingIds, confidence: row.confidence, probe, intersectionCount: row.intersectionCount ?? undefined, parentCounts, parentTrend, evidenceConfidence: row.evidenceConfidence ?? undefined, source: row.source as "report" | "standalone", sourceReportId: row.sourceReportId, analysisId: row.analysisId, projectId: row.projectId, userId: row.userId, status: row.status as "active" | "resolved" | "dismissed", createdAt: row.createdAt, gapType: row.gapType as never, scope: row.scope ?? undefined, establishedKnowledge: row.establishedKnowledge ?? undefined, observedLimitation: row.observedLimitation ?? undefined, missingEvidence: row.missingEvidence ?? undefined, significanceExplanation: row.significanceExplanation ?? undefined, suggestedResearchQuestion: row.suggestedResearchQuestion ?? undefined, validationStatus: row.validationStatus as never, gapConfidence: row.gapConfidence as never, researchPriority: row.researchPriority as never, origin: row.origin as never }, supportingPapersById); });
    return { gaps, total };
  },

  async patchStatus(userInput: string, gapInput: string, dto: PatchGapDto) { const user = await resolveUser(userInput), gap = await resolveGap(gapInput); if (!gap) throw AppError.notFound("Research gap not found"); if (gap.userId !== user.id) throw AppError.forbidden("Only the creator can update gap status"); const updated = await getPrisma().researchGap.update({ where: { id: gap.id }, data: { status: dto.status } }); return { id: publicDatabaseId(updated), status: updated.status }; },

  async generateDirections(userInput: string, gapInput: string, force?: boolean): Promise<GapDirections> {
    const gap = await resolveGap(gapInput); if (!gap) throw AppError.notFound("Research gap not found"); const user = await assertCanReadGap(userInput, gap); const links = await getPrisma().researchGapPaper.findMany({ where: { gapId: gap.id, kind: "supporting" }, orderBy: { position: "asc" } }); const papers = await getPrisma().paper.findMany({ where: { id: { in: links.map((row) => row.paperId) } }, select: { id: true, legacyMongoId: true, title: true, abstractText: true, aiAnalysis: true } }); const paperMap = new Map(papers.map((paper) => [paper.id, paper])); const directionPapers = links.flatMap((link) => { const paper = paperMap.get(link.paperId); return paper ? [{ id: publicDatabaseId(paper), title: paper.title, abstractText: paper.abstractText ?? undefined, aiAnalysis: paper.aiAnalysis as never }] : []; }); const allowedPaperIds = directionPapers.map((paper) => paper.id), evidenceHash = buildDirectionsEvidenceHash(directionPapers); const existing = await getPrisma().gapDirections.findUnique({ where: { gapId: gap.id } }); if (existing && !force && existing.promptVersion === DIRECTIONS_PROMPT_VERSION && existing.evidenceHash === evidenceHash) return directionsDto(existing);
    const tx = await creditService.chargeCreditsChecked({ userId: user.id, action: "generate_directions", amount: 15, targetKind: "gap_direction", targetId: gap.id, idempotencyKey: `directions:${gap.id}:${crypto.randomUUID()}` }); let txId = tx?.id, cacheHit = false; let raw: DirectionsRaw;
    try { raw = await cachedGenerateJSON<DirectionsRaw>({ task: "directions", promptVersion: DIRECTIONS_PROMPT_VERSION, keyParts: { gapId: gap.id, allowedPaperIds }, model: env.GEMINI_MODEL_FAST, bypassCache: force, prompt: buildDirectionsPrompt({ topic: gap.topic, title: gap.title, description: gap.description, rationale: gap.rationale, intersectionCount: gap.intersectionCount ?? undefined, parentTrend: gap.parentTrend as never }, directionPapers), onCacheHit: () => { cacheHit = true; }, validate: (candidate) => { if (!sanitizeDirections(candidate, allowedPaperIds).length) throw new LlmContentError("LLM returned no valid research directions"); return candidate; }, options: { system: DIRECTIONS_SYSTEM_PROMPT, temperature: 0.4, maxOutputTokens: 1024 } }); } catch (error) { if (txId) await creditService.refundCreditsOnce({ transactionId: txId, reason: "Directions generation failed" }); logger.warn({ err: error, gapId: gap.id }, "gap directions generation failed"); throw AppError.serviceUnavailable("AI gợi ý tạm thời không khả dụng. Vui lòng thử lại."); }
    if (cacheHit && txId) { await creditService.refundCreditsOnce({ transactionId: txId, reason: "Directions cache hit" }); txId = undefined; } const directions = sanitizeDirections(raw, allowedPaperIds); if (!directions.length) throw AppError.serviceUnavailable("AI không trả về gợi ý hợp lệ. Vui lòng thử lại.");
    const saved = await getPrisma().$transaction(async (db) => { const root = await db.gapDirections.upsert({ where: { gapId: gap.id }, create: { gapId: gap.id, model: env.GEMINI_MODEL_FAST, promptVersion: DIRECTIONS_PROMPT_VERSION, evidenceHash, creditTransactionId: txId, creditCost: txId ? 15 : 0 }, update: { model: env.GEMINI_MODEL_FAST, promptVersion: DIRECTIONS_PROMPT_VERSION, evidenceHash, creditTransactionId: txId ?? null, creditCost: txId ? 15 : 0 } }); const old = await db.gapDirectionItem.findMany({ where: { directionsId: root.id }, select: { id: true } }); if (old.length) { await db.gapDirectionPaper.deleteMany({ where: { directionId: { in: old.map((row) => row.id) } } }); await db.gapDirectionItem.deleteMany({ where: { directionsId: root.id } }); } for (const [position, direction] of directions.entries()) { const item = await db.gapDirectionItem.create({ data: { directionsId: root.id, title: direction.title, rationale: direction.rationale, suggestedApproach: direction.suggestedApproach, position } }); const related = await resolvePaperIds(direction.relatedPaperIds); if (related.length) await db.gapDirectionPaper.createMany({ data: related.map((paperId, paperPosition) => ({ directionId: item.id, paperId, position: paperPosition })), skipDuplicates: true }); } return root; }); return directionsDto(saved);
  },

  async getDirections(userInput: string, gapInput: string) { const gap = await resolveGap(gapInput); if (!gap) throw AppError.notFound("Research gap not found"); await assertCanReadGap(userInput, gap); const row = await getPrisma().gapDirections.findUnique({ where: { gapId: gap.id } }); return row ? directionsDto(row) : null; },

  async markAnalysisFailed(analysisInput: string, message: string) { const analysis = await resolveAnalysis(analysisInput); if (!analysis || analysis.status === "ready") return; const claimed = await getPrisma().gapAnalysis.updateMany({ where: { id: analysis.id, status: { not: "ready" }, creditRefundedAt: null }, data: { status: "failed", errorMessage: message.slice(0, 500), creditRefundedAt: new Date() } }); if (claimed.count && analysis.creditTransactionId) await creditService.refundCreditsOnce({ transactionId: analysis.creditTransactionId, reason: `Gap analysis failed: ${message.slice(0, 100)}` }); else if (!claimed.count) await getPrisma().gapAnalysis.updateMany({ where: { id: analysis.id, status: { not: "ready" } }, data: { status: "failed", errorMessage: message.slice(0, 500) } }); },
};

async function collectGapEvidence(input: CollectGapEvidenceInput): Promise<CollectGapEvidenceResult> {
  const selectedPaperIds = [...new Set(input.selectedPaperIds ?? [])]; const selected = input.evidenceMode === "auto" ? { papers: [] as GapEvidenceCandidate[], missingIds: [] as string[] } : await fetchSelectedGapEvidence(selectedPaperIds, input); let retrieved: GapEvidenceCandidate[] = [];
  if (input.evidenceMode !== "selected") { const filters = { yearFrom: input.yearFrom, yearTo: input.yearTo, paperIds: input.projectPaperIds }; const candidates = input.queryVector?.length ? await retrieveGapEvidence(input.queryVector, filters) : await retrieveGapTextEvidence(input.topic, filters); retrieved = candidates.map((paper) => ({ ...paper, authorNames: paper.authorNames, score: Number(paper.score ?? 0.5), source: "retrieved" })); }
  const seen = new Set<string>(), papers: GapEvidenceCandidate[] = []; for (const paper of [...selected.papers, ...retrieved]) { if (papers.length >= env.GAPS_TOP_K) break; if (!seen.has(paper.id)) { seen.add(paper.id); papers.push(paper); } }
  return { papers, selectedPaperIds, retrievedPaperIds: retrieved.map((paper) => paper.id), missingSelectedPaperIds: selected.missingIds };
}

async function fetchSelectedGapEvidence(values: string[], input: Pick<CollectGapEvidenceInput, "yearFrom" | "yearTo" | "projectPaperIds">) {
  if (!values.length) return { papers: [] as GapEvidenceCandidate[], missingIds: [] as string[] }; const allowed = input.projectPaperIds ? new Set(input.projectPaperIds) : null; const eligible = allowed ? values.filter((id) => allowed.has(id)) : values; const prisma = getPrisma(); const docs = await prisma.paper.findMany({ where: { OR: eligible.map(idWhere), dataStatus: "active", ...((input.yearFrom !== undefined || input.yearTo !== undefined) ? { publicationYear: { ...(input.yearFrom !== undefined ? { gte: input.yearFrom } : {}), ...(input.yearTo !== undefined ? { lte: input.yearTo } : {}) } } : {}) }, select: { id: true, legacyMongoId: true, title: true, abstractText: true, aiAnalysis: true, publicationYear: true, journalName: true, citationCount: true } }); const authors = await prisma.paperAuthor.findMany({ where: { paperId: { in: docs.map((row) => row.id) } }, orderBy: { position: "asc" } }); const authorMap = new Map<string, string[]>(); for (const author of authors) { const list = authorMap.get(author.paperId) ?? []; list.push(author.displayName); authorMap.set(author.paperId, list); } const byId = new Map<string, typeof docs[number]>(); for (const doc of docs) { byId.set(doc.id, doc); if (doc.legacyMongoId) byId.set(doc.legacyMongoId, doc); }
  const papers: GapEvidenceCandidate[] = [], missingIds: string[] = []; for (const value of values) { const doc = byId.get(value); if (!doc) { missingIds.push(value); continue; } papers.push({ id: publicDatabaseId(doc), title: doc.title, abstractText: doc.abstractText ?? undefined, aiAnalysis: doc.aiAnalysis as never, publicationYear: doc.publicationYear, journalName: doc.journalName ?? undefined, citationCount: doc.citationCount, authorNames: authorMap.get(doc.id) ?? [], score: 1, source: "selected" }); } return { papers, missingIds };
}

async function retrieveGapTextEvidence(topic: string, filters: { yearFrom?: number; yearTo?: number; paperIds?: string[] }) {
  const ids = filters.paperIds ? await resolvePaperIds(filters.paperIds) : undefined; const terms = topic.split(/\s+/).map((value) => value.trim()).filter((value) => value.length > 1).slice(0, 8); const docs = await getPrisma().paper.findMany({ where: { dataStatus: "active", ...(ids ? { id: { in: ids } } : {}), ...((filters.yearFrom !== undefined || filters.yearTo !== undefined) ? { publicationYear: { ...(filters.yearFrom !== undefined ? { gte: filters.yearFrom } : {}), ...(filters.yearTo !== undefined ? { lte: filters.yearTo } : {}) } } : {}), ...(terms.length ? { OR: terms.flatMap((term) => [{ title: { contains: term, mode: "insensitive" as const } }, { abstractText: { contains: term, mode: "insensitive" as const } }]) } : {}) }, orderBy: [{ citationCount: "desc" }, { publicationYear: "desc" }], take: env.GAPS_TOP_K, select: { id: true, legacyMongoId: true, title: true, abstractText: true, aiAnalysis: true, publicationYear: true, journalName: true, citationCount: true } }); return hydrateEvidence(docs, "retrieved");
}

async function retrieveGapEvidence(queryVector: number[], filters: { yearFrom?: number; yearTo?: number; paperIds?: string[] }) { const papers = await retrieve({ queryVector, topK: env.GAPS_TOP_K, poolSize: env.GAPS_TOP_K, filters }); return papers.map((paper) => ({ ...paper, authorNames: paper.authorNames, score: Number(paper.score ?? 0.5), source: "retrieved" as const })); }

async function hydrateEvidence(docs: Array<{ id: string; legacyMongoId: string | null; title: string; abstractText: string | null; aiAnalysis: unknown; publicationYear: number; journalName: string | null; citationCount: number }>, source: "selected" | "retrieved") { const authors = await getPrisma().paperAuthor.findMany({ where: { paperId: { in: docs.map((row) => row.id) } }, orderBy: { position: "asc" } }); const map = new Map<string, string[]>(); for (const author of authors) { const list = map.get(author.paperId) ?? []; list.push(author.displayName); map.set(author.paperId, list); } return docs.map((doc) => ({ id: publicDatabaseId(doc), title: doc.title, abstractText: doc.abstractText ?? undefined, aiAnalysis: doc.aiAnalysis as never, publicationYear: doc.publicationYear, journalName: doc.journalName ?? undefined, citationCount: doc.citationCount, authorNames: map.get(doc.id) ?? [], score: 0.5, source })); }
function toPreviewGapPaper(paper: GapEvidenceCandidate) { return { id: paper.id, title: paper.title, abstractText: paper.abstractText, publicationYear: paper.publicationYear, journalName: paper.journalName, citationCount: paper.citationCount, authorNames: paper.authorNames, score: paper.score, source: paper.source }; }
