/**
 * Centralised list of backend route paths. Use these everywhere instead of
 * string literals so renames stay safe and grep-able.
 */
export const API_ROUTES = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    oauthExchange: "/auth/oauth/exchange",
    me: "/auth/me",
    academicProfile: "/auth/me/academic-profile",
    changePassword: "/auth/change-password",
    verifyEmail: "/auth/email/verify",
    resendEmailVerification: "/auth/email/resend",
    forgotPassword: "/auth/password/forgot",
    resetPassword: "/auth/password/reset",
  },
  academicProfiles: {
    me: "/academic-profiles/me",
    academicIdentities: "/academic-profiles/me/academic-identities",
    academicIdentity: (identityId: string) => `/academic-profiles/me/academic-identities/${identityId}`,
    public: (userId: string) => `/academic-profiles/${userId}`,
    byHandle: (handle: string) => `/academic-profiles/by-handle/${encodeURIComponent(handle)}`,
    publicHandle: "/academic-profiles/me/public-handle",
    avatar: "/academic-profiles/me/avatar",
    cover: "/academic-profiles/me/cover",
    summary: (userId: string) => `/academic-profiles/${userId}/summary`,
    lecturers: "/academic-profiles/lecturers",
      verificationStatus: "/academic-profiles/me/verification-status",
      verificationRequest: "/academic-profiles/me/verification-request",
      verificationEvidence: (requestId: string) => `/admin/academic-verifications/${requestId}/evidence`,
      institutionalEmailStatus: "/academic-profiles/me/institutional-email/status",
      institutionalEmailChallenge: "/academic-profiles/me/institutional-email/challenge",
      institutionalEmailVerify: "/academic-profiles/me/institutional-email/verify",
  },
  reviewAvailability: {
    mine: "/review-availability/me",
  },
  reviewOpportunities: {
    list: "/review-opportunities",
    accept: (submissionId: string) => `/review-opportunities/${submissionId}/accept`,
    conflict: (submissionId: string) => `/review-opportunities/${submissionId}/conflicts`,
  },
  reviews: {
    list: "/reviews",
    detail: (assignmentId: string) => `/reviews/${assignmentId}`,
    save: (assignmentId: string) => `/reviews/${assignmentId}`,
    submit: (assignmentId: string) => `/reviews/${assignmentId}/submit`,
  },
  contributions: {
    user: (userId: string) => `/contributions/users/${userId}`,
  },
  submissions: {
    list: "/submissions",
    create: "/submissions",
    detail: (id: string) => `/submissions/${id}`,
    revisions: (id: string) => `/submissions/${id}/revisions`,
    revisionDownload: (id: string, revisionId: string) => `/submissions/${id}/revisions/${revisionId}/download`,
    aiPreReviews: (id: string) => `/submissions/${id}/ai-pre-reviews`,
    runAiPreReview: (id: string) => `/submissions/${id}/ai-pre-review`,
  },
  communities: {
    list: "/communities",
    detail: (idOrSlug: string) => `/communities/${idOrSlug}`,
    join: (id: string) => `/communities/${id}/join`,
    leave: (id: string) => `/communities/${id}/membership`,
    members: (id: string) => `/communities/${id}/members`,
    member: (id: string, userId: string) => `/communities/${id}/members/${userId}`,
  },
  forum: {
    posts: "/forum/posts",
    post: (id: string) => `/forum/posts/${id}`,
    comments: (postId: string) => `/forum/posts/${postId}/comments`,
    postVote: (id: string) => `/forum/posts/${id}/vote`,
    commentVote: (id: string) => `/forum/comments/${id}/vote`,
    acceptAnswer: (postId: string, commentId: string) => `/forum/posts/${postId}/accepted-answer/${commentId}`,
    reports: "/forum/reports",
  },
  home: {
    overview: "/home/overview",
  },
  papers: {
    list: "/papers",
    detail: (id: string) => `/papers/${id}`,
    translation: (id: string) => `/papers/${id}/translation`,
    translationCapabilities: "/papers/translation/capabilities",
    compare: "/papers/compare",
  },
  search: {
    semantic: "/search", 
  },
  trends: {
    topic: (topic: string) => `/trends/${encodeURIComponent(topic)}`,
  },
  reports: {
    list: "/reports",
    detail: (id: string) => `/reports/${id}`,
    create: "/reports",
    paperCount: (paperId: string) => `/reports/paper/${paperId}/count`,
    evidencePreview: "/reports/evidence-preview",
  },
  bookmarks: {
    list: "/bookmarks",
    create: "/bookmarks",
    delete: (id: string) => `/bookmarks/${id}`,
    check: "/bookmarks/check",
    updateNote: (id: string) => `/bookmarks/${id}`,
  },
  notifications: {
    list: "/notifications",
    read: (id: string) => `/notifications/${id}/read`,
    readAll: "/notifications/read-all",
  },
  analytics: {
    summary: "/analytics/search/summary",
    dashboard: "/analytics/search",
    me: "/analytics/search/me",
  },
  admin: {
    sync: "/admin/sync",
    syncRuns: "/admin/sync/runs",
    embedStatus: "/admin/embed/status",
    triggerEmbed: "/admin/embed",
    users: "/admin/users",
    usersSummary: "/admin/users/summary",
    user: (id: string) => `/admin/users/${id}`,
    userRole: (id: string) => `/admin/users/${id}/role`,
    userStatus: (id: string) => `/admin/users/${id}/status`,
    userSessions: (id: string) => `/admin/users/${id}/revoke-sessions`,
    stats: "/admin/stats",
    pipelineStatus: "/admin/pipeline/status",
    openAlexIngestPreflight: "/admin/openalex-ingest/preflight",
    openAlexIngestCampaigns: "/admin/openalex-ingest/campaigns",
    openAlexIngestCampaign: (id: string) => `/admin/openalex-ingest/campaigns/${id}`,
    startOpenAlexIngestCampaign: (id: string) => `/admin/openalex-ingest/campaigns/${id}/start`,
    pauseOpenAlexIngestCampaign: (id: string) => `/admin/openalex-ingest/campaigns/${id}/pause`,
    cancelOpenAlexIngestCampaign: (id: string) => `/admin/openalex-ingest/campaigns/${id}/cancel`,
    triggerCorpusValidation: (campaignId: string) => `/admin/openalex-ingest/campaigns/${campaignId}/validations`,
    latestCorpusValidation: (campaignId: string) => `/admin/openalex-ingest/campaigns/${campaignId}/validations/latest`,
    corpusValidationRun: (validationRunId: string) => `/admin/openalex-ingest/validations/${validationRunId}`,
    evaluationSummary: "/admin/evaluation/summary",
    academicVerifications: "/admin/academic-verifications",
    academicVerification: (profileId: string) => `/admin/academic-verifications/${profileId}`,
    auditLogs: "/admin/audit-logs",
    workers: "/admin/workers",
    settings: "/admin/settings",
  },
  gaps: {
    evidencePreview: "/gaps/evidence-preview",
    analyze: "/gaps/analyze",
    analyzeStatus: (id: string) => `/gaps/analyze/${id}`,
    retryAnalysis: (id: string) => `/gaps/analyze/${id}/retry`,
    activeAnalysis: "/gaps/analyze/active",
    list: "/gaps",
    patch: (id: string) => `/gaps/${id}`,
    directions: (id: string) => `/gaps/${id}/directions`,
  },
  projects: {
    list: "/projects",
    create: "/projects",
    detail: (id: string) => `/projects/${id}`,
    update: (id: string) => `/projects/${id}`,
    delete: (id: string) => `/projects/${id}`,
    addPaper: (id: string) => `/projects/${id}/papers`,
    removePaper: (id: string, paperId: string) => `/projects/${id}/papers/${paperId}`,
    addMember: (id: string) => `/projects/${id}/members`,
    removeMember: (id: string, memberId: string) => `/projects/${id}/members/${memberId}`,
    chat: {
      send: (id: string) => `/projects/${id}/chat`,
      history: (id: string) => `/projects/${id}/chat`,
      events: (id: string) => `/projects/${id}/chat/events`,
      pin: (id: string, messageId: string) => `/projects/${id}/chat/${messageId}/pin`,
    },
    teamChat: {
      send: (id: string) => `/projects/${id}/team-chat`,
      history: (id: string) => `/projects/${id}/team-chat`,
      events: (id: string) => `/projects/${id}/team-chat/events`,
      read: (id: string, messageId: string) => `/projects/${id}/team-chat/${messageId}/read`,
      delete: (id: string, messageId: string) => `/projects/${id}/team-chat/${messageId}`,
    },
  }
} as const;
