/**
 * Centralised list of backend route paths. Use these everywhere instead of
 * string literals so renames stay safe and grep-able.
 */
export const API_ROUTES = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    oauthExchange: "/auth/oauth/exchange",
    me: "/auth/me",
    emails: "/auth/me/emails",
    academicOnboardingOptions: "/auth/academic-onboarding/options",
    academicProfile: "/auth/me/academic-profile",
    changePassword: "/auth/change-password",
    verifyEmail: "/auth/email/verify",
    resendEmailVerification: "/auth/email/resend",
    forgotPassword: "/auth/password/forgot",
    resetPassword: "/auth/password/reset",
  },
  academicProfiles: {
    me: "/academic-profiles/me",
    academicIdentities: "/academic-profiles/me/academic-identities",
    academicIdentity: (identityId: string) => `/academic-profiles/me/academic-identities/${identityId}`,
    public: (userId: string) => `/academic-profiles/${userId}`,
    byHandle: (handle: string) => `/academic-profiles/by-handle/${encodeURIComponent(handle)}`,
    forumActivity: (userId: string) => `/academic-profiles/${encodeURIComponent(userId)}/forum-activity`,
    publicHandle: "/academic-profiles/me/public-handle",
    avatar: "/academic-profiles/me/avatar",
    cover: "/academic-profiles/me/cover",
    summary: (userId: string) => `/academic-profiles/${userId}/summary`,
    lecturers: "/academic-profiles/lecturers",
      verificationStatus: "/academic-profiles/me/verification-status",
      verificationRequest: "/academic-profiles/me/verification-request",
      verificationEvidence: (requestId: string) => `/admin/academic-verifications/${requestId}/evidence`,
      institutionalEmailStatus: "/academic-profiles/me/institutional-email/status",
      institutionalEmailChallenge: "/academic-profiles/me/institutional-email/challenge",
      institutionalEmailVerify: "/academic-profiles/me/institutional-email/verify",
  },
  reviewAvailability: {
    mine: "/review-availability/me",
  },
  reviewOpportunities: {
    list: "/review-opportunities",
    accept: (submissionId: string) => `/review-opportunities/${submissionId}/accept`,
    conflict: (submissionId: string) => `/review-opportunities/${submissionId}/conflicts`,
  },
  reviews: {
    list: "/reviews",
    detail: (assignmentId: string) => `/reviews/${assignmentId}`,
    save: (assignmentId: string) => `/reviews/${assignmentId}`,
    submit: (assignmentId: string) => `/reviews/${assignmentId}/submit`,
  },
  reviewTemplates: {
    list: "/review-templates",
    detail: (templateId: string) => `/review-templates/${templateId}`,
    versions: (templateId: string) => `/review-templates/${templateId}/versions`,
    publish: (templateId: string) => `/review-templates/${templateId}/publish`,
    duplicate: (templateId: string) => `/review-templates/${templateId}/duplicate`,
    archive: (templateId: string) => `/review-templates/${templateId}/archive`,
  },
  reviewRequests: {
    revisionItem: (id: string, itemId: string) => `/review-requests/${id}/revision-items/${itemId}`,
    list: "/review-requests",
    reviewers: "/review-requests/reviewers",
    detail: (requestId: string) => `/review-requests/${requestId}`,
    accept: (requestId: string) => `/review-requests/${requestId}/accept`,
    decline: (requestId: string) => `/review-requests/${requestId}/decline`,
    cancel: (requestId: string) => `/review-requests/${requestId}/cancel`,
    resubmit: (requestId: string) => `/review-requests/${requestId}/resubmit`,
  },
  contributions: {
    user: (userId: string) => `/contributions/users/${userId}`,
  },
  submissions: {
    history: (id: string) => `/submissions/${id}/history`,
    versions: (id: string) => `/submissions/${id}/versions`,
    openReview: (id: string) => `/submissions/${id}/open-review`,
    list: "/submissions",
    create: "/submissions",
    detail: (id: string) => `/submissions/${id}`,
    revisions: (id: string) => `/submissions/${id}/revisions`,
    revisionDownload: (id: string, revisionId: string) => `/submissions/${id}/revisions/${revisionId}/download`,
    aiPreReviews: (id: string) => `/submissions/${id}/ai-pre-reviews`,
    runAiPreReview: (id: string) => `/submissions/${id}/ai-pre-review`,
  },
  communities: {
    list: "/communities",
    detail: (idOrSlug: string) => `/communities/${idOrSlug}`,
    join: (id: string) => `/communities/${id}/join`,
    leave: (id: string) => `/communities/${id}/membership`,
    members: (id: string) => `/communities/${id}/members`,
    member: (id: string, userId: string) => `/communities/${id}/members/${userId}`,
    review: (id: string) => `/communities/${id}/review`,
    facets: "/communities/facets",
    status: (id: string) => `/communities/${id}/status`,
    resubmit: (id: string) => `/communities/${id}/resubmit`,
    transferOwnership: (id: string) => `/communities/${id}/transfer-ownership`,
    publicMembers: (id: string) => `/communities/${id}/members/public`,
    relatedPapers: (id: string) => `/communities/${id}/related-papers`,
    relatedGaps: (id: string) => `/communities/${id}/related-gaps`,
    recommendations: "/communities/recommendations",
    suggestions: "/communities/suggestions",
    summary: (id: string) => `/communities/${id}/summary`,
  },
  forum: {
    posts: "/forum/posts",
    post: (id: string) => `/forum/posts/${id}`,
    postRevisions: (id: string) => `/forum/posts/${id}/revisions`,
    comments: (postId: string) => `/forum/posts/${postId}/comments`,
    postVote: (id: string) => `/forum/posts/${id}/vote`,
    commentVote: (id: string) => `/forum/comments/${id}/vote`,
    postReactions: (id: string) => `/forum/posts/${id}/reactions`,
    commentReactions: (id: string) => `/forum/comments/${id}/reactions`,
    acceptAnswer: (postId: string, commentId: string) => `/forum/posts/${postId}/accepted-answer/${commentId}`,
    acceptedAnswer: (postId: string) => `/forum/posts/${postId}/accepted-answer`,
    follow: (id: string) => `/forum/posts/${id}/follow`,
    context: "/forum/context",
    shareGap: (id: string) => `/forum/context/gaps/${id}/share`,
    postModeration: (id: string) => `/forum/posts/${id}/moderation`,
    commentModeration: (id: string) => `/forum/comments/${id}/moderation`,
    comment: (id: string) => `/forum/comments/${id}`,
    commentRevisions: (id: string) => `/forum/comments/${id}/revisions`,
    reports: "/forum/reports",
    moderationActions: "/forum/moderation/actions",
    reviewReport: (id: string) => `/forum/reports/${id}`,
  },
  home: {
    overview: "/home/overview",
    research: "/home/research",
  },
  papers: {
    list: "/papers",
    detail: (id: string) => `/papers/${id}`,
    translation: (id: string) => `/papers/${id}/translation`,
    translationCapabilities: "/papers/translation/capabilities",
    compare: "/papers/compare",
  },
  search: {
    semantic: "/search", 
  },
  trends: {
    topic: (topic: string) => `/trends/${encodeURIComponent(topic)}`,
  },
  reports: {
    list: "/reports",
    detail: (id: string) => `/reports/${id}`,
    create: "/reports",
    paperCount: (paperId: string) => `/reports/paper/${paperId}/count`,
    evidencePreview: "/reports/evidence-preview",
  },
  bookmarks: {
    list: "/bookmarks",
    create: "/bookmarks",
    delete: (id: string) => `/bookmarks/${id}`,
    check: "/bookmarks/check",
    updateNote: (id: string) => `/bookmarks/${id}`,
  },
  notifications: {
    list: "/notifications",
    read: (id: string) => `/notifications/${id}/read`,
    readAll: "/notifications/read-all",
  },
  analytics: {
    summary: "/analytics/search/summary",
    dashboard: "/analytics/search",
    me: "/analytics/search/me",
  },
  admin: {
    sync: "/admin/sync",
    syncRuns: "/admin/sync/runs",
    embedStatus: "/admin/embed/status",
    triggerEmbed: "/admin/embed",
    users: "/admin/users",
    usersSummary: "/admin/users/summary",
    user: (id: string) => `/admin/users/${id}`,
    userRole: (id: string) => `/admin/users/${id}/role`,
    userStatus: (id: string) => `/admin/users/${id}/status`,
    userSessions: (id: string) => `/admin/users/${id}/revoke-sessions`,
    stats: "/admin/stats",
    pipelineStatus: "/admin/pipeline/status",
    openAlexIngestPreflight: "/admin/openalex-ingest/preflight",
    openAlexIngestCampaigns: "/admin/openalex-ingest/campaigns",
    openAlexIngestCampaign: (id: string) => `/admin/openalex-ingest/campaigns/${id}`,
    startOpenAlexIngestCampaign: (id: string) => `/admin/openalex-ingest/campaigns/${id}/start`,
    pauseOpenAlexIngestCampaign: (id: string) => `/admin/openalex-ingest/campaigns/${id}/pause`,
    cancelOpenAlexIngestCampaign: (id: string) => `/admin/openalex-ingest/campaigns/${id}/cancel`,
    triggerCorpusValidation: (campaignId: string) => `/admin/openalex-ingest/campaigns/${campaignId}/validations`,
    latestCorpusValidation: (campaignId: string) => `/admin/openalex-ingest/campaigns/${campaignId}/validations/latest`,
    corpusValidationRun: (validationRunId: string) => `/admin/openalex-ingest/validations/${validationRunId}`,
    evaluationSummary: "/admin/evaluation/summary",
    academicVerifications: "/admin/academic-verifications",
    academicVerification: (profileId: string) => `/admin/academic-verifications/${profileId}`,
    auditLogs: "/admin/audit-logs",
    workers: "/admin/workers",
    settings: "/admin/settings",
  },
  gaps: {
    evidencePreview: "/gaps/evidence-preview",
    analyze: "/gaps/analyze",
    analyzeStatus: (id: string) => `/gaps/analyze/${id}`,
    retryAnalysis: (id: string) => `/gaps/analyze/${id}/retry`,
    activeAnalysis: "/gaps/analyze/active",
    list: "/gaps",
    patch: (id: string) => `/gaps/${id}`,
    directions: (id: string) => `/gaps/${id}/directions`,
    discussions: (id: string) => `/gaps/${id}/discussions`,
    reviewForumCitation: (id: string, referenceId: string) => `/gaps/${id}/forum-citations/${referenceId}/review-as-evidence`,
    forumCitationEvidenceOptions: (id: string, referenceId: string) => `/gaps/${id}/forum-citations/${referenceId}/evidence-options`,
    validationQueue: "/gaps/validation-queue",
    requestValidation: (id: string) => `/gaps/${id}/request-validation`,
    validations: (id: string) => `/gaps/${id}/validations`,
    evidence: (id: string) => `/gaps/${id}/evidence`,
  },
  projects: {
    list: "/projects",
    create: "/projects",
    detail: (id: string) => `/projects/${id}`,
    update: (id: string) => `/projects/${id}`,
    delete: (id: string) => `/projects/${id}`,
    addPaper: (id: string) => `/projects/${id}/papers`,
    updatePaper: (id: string, paperId: string) => `/projects/${id}/papers/${paperId}`,
    removePaper: (id: string, paperId: string) => `/projects/${id}/papers/${paperId}`,
    addMember: (id: string) => `/projects/${id}/members`,
    removeMember: (id: string, memberId: string) => `/projects/${id}/members/${memberId}`,
    archive: (id: string) => `/projects/${id}/archive`,
    leave: (id: string) => `/projects/${id}/leave`,
    transferOwnership: (id: string) => `/projects/${id}/transfer-ownership`,
    activity: (id: string) => `/projects/${id}/activity`,
    mentorships: {
      list: (id: string) => `/projects/${id}/mentorships`,
      request: (id: string) => `/projects/${id}/mentorships`,
      accept: (id: string, relationshipId: string) => `/projects/${id}/mentorships/${relationshipId}/accept`,
      decline: (id: string, relationshipId: string) => `/projects/${id}/mentorships/${relationshipId}/decline`,
      end: (id: string, relationshipId: string) => `/projects/${id}/mentorships/${relationshipId}/end`,
    },
    invitations: {
      mine: "/projects/invitations/mine",
      preview: (token: string) => `/projects/invitation-tokens/${encodeURIComponent(token)}`,
      acceptToken: (token: string) => `/projects/invitation-tokens/${encodeURIComponent(token)}/accept`,
      declineToken: (token: string) => `/projects/invitation-tokens/${encodeURIComponent(token)}/decline`,
      create: (id: string) => `/projects/${id}/invitations`,
      accept: (id: string, invitationId: string) => `/projects/${id}/invitations/${invitationId}/accept`,
      decline: (id: string, invitationId: string) => `/projects/${id}/invitations/${invitationId}/decline`,
      cancel: (id: string, invitationId: string) => `/projects/${id}/invitations/${invitationId}/cancel`,
    },
    chat: {
      send: (id: string) => `/projects/${id}/chat`,
      history: (id: string) => `/projects/${id}/chat`,
      events: (id: string) => `/projects/${id}/chat/events`,
      pin: (id: string, messageId: string) => `/projects/${id}/chat/${messageId}/pin`,
    },
    teamChat: {
      send: (id: string) => `/projects/${id}/team-chat`,
      history: (id: string) => `/projects/${id}/team-chat`,
      events: (id: string) => `/projects/${id}/team-chat/events`,
      read: (id: string, messageId: string) => `/projects/${id}/team-chat/${messageId}/read`,
      delete: (id: string, messageId: string) => `/projects/${id}/team-chat/${messageId}`,
    },
  }
} as const;
