import type { TrendCompareQuery, TrendExplainBody, TrendExplainHistoryQuery, TrendRelationshipQuery, TrendTopicCandidatesQuery, TopicTrendQuery, TrendsOverviewQuery } from "./dto/trends.schema.js";
import { AppError } from "../../common/exceptions/app-error.js";
import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import { cachedGenerateJSON } from "../llm/llm.run.js";
import { computeMetrics, fillMissingYears } from "./trend.formulas.js";
import { getPostgresTrendsOverview } from "./trend.postgres.js";

const WINDOW = 10;
function years(input: { yearFrom?: number; yearTo?: number }) { const yearTo = input.yearTo ?? new Date().getFullYear(); return { yearTo, yearFrom: input.yearFrom ?? yearTo - WINDOW, lastCompleteYear: Math.min(yearTo, new Date().getFullYear() - 1) }; }
async function topicRows(topic: string, input: { yearFrom?: number; yearTo?: number; topicId?: string }) { const span = years(input); const topics = await getPrisma().paperTopic.findMany({ where: input.topicId ? { openalexTopicId: { contains: input.topicId, mode: "insensitive" } } : { topicName: { equals: topic, mode: "insensitive" } } }); const ids = [...new Set(topics.map((row) => row.paperId))]; const papers = await getPrisma().paper.findMany({ where: { id: { in: ids }, dataStatus: "active", publicationYear: { gte: span.yearFrom, lte: span.yearTo } } }); return { span, papers, topics }; }
function series(papers: Array<{ publicationYear: number }>, yearFrom: number, yearTo: number) { const counts = new Map<number, number>(); for (const paper of papers) counts.set(paper.publicationYear, (counts.get(paper.publicationYear) ?? 0) + 1); return fillMissingYears([...counts].map(([year, count]) => ({ year, count })), yearFrom, yearTo); }
function citationSeries(papers: Array<{ publicationYear: number; citationCount: number }>, yearFrom: number, yearTo: number) { const groups = new Map<number, { count: number; citations: number }>(); for (const paper of papers) { const row = groups.get(paper.publicationYear) ?? { count: 0, citations: 0 }; row.count++; row.citations += paper.citationCount; groups.set(paper.publicationYear, row); } return Array.from({ length: yearTo - yearFrom + 1 }, (_, index) => { const year = yearFrom + index; const row = groups.get(year) ?? { count: 0, citations: 0 }; return { year, count: row.count, totalCitations: row.citations, avgCitations: row.count ? Math.round((row.citations / row.count) * 10) / 10 : 0 }; }); }
async function topAuthors(paperIds: string[]) { const rows = await getPrisma().paperAuthor.groupBy({ by: ["displayName"], where: { paperId: { in: paperIds } }, _count: { _all: true }, orderBy: { _count: { displayName: "desc" } }, take: 5 }); return rows.map((row) => ({ name: row.displayName, count: row._count._all })); }
async function topKeywords(paperIds: string[]) { const rows = await getPrisma().paperKeyword.groupBy({ by: ["keywordName"], where: { paperId: { in: paperIds } }, _count: { _all: true }, orderBy: { _count: { keywordName: "desc" } }, take: 5 }); return rows.map((row) => ({ name: row.keywordName, count: row._count._all })); }
function taxonomy(rows: Array<{ topicName: string; openalexTopicId: string | null; domainId: string | null; domainName: string | null; fieldId: string | null; fieldName: string | null; subfieldId: string | null; subfieldName: string | null }>) { const row = rows[0]; return row ? { topicId: row.openalexTopicId ?? undefined, topicName: row.topicName, domainId: row.domainId ?? undefined, domainName: row.domainName ?? undefined, fieldId: row.fieldId ?? undefined, fieldName: row.fieldName ?? undefined, subfieldId: row.subfieldId ?? undefined, subfieldName: row.subfieldName ?? undefined } : undefined; }

export const trendService = {
  overview(query: TrendsOverviewQuery) { return getPostgresTrendsOverview(query); },
  async topic(topic: string, query: TopicTrendQuery) { const { span, papers, topics } = await topicRows(topic, query); if (!papers.length) throw AppError.notFound(`No papers found for topic "${topic}" in ${span.yearFrom}-${span.yearTo}`); const yearlyBreakdown = series(papers, span.yearFrom, span.yearTo); const journals = new Map<string, number>(); for (const paper of papers) if (paper.journalName) journals.set(paper.journalName, (journals.get(paper.journalName) ?? 0) + 1); return { topic, taxonomy: taxonomy(topics), totalPapers: papers.length, yearlyBreakdown, citationTrend: citationSeries(papers, span.yearFrom, span.yearTo), facets: {}, lastCompleteYear: span.lastCompleteYear, ...computeMetrics(yearlyBreakdown, span.lastCompleteYear), topJournals: [...journals].sort((a, b) => b[1] - a[1]).slice(0, 5).map(([name, count]) => ({ name, count })), topAuthors: await topAuthors(papers.map((row) => row.id)), topKeywords: await topKeywords(papers.map((row) => row.id)), computedAt: new Date().toISOString() }; },
  async compare(query: TrendCompareQuery) { const span = years(query); const topics = await Promise.all([...new Set(query.topics)].map(async (topic) => { const detail = await this.topic(topic, query); return { topic, taxonomy: detail.taxonomy, totalPapers: detail.totalPapers, yearlyBreakdown: detail.yearlyBreakdown, citationTrend: detail.citationTrend, momentum: detail.momentum, growthRatePct: detail.growthRatePct }; })); return { ...span, topics, computedAt: new Date().toISOString() }; },
  async topicCandidates(query: TrendTopicCandidatesQuery) { const span = years(query); const rows = await getPrisma().paperTopic.groupBy({ by: ["topicName"], where: { topicName: { contains: query.q.trim(), mode: "insensitive" } }, _count: { _all: true }, orderBy: { _count: { topicName: "desc" } }, take: query.limit }); const topics = (await Promise.all(rows.filter((row) => row._count._all >= query.minPapers).map(async (row) => { const detail = await this.topic(row.topicName, span); return { topic: row.topicName, taxonomy: detail.taxonomy, totalPapers: detail.totalPapers, yearlyBreakdown: detail.yearlyBreakdown, matchedBy: "topic", momentum: detail.momentum, growthRatePct: detail.growthRatePct }; }))).slice(0, query.limit); return { query: query.q.trim(), ...span, totalCandidates: topics.length, topics, computedAt: new Date().toISOString() }; },
  async relationships(query: TrendRelationshipQuery) { const { span, papers } = await topicRows(query.topic, query); const sourceIds = new Set(papers.map((paper) => paper.id)); const rows = await getPrisma().paperTopic.findMany({ where: { paperId: { in: [...sourceIds] }, topicName: { not: query.topic } } }); const grouped = new Map<string, Set<string>>(); for (const row of rows) { const ids = grouped.get(row.topicName) ?? new Set(); ids.add(row.paperId); grouped.set(row.topicName, ids); } const related = [...grouped].map(([name, ids]) => ({ name, count: ids.size })).sort((a, b) => b.count - a.count).slice(0, query.limit); return { topic: query.topic, yearFrom: span.yearFrom, yearTo: span.yearTo, nodes: [{ id: query.topic, label: query.topic, count: papers.length }, ...related.map((row) => ({ id: row.name, label: row.name, count: row.count }))], edges: related.map((row) => ({ source: query.topic, target: row.name, count: row.count })), computedAt: new Date().toISOString() }; },
  async explain(input: TrendExplainBody, userId?: string) { const overview = await this.overview({ ...input, limit: 10, minPapers: 3, sortBy: "momentum" }); const detail = input.topic ? await this.topic(input.topic, input).catch(() => null) : null; const explanation = await cachedGenerateJSON<any>({ task: "trend", promptVersion: "trend-explain-v2", keyParts: { topic: input.topic ?? null, yearFrom: input.yearFrom, yearTo: input.yearTo, language: input.language }, model: undefined, prompt: `Explain these deterministic research trend metrics in ${input.language}. Do not invent values.\n${JSON.stringify({ overview, detail })}`, options: { temperature: 0.2, maxOutputTokens: 1000 }, validate: (value) => value }); if (userId) { const owner = await getPrisma().user.findUnique({ where: whereId(userId) }); if (owner) await getPrisma().trendExplanation.create({ data: { userId: owner.id, topic: input.topic, language: input.language, yearFrom: input.yearFrom ?? overview.yearFrom, yearTo: input.yearTo ?? overview.yearTo, scopeHash: "postgres", scopeLabel: "PostgreSQL corpus", scopeFilters: input as never, explanation: explanation as never } }); } return explanation; },
  async explainHistory(userId: string, query: TrendExplainHistoryQuery) { const owner = await getPrisma().user.findUnique({ where: whereId(userId) }); if (!owner) return { items: [] }; const rows = await getPrisma().trendExplanation.findMany({ where: { userId: owner.id, ...(query.topic ? { topic: query.topic } : {}) }, orderBy: { createdAt: "desc" }, take: query.limit }); return { items: rows.map((row) => ({ ...(row.explanation as object), id: publicDatabaseId(row), yearFrom: row.yearFrom, yearTo: row.yearTo, scopeHash: row.scopeHash, scopeLabel: row.scopeLabel, createdAt: row.createdAt.toISOString() })) }; },
};

function whereId(value: string) { const parsed = parseDatabaseId(value); if (!parsed) throw AppError.badRequest("Invalid identifier"); return parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; }
