import { randomUUID } from "node:crypto";
import type { AnalyticalReport, PreviewReportEvidenceResponse, ReportListItem } from "@trend/shared-types";
import { AppError } from "../../common/exceptions/app-error.js";
import { env } from "../../config/env.js";
import { parseDatabaseId, publicDatabaseId } from "../../infrastructure/database/database-id.js";
import { getPrisma } from "../../infrastructure/database/prisma.js";
import { logger } from "../../infrastructure/logger.js";
import { reportQueue } from "../../infrastructure/queue.js";
import { creditService } from "../credits/credit.service.js";
import { resolveReportCreditCost } from "../credits/credit-policy.js";
import { getEmbeddingProvider } from "../embeddings/embedding.factory.js";
import { paperService } from "../papers/paper.service.js";
import { projectService } from "../projects/project.service.js";
import { resolveProjectEvidenceIds } from "../projects/project-scope.js";
import type { CreateReportInput, ListReportsQuery, PreviewReportEvidenceInput } from "./dto/report.schema.js";
import { collectReportEvidence } from "./report.evidence.js";
import { artifactDeleteError, artifactStatusChangeError, type ArtifactReviewState } from "./artifact-status.rules.js";
import { ACTIVE_REVIEW_REQUEST_STATUSES } from "../reviews/review.constants.js";

const STALE_GENERATING_MS = 5 * 60_000;
function whereId(value: string) { const parsed = parseDatabaseId(value); if (!parsed) throw AppError.badRequest("Invalid identifier"); return parsed.kind === "uuid" ? { id: parsed.value } : { legacyMongoId: parsed.value }; }
async function user(value: string) { const row = await getPrisma().user.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("User not found"); return row; }
async function report(value: string) { const row = await getPrisma().report.findUnique({ where: whereId(value) }); if (!row) throw AppError.notFound("Report not found"); return row; }
async function canAccessProject(projectId: string, userId: string) { const project = await getPrisma().project.findUnique({ where: { id: projectId } }); if (!project) return false; if (project.ownerId === userId) return true; const member = await getPrisma().projectMember.findUnique({ where: { projectId_userId: { projectId, userId } } }); return member?.status === "ACTIVE"; }

async function artifactReviewState(reportId: string): Promise<ArtifactReviewState> {
  const submission = await getPrisma().submission.findUnique({ where: { sourceReportId: reportId }, select: { id: true } });
  if (!submission) return { activeRequestCount: 0, completedRequestCount: 0 };
  const [activeRequestCount, completedRequestCount] = await Promise.all([
    getPrisma().reviewRequest.count({ where: { submissionId: submission.id, status: { in: ACTIVE_REVIEW_REQUEST_STATUSES } } }),
    getPrisma().reviewRequest.count({ where: { submissionId: submission.id, status: "COMPLETED" } }),
  ]);
  return { activeRequestCount, completedRequestCount };
}

async function dto(row: Awaited<ReturnType<typeof report>>): Promise<AnalyticalReport> { const artifactReview = row.projectId ? await artifactReviewState(row.id) : undefined; const links = await getPrisma().reportPaper.findMany({ where: { reportId: row.id }, orderBy: { position: "asc" } }); const groundingPaperIds = links.filter((link) => link.kind === "grounding").map((link) => link.paperId); const selectedPaperIds = links.filter((link) => link.kind === "selected").map((link) => link.paperId); return { ...row, id: publicDatabaseId(row), groundingPaperIds, selectedPaperIds, researchGaps: row.researchGapSnapshots, artifactReview } as unknown as AnalyticalReport; }

export const reportService = {
  async create(userIdInput: string, input: CreateReportInput): Promise<{ id: string; status: string }> {
    const owner = await user(userIdInput); const selectedPaperIds = await resolveReportEvidenceScope(userIdInput, input);
    const pending = await getPrisma().report.count({ where: { userId: owner.id, OR: [{ status: "queued" }, { status: "generating", updatedAt: { gte: new Date(Date.now() - STALE_GENERATING_MS) } }] } });
    if (pending >= env.REPORT_MAX_PENDING_PER_USER) throw AppError.tooMany(`You already have ${pending} report(s) in progress — wait for them to finish first.`);
    const reportId = randomUUID(); const { action, cost } = resolveReportCreditCost({ fast: input.fast, deepAnalysis: input.deepAnalysis }); let txId: string | undefined;
    if (cost > 0) { const tx = await creditService.chargeCreditsChecked({ userId: userIdInput, action, amount: cost, targetKind: "report", targetId: reportId, idempotencyKey: `report:${reportId}` }); txId = tx?.id ?? tx?._id?.toString(); }
    try { const project = input.projectId ? await getPrisma().project.findUnique({ where: whereId(input.projectId) }) : null; const created = await getPrisma().$transaction(async (tx) => { const title = (input.title ?? input.topic ?? input.query).slice(0, 240); const row = await tx.report.create({ data: { id: reportId, userId: owner.id, query: input.query, title, topic: input.topic, projectId: project?.id, artifactType: input.artifactType, artifactStatus: "DRAFT", isAiGenerated: true, yearFrom: input.yearFrom, yearTo: input.yearTo, scopeFilters: (input.scopeFilters ?? {}) as never, language: input.language ?? "auto", deepAnalysis: input.deepAnalysis ?? false, fast: input.fast ?? false, status: "queued", creditTransactionId: txId, creditCost: cost, creditAction: action } }); const resolved = await Promise.all((selectedPaperIds ?? []).map(async (id) => getPrisma().paper.findUnique({ where: whereId(id), select: { id: true } }))); if (resolved.length) await tx.reportPaper.createMany({ data: resolved.flatMap((paper, position) => paper ? [{ reportId: row.id, paperId: paper.id, kind: "selected", position }] : []), skipDuplicates: true }); if (project) await tx.projectActivity.create({ data: { projectId: project.id, actorId: owner.id, type: "REPORT_CREATED", entityKind: "REPORT", entityId: publicDatabaseId(row), metadata: { title, artifactType: input.artifactType } } }); return row; }); await reportQueue.add("generate-report", { reportId: created.id }, { jobId: created.id }); return { id: publicDatabaseId(created), status: "queued" }; } catch (error) { if (txId) await creditService.refundCreditsOnce({ transactionId: txId, reason: "Failed to create report or enqueue job" }); throw error; }
  },
  async previewEvidence(userId: string, input: PreviewReportEvidenceInput): Promise<PreviewReportEvidenceResponse> { const selectedPaperIds = await resolveReportEvidenceScope(userId, input); const fillWithRetrieved = input.projectId ? false : input.fillWithRetrieved; let queryVector: number[] | undefined; let usedTextFallback = false; if (fillWithRetrieved ?? true) { try { queryVector = await getEmbeddingProvider().embed(input.query); } catch (error) { usedTextFallback = true; logger.warn({ error }, "report evidence preview embedding failed; using text fallback"); } } const evidence = await collectReportEvidence({ queryText: input.query, queryVector, selectedPaperIds, yearFrom: input.yearFrom, yearTo: input.yearTo, scopeFilters: input.scopeFilters, fillWithRetrieved }); const warnings = evidence.missingSelectedPaperIds.map((id) => `Selected paper ${id} was not found in the active corpus and was skipped.`); if (usedTextFallback) warnings.push("Semantic embedding was unavailable, so the evidence preview used keyword fallback."); if (!evidence.papers.length) warnings.push("No active evidence papers were found for this query."); return { papers: evidence.papers, retrievedPaperIds: evidence.retrievedPaperIds, selectedPaperIds: evidence.selectedPaperIds, maxEvidencePapers: evidence.maxEvidencePapers, warnings }; },
  async list(userIdInput: string, { page, pageSize, projectId, paperId }: ListReportsQuery) { const owner = await user(userIdInput); let where: Record<string, unknown> = { userId: owner.id }; if (projectId) { const project = await getPrisma().project.findUnique({ where: whereId(projectId) }); if (!project || !await canAccessProject(project.id, owner.id)) throw AppError.notFound("Project not found"); where = { projectId: project.id }; } if (paperId) { const paper = await getPrisma().paper.findUnique({ where: whereId(paperId) }); if (!paper) return { reports: [], total: 0 }; const links = await getPrisma().reportPaper.findMany({ where: { paperId: paper.id }, select: { reportId: true } }); where = { ...where, id: { in: links.map((link) => link.reportId) } }; } const [rows, total] = await Promise.all([getPrisma().report.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize }), getPrisma().report.count({ where })]); const reports = await Promise.all(rows.map(dto)); return { reports: reports.map(({ markdown: _markdown, ...item }) => item as ReportListItem), total }; },
  async getById(userIdInput: string, id: string) { const [owner, row] = await Promise.all([user(userIdInput), report(id)]); if (row.userId !== owner.id && (!row.projectId || !await canAccessProject(row.projectId, owner.id))) throw AppError.notFound("Report not found"); const result = await dto(row); result.groundingPapers = await paperService.getSummariesByIds(result.groundingPaperIds ?? []); return result; },
  async updateArtifactStatus(userIdInput: string, id: string, status: "DRAFT" | "REVIEWING" | "FINAL" | "ARCHIVED") { const [actor, row] = await Promise.all([user(userIdInput), report(id)]); if (!row.projectId) throw AppError.badRequest("Only project reports have an artifact workflow"); const project = await getPrisma().project.findUnique({ where: { id: row.projectId } }); if (!project || (row.userId !== actor.id && project.ownerId !== actor.id)) throw AppError.forbidden("Only the artifact creator or project owner can update its status"); if (project.status === "ARCHIVED") throw AppError.conflict("Archived projects are read-only"); const transitionError = artifactStatusChangeError(status, await artifactReviewState(row.id)); if (transitionError) throw AppError.conflict(transitionError); const updated = await getPrisma().$transaction(async (tx) => { const next = await tx.report.update({ where: { id: row.id }, data: { artifactStatus: status } }); await tx.projectActivity.create({ data: { projectId: row.projectId!, actorId: actor.id, type: status === "FINAL" ? "REPORT_FINALIZED" : "REPORT_STATUS_CHANGED", entityKind: "REPORT", entityId: publicDatabaseId(row), metadata: { title: row.topic ?? row.query, artifactStatus: status } } }); return next; }); return dto(updated); },
  async deleteById(userIdInput: string, id: string) { const [owner, row] = await Promise.all([user(userIdInput), report(id)]); if (row.userId !== owner.id) throw AppError.notFound("Report not found or not owned by you"); const deleteError = artifactDeleteError(await artifactReviewState(row.id)); if (deleteError) throw AppError.conflict(deleteError); await getPrisma().$transaction([getPrisma().bookmark.deleteMany({ where: { userId: owner.id, reportId: row.id } }), getPrisma().report.delete({ where: { id: row.id } })]); },
  async deleteBatch(userIdInput: string, ids: string[]) { const owner = await user(userIdInput); const rows = (await Promise.all(ids.map((id) => getPrisma().report.findUnique({ where: whereId(id), select: { id: true, userId: true } })))).filter((row): row is NonNullable<typeof row> => Boolean(row && row.userId === owner.id)); const reportIds = rows.map((row) => row.id); const reviewed = (await Promise.all(reportIds.map(async (reportId) => artifactDeleteError(await artifactReviewState(reportId))))).filter(Boolean).length; if (reviewed) throw AppError.conflict(`${reviewed} of the selected report(s) have been sent for review and cannot be deleted. Archive them instead.`); await getPrisma().$transaction([getPrisma().bookmark.deleteMany({ where: { userId: owner.id, reportId: { in: reportIds } } }), getPrisma().report.deleteMany({ where: { id: { in: reportIds }, userId: owner.id } })]); },
  async countByPaper(paperId: string) { const paper = await getPrisma().paper.findUnique({ where: whereId(paperId), select: { id: true } }); if (!paper) return 0; const links = await getPrisma().reportPaper.findMany({ where: { paperId: paper.id }, select: { reportId: true } }); return getPrisma().report.count({ where: { id: { in: links.map((link) => link.reportId) }, status: "ready" } }); },
};

async function resolveReportEvidenceScope(userId: string, input: Pick<CreateReportInput, "projectId" | "selectedPaperIds">) { if (!input.projectId) return input.selectedPaperIds; const projectPaperIds = await projectService.getProjectPaperIdsForUser(input.projectId, userId, "report"); const resolved = resolveProjectEvidenceIds(projectPaperIds, input.selectedPaperIds); if (resolved.invalidIds.length) throw AppError.badRequest("Selected evidence papers must belong to the project.", { invalidPaperIds: resolved.invalidIds }); return resolved.ids; }
